// GENERATED BY tool/import_legal.mjs — DO NOT EDIT.
// Source: legal/source/17_Accessibility_Statement.docx
//
// Edit the Word document, run `node tool/import_legal.mjs`, commit both.
import 'package:zopiq_legal/src/legal_document.dart';

const LegalDocument accessibilityStatement = LegalDocument(
  slug: 'accessibility-statement',
  title: 'Accessibility Statement',
  subtitle: 'Our Commitment to Accessible Digital Services',
  docId: 'ZOPIQ-LEGAL-17',
  version: '1.0',
  effectiveDate: '18 August 2026',
  group: 'support',
  audiences: <LegalAudience>{LegalAudience.customer, LegalAudience.restaurant, LegalAudience.rider},
  requiresConsent: false,
  blocks: <LegalBlock>[
    LegalHeading(1, 'Document Control & Version History'),
    LegalParagraph(
      'This document is maintained under version control. Any material '
          'amendment will be recorded in the table below and reflected in the '
          'version number and effective date on the cover page.',
    ),
    LegalTable(
      headers: <String>['Version', 'Date', 'Summary of Changes', 'Approved By'],
      rows: <List<String>>[
        <String>['1.0', '18 August 2026', 'Initial publication-ready version.', 'Hybrid Monks LLP'],
      ],
    ),
    LegalHeading(1, '1. INTRODUCTION'),
    LegalParagraph(
      'This Accessibility Statement ("Statement") explains the commitment of '
          'Zopiq, operated by Hybrid Monks LLP ("Zopiq", "Company", "we", "our", or '
          '"us"), to making its website and applications accessible to as many '
          'people as possible, including people with disabilities. Accessibility is '
          'an ongoing effort, and this Statement describes our goals, current '
          'approach, and how to give feedback.',
    ),
    LegalHeading(1, '2. ACCESSIBILITY GOALS'),
    LegalParagraph(
      'Our accessibility goals are to:',
    ),
    LegalBullets(<String>[
        'Make core functions — browsing, ordering, and account management — '
            'usable by as many people as possible.',
        'Work towards recognised accessibility guidance for digital products.',
        'Support assistive technologies commonly used on mobile and web.',
        'Continuously identify and address accessibility barriers.',
    ]),
    LegalParagraph(
      'We aim to align our efforts with widely recognised accessibility '
          'principles, understanding that full conformance across all features is '
          'an ongoing process.',
    ),
    LegalHeading(1, '3. MEASURES WE TAKE'),
    LegalParagraph(
      'To support accessibility, Zopiq seeks to:',
    ),
    LegalBullets(<String>[
        'Consider accessibility when designing new features, consistent with '
            'privacy-by-design and accessibility-by-design principles.',
        'Use clear layouts, readable text, and understandable navigation where '
            'practicable.',
        'Provide text alternatives for meaningful non-text elements where '
            'feasible.',
        'Test key flows and address identified barriers over time.',
    ]),
    LegalHeading(1, '4. SUPPORTED TECHNOLOGIES'),
    LegalParagraph(
      'Our applications and website are designed to work on commonly used '
          'devices and platforms.',
    ),
    LegalTable(
      headers: <String>['Area', 'Approach'],
      rows: <List<String>>[
        <String>['Mobile devices', 'Support for widely used Android and iOS devices and current '
              'operating-system versions where practicable.'],
        <String>['Web browsers', 'Support for commonly used, up-to-date web browsers.'],
        <String>['Assistive technologies', 'Aim to support common assistive technologies such as screen readers '
              'and system accessibility settings.'],
        <String>['System settings', 'Respect device-level settings such as text size and display '
              'preferences where feasible.'],
      ],
    ),
    LegalParagraph(
      'Because devices, browsers, and assistive technologies vary, some '
          'features may work better in certain environments than others.',
    ),
    LegalHeading(1, '5. KNOWN LIMITATIONS'),
    LegalParagraph(
      'Despite our efforts, some parts of the website or applications may not '
          'yet be fully accessible. Third-party content and integrations may also '
          'have accessibility limitations outside our direct control. We are '
          'committed to identifying and addressing such limitations over time and '
          'welcome feedback that helps us prioritise improvements.',
    ),
    LegalHeading(1, '6. FEEDBACK PROCESS'),
    LegalParagraph(
      'We welcome feedback on the accessibility of our website and '
          'applications.',
    ),
    LegalHeading(2, '6.1 How to Contact Us'),
    LegalParagraph(
      'If you encounter an accessibility barrier or have suggestions, please '
          'contact us by email at hello@hybridmonks.com, by phone at +91 96608 '
          '77411, or by writing to our registered office. Where possible, please '
          'describe the issue, the page or feature involved, and the device or '
          'assistive technology you were using, so we can investigate effectively.',
    ),
    LegalHeading(2, '6.2 Our Response'),
    LegalParagraph(
      'We aim to acknowledge accessibility feedback and respond within a '
          'reasonable timeframe, and to use it to improve our products.',
    ),
    LegalHeading(1, '7. CONTINUOUS IMPROVEMENT'),
    LegalParagraph(
      'Accessibility is an ongoing commitment. We intend to review '
          'accessibility as we develop new features, consider user feedback, and '
          'work towards reducing barriers over time. This Statement will be updated '
          'to reflect meaningful changes in our approach.',
    ),
    LegalHeading(1, '8. CHANGES TO THIS STATEMENT'),
    LegalParagraph(
      'Zopiq may update this Statement from time to time to reflect changes in '
          'our products, practices, or applicable guidance. The "Last Updated" date '
          'on the cover page indicates the latest version.',
    ),
    LegalHeading(1, '9. CONTACT INFORMATION'),
    LegalParagraph(
      'For questions, requests, or concerns relating to this document, please '
          'contact:',
    ),
    LegalParagraph(
      'Hybrid Monks LLP',
    ),
    LegalParagraph(
      'Brand: Zopiq',
    ),
    LegalParagraph(
      'Registered Office: C/O Meena Dev, Main Road, Sadri, Rajasthan – 306702, '
          'India',
    ),
    LegalParagraph(
      'Email: hello@hybridmonks.com',
    ),
    LegalParagraph(
      'Phone: +91 96608 77411',
    ),
    LegalParagraph(
      'GSTIN: 08AATFH7649R1Z2',
    ),
  ],
);
