// GENERATED BY tool/import_legal.mjs — DO NOT EDIT.
// Source: legal/source/Zopiq_Account_Deletion_Data_Retention_Policy.docx
//
// Edit the Word document, run `node tool/import_legal.mjs`, commit both.
import 'package:zopiq_legal/src/legal_document.dart';

const LegalDocument accountDeletionDataRetentionPolicy = LegalDocument(
  slug: 'account-deletion-data-retention-policy',
  title: 'Zopiq Account Deletion &',
  subtitle: null,
  docId: null,
  version: '1.0',
  effectiveDate: '18 August 2026',
  group: 'core',
  audiences: <LegalAudience>{LegalAudience.customer, LegalAudience.restaurant, LegalAudience.rider},
  requiresConsent: false,
  blocks: <LegalBlock>[
    LegalHeading(1, '1. INTRODUCTION AND SCOPE'),
    LegalParagraph(
      'Applies to Customers, Restaurant Partners, and Delivery Partners.',
    ),
    LegalParagraph(
      'This Account Deletion & Data Retention Policy ("Policy") explains how '
          'users of the Zopiq platform, operated by Hybrid Monks LLP ("Zopiq", '
          '"Company", "we", "our", or "us"), may request deletion of their '
          'accounts, and how Zopiq retains and disposes of personal data. This '
          'Policy should be read together with the Zopiq Terms & Conditions and the '
          'Zopiq Privacy Policy, each of which forms an integral part of the '
          'arrangement between the user and Hybrid Monks LLP. In the event of any '
          'conflict regarding the handling of personal data, the Privacy Policy '
          'governs to the extent of that conflict, unless applicable law requires '
          'otherwise.',
    ),
    LegalParagraph(
      'This Policy is prepared considering the Digital Personal Data Protection '
          'Act, 2023 (India), the Information Technology Act, 2000, and other '
          'applicable Indian laws.',
    ),
    LegalHeading(1, '2. DEFINITIONS'),
    LegalParagraph(
      'Account means the registered profile created by a Customer, Restaurant '
          'Partner, or Delivery Partner.',
    ),
    LegalParagraph(
      'Deletion means the removal or anonymization of personal data associated '
          'with an Account, subject to the retention exceptions set out in this '
          'Policy.',
    ),
    LegalParagraph(
      'Anonymization means processing personal data so that it can no longer be '
          'attributed to an identified or identifiable individual without '
          'additional information.',
    ),
    LegalParagraph(
      'Retention Period means the period for which a category of data is kept, '
          'determined by legal, tax, accounting, fraud-prevention, '
          'dispute-resolution, and legitimate business requirements.',
    ),
    LegalHeading(1, '3. ACCOUNT DELETION'),
    LegalParagraph(
      'Users may request deletion through the app or support. Identity '
          'verification may be required.',
    ),
    LegalParagraph(
      'Requests may be submitted through the account settings within the '
          'Platform or by contacting Customer Support using the details in this '
          'Policy. To protect users against unauthorised deletion, Zopiq may verify '
          'the identity of the requester before processing a deletion request.',
    ),
    LegalHeading(2, '3.1 What Deletion Involves'),
    LegalParagraph(
      'Once a deletion request is verified and accepted, deletion generally '
          'results in:',
    ),
    LegalBullets(<String>[
        'Removal of access to the Platform.',
        'Deactivation of the Account.',
        'Deletion or anonymization of personal data where legally permissible.',
    ]),
    LegalHeading(2, '3.2 Processing Time'),
    LegalParagraph(
      'Zopiq will process verified deletion requests within a reasonable '
          'timeframe, subject to the completion of any pending orders, settlements, '
          'investigations, or legal obligations.',
    ),
    LegalHeading(2, '3.3 Irreversibility'),
    LegalParagraph(
      'Once processed, deleted Accounts and associated personal data may not be '
          'recoverable.',
    ),
    LegalHeading(1, '4. CUSTOMERS'),
    LegalParagraph(
      'Accounts can be deleted after request. Order history and legally '
          'required records may be retained.',
    ),
    LegalParagraph(
      'Customer order history, transaction records, and related information may '
          'be retained where necessary for customer support, dispute resolution, '
          'fraud prevention, and tax, accounting, or other legal obligations, even '
          'after the Account is deleted, in accordance with the Retention Schedule '
          'in this Policy.',
    ),
    LegalHeading(1, '5. RESTAURANT PARTNERS'),
    LegalParagraph(
      'Deletion is processed after settlement of dues and completion of legal '
          'obligations.',
    ),
    LegalParagraph(
      'Restaurant Partners must ensure that all outstanding settlements, '
          'obligations, invoices, and compliance requirements are completed before '
          'an Account deletion can be finalised. Settlement records, tax invoices, '
          'and financial documents may be retained for statutory '
          'financial-reporting and audit purposes.',
    ),
    LegalHeading(1, '6. DELIVERY PARTNERS'),
    LegalParagraph(
      'Deletion is processed after payout reconciliation and completion of '
          'legal obligations.',
    ),
    LegalParagraph(
      'Delivery Partners must ensure that all pending payouts are reconciled '
          'and any outstanding obligations are completed before an Account deletion '
          'can be finalised. Earnings records, payout history, and '
          'identity-verification records may be retained where required for '
          'statutory, tax, or fraud-prevention purposes.',
    ),
    LegalHeading(1, '7. DATA RETENTION'),
    LegalParagraph(
      'Information is retained only as long as necessary for legal, tax, fraud '
          'prevention, dispute resolution, and accounting purposes.',
    ),
    LegalParagraph(
      'The Retention Period for each category of data depends on the type of '
          'information and the purpose for which it was collected. Where retention '
          'is no longer necessary, Zopiq will delete or anonymize the information '
          'unless continued retention is required or permitted by applicable law.',
    ),
    LegalHeading(1, '8. RETENTION SCHEDULE (SUMMARY)'),
    LegalParagraph(
      'The following table provides a general overview of how Zopiq retains '
          'different categories of information after an Account is deleted or '
          'becomes inactive. Actual retention periods may vary where longer '
          'retention is required by law or necessary for fraud prevention, dispute '
          'resolution, or legitimate business purposes.',
    ),
    LegalTable(
      headers: <String>['Data Category', 'Retention Approach'],
      rows: <List<String>>[
        <String>['Account Information', 'Deleted or anonymized after the deletion request is processed, '
              'subject to any period required by law or legitimate business needs.'],
        <String>['Order History', 'Retained as necessary for legal, tax, accounting, fraud prevention, '
              'and customer support purposes.'],
        <String>['Payment Records', 'Retained in accordance with applicable tax and accounting laws.'],
        <String>['Restaurant Settlement Records', 'Retained in accordance with applicable financial and tax '
              'obligations.'],
        <String>['Delivery Payout Records', 'Retained in accordance with applicable financial and tax '
              'obligations.'],
        <String>['Identity Verification Records', 'Retained where required for statutory, fraud-prevention, or '
              'dispute-resolution purposes.'],
        <String>['Customer Support Records', 'Retained for service quality, dispute resolution, and legal '
              'compliance.'],
        <String>['Security & Fraud Logs', 'Retained for security monitoring and incident investigation for an '
              'appropriate period.'],
      ],
    ),
    LegalParagraph(
      'Where information is no longer needed, Zopiq will delete it or anonymize '
          'it, unless retention is required or permitted by law.',
    ),
    LegalHeading(1, '9. RETENTION EXCEPTIONS'),
    LegalParagraph(
      'Notwithstanding a deletion request, certain information may be retained '
          'where necessary to:',
    ),
    LegalBullets(<String>[
        'Comply with legal, tax, accounting, or regulatory obligations.',
        'Complete pending financial settlements or payouts.',
        'Detect, prevent, or investigate fraud or unlawful activity.',
        'Resolve disputes or enforce agreements.',
        'Maintain records required for audit or statutory compliance.',
    ]),
    LegalParagraph(
      'Deletion of an Account does not automatically erase information that '
          'Zopiq is legally required or otherwise permitted to retain.',
    ),
    LegalHeading(1, '10. RE-REGISTRATION'),
    LegalParagraph(
      'Users may create a new account unless permanently banned for policy '
          'violations.',
    ),
    LegalParagraph(
      'Zopiq reserves the right to refuse re-registration, or to link a new '
          'Account to a previously terminated one, where an Account was permanently '
          'terminated for fraud, abuse, or serious or repeated policy violations, '
          'subject to applicable law.',
    ),
    LegalHeading(1, '11. USER RIGHTS'),
    LegalParagraph(
      'Subject to applicable law, users may request confirmation of whether '
          'their personal data is being processed, access to certain personal '
          'information, correction of inaccurate information, deletion of personal '
          'data where legally permissible, and withdrawal of consent where '
          'processing is based on consent. These rights may be subject to legal '
          'limitations, including where retaining or processing information is '
          'necessary to comply with legal obligations, prevent fraud, or resolve '
          'disputes. Requests may be submitted using the contact details in this '
          'Policy.',
    ),
    LegalHeading(1, '12. SECURITY OF RETAINED DATA'),
    LegalParagraph(
      'Data retained after Account deletion is protected using administrative, '
          'technical, and organizational safeguards appropriate to the nature of '
          'the information, consistent with the Zopiq Privacy Policy. Access to '
          'retained data is restricted to authorised personnel and permitted '
          'purposes only.',
    ),
    LegalHeading(1, '13. CHANGES TO THIS POLICY'),
    LegalParagraph(
      'Zopiq may update this Policy from time to time to reflect changes in '
          'law, Platform features, business operations, or regulatory requirements. '
          'Material changes will be communicated through the Platform or by other '
          'reasonable means. The "Last Updated" date above will indicate the latest '
          'version.',
    ),
    LegalHeading(1, '14. CONTACT'),
    LegalParagraph(
      'Hybrid Monks LLP, hello@hybridmonks.com, +91 9660877411',
    ),
    LegalParagraph(
      'For account deletion or data-retention questions or requests, please '
          'contact:',
    ),
    LegalParagraph(
      'Hybrid Monks LLP',
    ),
    LegalParagraph(
      'Brand: Zopiq',
    ),
    LegalParagraph(
      'Email: hello@hybridmonks.com',
    ),
    LegalParagraph(
      'Phone: +91 96608 77411',
    ),
    LegalParagraph(
      'Address: C/O Meena Dev, Main Road, Sadri, Rajasthan – 306702, India',
    ),
  ],
);
