// GENERATED BY tool/import_legal.mjs — DO NOT EDIT.
// Source: legal/source/18_AI_Usage_and_Automated_Decision_Policy.docx
//
// Edit the Word document, run `node tool/import_legal.mjs`, commit both.
import 'package:zopiq_legal/src/legal_document.dart';

const LegalDocument aiUsageAndAutomatedDecisionPolicy = LegalDocument(
  slug: 'ai-usage-and-automated-decision-policy',
  title: 'AI Usage & Automated Decision Policy',
  subtitle: 'Use of Automation, Oversight, and User Rights',
  docId: 'ZOPIQ-LEGAL-18',
  version: '1.0',
  effectiveDate: '18 August 2026',
  group: 'data',
  audiences: <LegalAudience>{LegalAudience.customer, LegalAudience.restaurant, LegalAudience.rider},
  requiresConsent: false,
  blocks: <LegalBlock>[
    LegalHeading(1, 'Document Control & Version History'),
    LegalParagraph(
      'This document is maintained under version control. Any material '
          'amendment will be recorded in the table below and reflected in the '
          'version number and effective date on the cover page.',
    ),
    LegalTable(
      headers: <String>['Version', 'Date', 'Summary of Changes', 'Approved By'],
      rows: <List<String>>[
        <String>['1.0', '18 August 2026', 'Initial publication-ready version.', 'Hybrid Monks LLP'],
      ],
    ),
    LegalHeading(1, '1. INTRODUCTION'),
    LegalParagraph(
      'This AI Usage & Automated Decision Policy ("Policy") explains how Zopiq, '
          'operated by Hybrid Monks LLP ("Zopiq", "Company", "we", "our", or "us"), '
          'uses automated systems, including artificial intelligence and '
          'algorithmic processing, on the Platform. It describes where automation '
          'is used, the role of human oversight, and the rights available to Users. '
          'It supplements the Privacy Policy.',
    ),
    LegalParagraph(
      'Zopiq uses automation to make the Platform more efficient, secure, and '
          'useful, while seeking to remain fair and transparent and to respect '
          'Users\' rights under applicable law, including the Digital Personal Data '
          'Protection Act, 2023.',
    ),
    LegalHeading(1, '2. DEFINITIONS'),
    LegalParagraph(
      'Automated Processing means processing carried out by systems, including '
          'algorithms and AI, with limited or no human intervention at the point of '
          'processing.',
    ),
    LegalParagraph(
      'Automated Decision means a decision produced or significantly informed '
          'by Automated Processing.',
    ),
    LegalParagraph(
      'Human Oversight means review or involvement by a person in relation to '
          'an automated system or decision.',
    ),
    LegalParagraph(
      'Personal Data means information that identifies or can reasonably '
          'identify an individual.',
    ),
    LegalHeading(1, '3. PRINCIPLES'),
    LegalParagraph(
      'Our use of automation is guided by the following principles:',
    ),
    LegalBullets(<String>[
        'Purpose: automation is used for legitimate, defined purposes.',
        'Proportionality: automated processing is limited to what those '
            'purposes require.',
        'Fairness: we seek to avoid unfair or discriminatory outcomes.',
        'Oversight: significant decisions may involve human review where '
            'appropriate.',
        'Transparency: we explain, in general terms, how automation is used.',
    ]),
    LegalHeading(1, '4. WHERE WE USE AUTOMATION'),
    LegalParagraph(
      'Zopiq uses Automated Processing to support the following functions.',
    ),
    LegalTable(
      headers: <String>['Area', 'How Automation Is Used'],
      rows: <List<String>>[
        <String>['Recommendations', 'Suggesting restaurants, items, or content based on relevance and '
              'usage.'],
        <String>['Order assignment', 'Allocating deliveries to Delivery Partners based on operational '
              'factors.'],
        <String>['Fraud detection', 'Identifying patterns that may indicate fraud or abuse.'],
        <String>['Risk assessment', 'Assessing order or transaction risk, including for COD and payments.'],
        <String>['Analytics', 'Understanding usage to improve performance and features.'],
        <String>['Routing & logistics', 'Optimising delivery routing and estimates.'],
      ],
    ),
    LegalHeading(1, '5. RECOMMENDATIONS'),
    LegalParagraph(
      'Zopiq may use automated systems to personalise and rank content, such as '
          'restaurants and items, to make the Platform more useful. Recommendations '
          'are intended to improve relevance and do not determine legal rights. '
          'Where possible, aggregated or de-identified data is used to improve '
          'recommendation quality.',
    ),
    LegalHeading(1, '6. FRAUD DETECTION'),
    LegalParagraph(
      'Automated systems help detect potential fraud and abuse, using signals '
          'such as device and IP data, payment risk, multiple-account indicators, '
          'and order or delivery patterns, consistent with the Fraud Prevention '
          'Policy and Privacy Policy. Automated detection may trigger further '
          'checks or interim measures, but material adverse decisions may involve '
          'human review where appropriate.',
    ),
    LegalHeading(1, '7. ORDER ASSIGNMENT'),
    LegalParagraph(
      'Deliveries are assigned to Delivery Partners using automated logic that '
          'considers operational factors such as proximity, availability, and '
          'delivery efficiency. Assignment logic is designed to support timely, '
          'efficient deliveries and fair distribution of work, subject to '
          'operational constraints.',
    ),
    LegalHeading(1, '8. ANALYTICS'),
    LegalParagraph(
      'Zopiq uses automated analytics to understand how the Platform is used '
          'and to improve performance, reliability, and features. Where possible, '
          'analytics are performed using aggregated or de-identified information, '
          'consistent with the Privacy Policy.',
    ),
    LegalHeading(1, '9. HUMAN OVERSIGHT'),
    LegalParagraph(
      'Automated systems support, but do not wholly replace, human judgement '
          'for significant matters.',
    ),
    LegalHeading(2, '9.1 Review of Significant Decisions'),
    LegalParagraph(
      'Material decisions that significantly affect Users — such as certain '
          'account actions arising from suspected fraud — may involve human review '
          'where appropriate. Human Oversight is intended to provide a check on '
          'automated outcomes in higher-impact situations.',
    ),
    LegalHeading(2, '9.2 Monitoring of Systems'),
    LegalParagraph(
      'Zopiq seeks to monitor automated systems for accuracy and fairness and '
          'to address identified issues, recognising that no automated system is '
          'perfect.',
    ),
    LegalHeading(1, '10. USER RIGHTS'),
    LegalParagraph(
      'Subject to applicable law, Users may have rights in relation to '
          'Automated Processing of their Personal Data, including:',
    ),
    LegalBullets(<String>[
        'The right to be informed, in general terms, about how automation is '
            'used.',
        'The right to access certain Personal Data and request correction of '
            'inaccuracies.',
        'The right to request review of certain decisions where provided by '
            'law.',
        'The right to raise concerns or complaints about automated processing.',
    ]),
    LegalParagraph(
      'These rights may be subject to legal limitations, including where '
          'processing is necessary for fraud prevention, security, or legal '
          'compliance. Requests may be submitted using the contact details in this '
          'Policy, and Zopiq may require reasonable identity verification.',
    ),
    LegalHeading(1, '11. TRANSPARENCY'),
    LegalParagraph(
      'Zopiq aims to be transparent about the general ways in which automation '
          'is used, while protecting security, fraud-prevention effectiveness, '
          'intellectual property, and the privacy of others. Detailed logic that '
          'would undermine fraud prevention or security may not be disclosed, but '
          'Zopiq will provide meaningful general information where appropriate.',
    ),
    LegalHeading(1, '12. LIMITATIONS'),
    LegalParagraph(
      'Automated systems can make errors or produce unexpected results. Zopiq '
          'does not represent that automated outputs are always accurate or '
          'complete, and combines automation with controls and, where appropriate, '
          'human review to manage risk. Users can raise concerns so that issues can '
          'be investigated and addressed.',
    ),
    LegalHeading(1, '13. CHANGES TO THIS POLICY'),
    LegalParagraph(
      'Zopiq may update this Policy from time to time to reflect changes in '
          'law, technology, or how automation is used. Material changes will be '
          'communicated through the Platform or by other reasonable means. The '
          '"Last Updated" date on the cover page indicates the latest version.',
    ),
    LegalHeading(1, '14. CONTACT INFORMATION'),
    LegalParagraph(
      'For questions, requests, or concerns relating to this document, please '
          'contact:',
    ),
    LegalParagraph(
      'Hybrid Monks LLP',
    ),
    LegalParagraph(
      'Brand: Zopiq',
    ),
    LegalParagraph(
      'Registered Office: C/O Meena Dev, Main Road, Sadri, Rajasthan – 306702, '
          'India',
    ),
    LegalParagraph(
      'Email: hello@hybridmonks.com',
    ),
    LegalParagraph(
      'Phone: +91 96608 77411',
    ),
    LegalParagraph(
      'GSTIN: 08AATFH7649R1Z2',
    ),
  ],
);
