// GENERATED BY tool/import_legal.mjs — DO NOT EDIT.
import 'package:zopiq_legal/src/documents/accessibility_statement.dart';
import 'package:zopiq_legal/src/documents/account_deletion_data_retention_policy.dart';
import 'package:zopiq_legal/src/documents/ai_usage_and_automated_decision_policy.dart';
import 'package:zopiq_legal/src/documents/app_permissions_policy.dart';
import 'package:zopiq_legal/src/documents/community_guidelines.dart';
import 'package:zopiq_legal/src/documents/cookie_policy.dart';
import 'package:zopiq_legal/src/documents/data_breach_response_policy.dart';
import 'package:zopiq_legal/src/documents/delivery_partner_handbook.dart';
import 'package:zopiq_legal/src/documents/delivery_partner_verification_policy.dart';
import 'package:zopiq_legal/src/documents/fraud_prevention_policy.dart';
import 'package:zopiq_legal/src/documents/grievance_redressal_policy.dart';
import 'package:zopiq_legal/src/documents/intellectual_property_policy.dart';
import 'package:zopiq_legal/src/documents/merchant_sla.dart';
import 'package:zopiq_legal/src/documents/payment_and_settlement_policy.dart';
import 'package:zopiq_legal/src/documents/platform_safety_policy.dart';
import 'package:zopiq_legal/src/documents/privacy_policy.dart';
import 'package:zopiq_legal/src/documents/refund_and_cancellation_policy.dart';
import 'package:zopiq_legal/src/documents/restaurant_partner_handbook.dart';
import 'package:zopiq_legal/src/documents/restaurant_verification_policy.dart';
import 'package:zopiq_legal/src/documents/terms_and_conditions.dart';
import 'package:zopiq_legal/src/documents/website_terms_of_use.dart';
import 'package:zopiq_legal/src/legal_document.dart';

/// Every legal document, in filing order.
const List<LegalDocument> allLegalDocuments = <LegalDocument>[
  refundAndCancellationPolicy,
  communityGuidelines,
  cookiePolicy,
  appPermissionsPolicy,
  restaurantPartnerHandbook,
  deliveryPartnerHandbook,
  merchantSla,
  grievanceRedressalPolicy,
  intellectualPropertyPolicy,
  fraudPreventionPolicy,
  platformSafetyPolicy,
  paymentAndSettlementPolicy,
  restaurantVerificationPolicy,
  deliveryPartnerVerificationPolicy,
  websiteTermsOfUse,
  dataBreachResponsePolicy,
  accessibilityStatement,
  aiUsageAndAutomatedDecisionPolicy,
  accountDeletionDataRetentionPolicy,
  privacyPolicy,
  termsAndConditions,
];

/// The version string an acceptance is recorded against. Bumping a consent
/// document's version in Word changes this, and everybody is asked again.
const String legalConsentVersion = '1.0';
