// GENERATED BY tool/import_legal.mjs — DO NOT EDIT.
// Source: legal/source/04_App_Permissions_Policy.docx
//
// Edit the Word document, run `node tool/import_legal.mjs`, commit both.
import 'package:zopiq_legal/src/legal_document.dart';

const LegalDocument appPermissionsPolicy = LegalDocument(
  slug: 'app-permissions-policy',
  title: 'App Permissions Policy',
  subtitle: 'Device Permissions Across the Zopiq Applications',
  docId: 'ZOPIQ-LEGAL-04',
  version: '1.0',
  effectiveDate: '18 August 2026',
  group: 'data',
  audiences: <LegalAudience>{LegalAudience.customer, LegalAudience.restaurant, LegalAudience.rider},
  requiresConsent: false,
  blocks: <LegalBlock>[
    LegalHeading(1, 'Document Control & Version History'),
    LegalParagraph(
      'This document is maintained under version control. Any material '
          'amendment will be recorded in the table below and reflected in the '
          'version number and effective date on the cover page.',
    ),
    LegalTable(
      headers: <String>['Version', 'Date', 'Summary of Changes', 'Approved By'],
      rows: <List<String>>[
        <String>['1.0', '18 August 2026', 'Initial publication-ready version.', 'Hybrid Monks LLP'],
      ],
    ),
    LegalHeading(1, '1. INTRODUCTION'),
    LegalParagraph(
      'This App Permissions Policy ("Policy") explains the device permissions '
          'requested by the Zopiq applications — the Customer App, Restaurant '
          'Partner App, and Delivery Partner App — operated by Hybrid Monks LLP '
          '("Zopiq", "Company", "we", "our", or "us"), why each permission is '
          'requested, and how you can control it. It is intended to be read '
          'together with the Zopiq Privacy Policy.',
    ),
    LegalParagraph(
      'Zopiq requests only the permissions reasonably necessary to provide its '
          'services. Some permissions are optional; declining them may limit '
          'certain features but generally does not prevent core use of the '
          'Platform, except where a permission is essential to a specific role or '
          'function.',
    ),
    LegalHeading(1, '2. DEFINITIONS'),
    LegalParagraph(
      'Permission means an authorisation you grant to an application to access '
          'a device capability or category of data.',
    ),
    LegalParagraph(
      'Foreground means while the application is open and in active use.',
    ),
    LegalParagraph(
      'Background means while the application is not actively open on screen.',
    ),
    LegalParagraph(
      'Role means whether you use the Platform as a Customer, Restaurant '
          'Partner, or Delivery Partner.',
    ),
    LegalHeading(1, '3. GENERAL PRINCIPLES'),
    LegalParagraph(
      'Our approach to permissions is guided by the following principles:',
    ),
    LegalBullets(<String>[
        'Necessity: we request a permission only where it supports a genuine '
            'feature.',
        'Transparency: we explain why each permission is used.',
        'Control: you can grant or withdraw most permissions through your '
            'device settings.',
        'Proportionality: access is limited to what the relevant feature '
            'requires.',
    ]),
    LegalHeading(1, '4. PERMISSIONS OVERVIEW'),
    LegalParagraph(
      'The table below summarises the main permissions and their typical use. '
          'The specific permissions requested vary by application and Role.',
    ),
    LegalTable(
      headers: <String>['Permission', 'Primary Purpose', 'Typically Optional?'],
      rows: <List<String>>[
        <String>['Location', 'Nearby restaurants, delivery estimates, order tracking, navigation, '
              'assignment.', 'Optional for Customers; required for Delivery Partners while active.'],
        <String>['Camera', 'Verification photos, scanning, uploading menu or delivery images.', 'Optional; needed for specific features.'],
        <String>['Gallery / Photos', 'Uploading profile, menu, or verification images.', 'Optional; needed to upload images.'],
        <String>['Notifications', 'Order, delivery, security, and settlement updates.', 'Optional; recommended for core updates.'],
        <String>['Storage', 'Saving and caching images, documents, and app data.', 'Optional; needed for some features.'],
        <String>['Microphone', 'Voice input or in-app voice support features, where offered.', 'Optional.'],
        <String>['Phone', 'Placing or receiving order-related calls; call-related support.', 'Optional; needed to call within the app.'],
      ],
    ),
    LegalHeading(1, '5. LOCATION'),
    LegalHeading(2, '5.1 Customers'),
    LegalParagraph(
      'With your permission, location is used to display nearby restaurants, '
          'estimate delivery charges, improve address accuracy, and provide order '
          'tracking. Location access is optional for Customers, though certain '
          'features may not function correctly without it.',
    ),
    LegalHeading(2, '5.2 Delivery Partners'),
    LegalParagraph(
      'Delivery Partners are required to share real-time location while online '
          'for deliveries, travelling to pickup locations, and delivering active '
          'orders. This enables order assignment, navigation, Customer tracking, '
          'and safety features. Location tracking generally stops when the Delivery '
          'Partner goes offline, except where limited background processing is '
          'necessary to complete active deliveries or comply with applicable law.',
    ),
    LegalHeading(2, '5.3 Restaurant Partners'),
    LegalParagraph(
      'Restaurant Partners may share business location information to display '
          'restaurant locations, estimate delivery zones, and improve logistics.',
    ),
    LegalHeading(1, '6. CAMERA'),
    LegalParagraph(
      'Camera access is used for features such as capturing verification or '
          'identity photographs (where applicable), scanning where supported, and '
          'taking images of menu items or delivery confirmation. Camera access is '
          'requested only when you use a feature that requires it.',
    ),
    LegalHeading(1, '7. GALLERY AND PHOTOS'),
    LegalParagraph(
      'Gallery or photo-library access is used to upload images you choose, '
          'such as a profile photograph, menu images, restaurant images, or '
          'verification documents. Zopiq accesses only the images you select for '
          'upload.',
    ),
    LegalHeading(1, '8. NOTIFICATIONS'),
    LegalParagraph(
      'Notification permission allows the app to send push notifications for '
          'order status, delivery tracking, account security, support updates, '
          'restaurant alerts, delivery assignments, and settlement notifications. '
          'You can manage most notification preferences through your device '
          'settings or within the app, although certain essential service '
          'notifications may remain necessary for core functionality.',
    ),
    LegalHeading(1, '9. STORAGE'),
    LegalParagraph(
      'Storage access is used to save and cache images, documents, and '
          'application data on your device, which supports performance and offline '
          'access to certain information. Access is limited to what the relevant '
          'feature requires.',
    ),
    LegalHeading(1, '10. MICROPHONE'),
    LegalParagraph(
      'Microphone access is used only where you use a feature that requires '
          'audio input, such as voice input or in-app voice support, where offered. '
          'The microphone is not accessed except when such a feature is actively in '
          'use.',
    ),
    LegalHeading(1, '11. PHONE'),
    LegalParagraph(
      'Phone permission supports placing or receiving order-related calls '
          'through the app and related support interactions — for example, '
          'connecting a Customer and a Delivery Partner for a specific delivery, '
          'often through masked or in-app calling where available. Phone access is '
          'used only for these purposes.',
    ),
    LegalHeading(1, '12. USER CONTROLS AND PERMISSION WITHDRAWAL'),
    LegalParagraph(
      'You remain in control of the permissions you grant.',
    ),
    LegalHeading(2, '12.1 Managing Permissions'),
    LegalParagraph(
      'You can grant or revoke permissions at any time through your device '
          'settings, and in some cases within the app. The exact steps vary by '
          'operating system and device.',
    ),
    LegalHeading(2, '12.2 Effect of Withdrawal'),
    LegalParagraph(
      'Withdrawing an optional permission may disable the related feature but '
          'generally does not prevent core use of the Platform. However, where a '
          'permission is essential to a Role — for example, location for an active '
          'Delivery Partner — withdrawing it may prevent you from performing that '
          'Role until it is restored.',
    ),
    LegalHeading(2, '12.3 Data Handling'),
    LegalParagraph(
      'Information accessed through permissions is handled in accordance with '
          'the Zopiq Privacy Policy, including the principles of data minimization '
          'and purpose limitation.',
    ),
    LegalHeading(1, '13. CHANGES TO THIS POLICY'),
    LegalParagraph(
      'Zopiq may update this Policy from time to time to reflect changes in app '
          'features, operating-system requirements, or applicable law. Material '
          'changes will be communicated through the Platform or by other reasonable '
          'means. The "Last Updated" date on the cover page indicates the latest '
          'version.',
    ),
    LegalHeading(1, '14. CONTACT INFORMATION'),
    LegalParagraph(
      'For questions, requests, or concerns relating to this document, please '
          'contact:',
    ),
    LegalParagraph(
      'Hybrid Monks LLP',
    ),
    LegalParagraph(
      'Brand: Zopiq',
    ),
    LegalParagraph(
      'Registered Office: C/O Meena Dev, Main Road, Sadri, Rajasthan – 306702, '
          'India',
    ),
    LegalParagraph(
      'Email: hello@hybridmonks.com',
    ),
    LegalParagraph(
      'Phone: +91 96608 77411',
    ),
    LegalParagraph(
      'GSTIN: 08AATFH7649R1Z2',
    ),
  ],
);
