// GENERATED BY tool/import_legal.mjs — DO NOT EDIT.
// Source: legal/source/02_Community_Guidelines.docx
//
// Edit the Word document, run `node tool/import_legal.mjs`, commit both.
import 'package:zopiq_legal/src/legal_document.dart';

const LegalDocument communityGuidelines = LegalDocument(
  slug: 'community-guidelines',
  title: 'Community Guidelines',
  subtitle: 'Standards of Conduct for the Zopiq Community',
  docId: 'ZOPIQ-LEGAL-02',
  version: '1.0',
  effectiveDate: '18 August 2026',
  group: 'conduct',
  audiences: <LegalAudience>{LegalAudience.customer, LegalAudience.restaurant, LegalAudience.rider},
  requiresConsent: false,
  blocks: <LegalBlock>[
    LegalHeading(1, 'Document Control & Version History'),
    LegalParagraph(
      'This document is maintained under version control. Any material '
          'amendment will be recorded in the table below and reflected in the '
          'version number and effective date on the cover page.',
    ),
    LegalTable(
      headers: <String>['Version', 'Date', 'Summary of Changes', 'Approved By'],
      rows: <List<String>>[
        <String>['1.0', '18 August 2026', 'Initial publication-ready version.', 'Hybrid Monks LLP'],
      ],
    ),
    LegalHeading(1, '1. INTRODUCTION'),
    LegalParagraph(
      'These Community Guidelines ("Guidelines") set out the standards of '
          'conduct expected of everyone who uses the Zopiq platform, operated by '
          'Hybrid Monks LLP ("Zopiq", "Company", "we", "our", or "us"). They apply '
          'to Customers, Restaurant Partners, and Delivery Partners across the '
          'Customer App, Restaurant Partner App, and Delivery Partner App.',
    ),
    LegalParagraph(
      'These Guidelines supplement, and are read together with, the Zopiq Terms '
          '& Conditions, Privacy Policy, and the relevant Partner Agreements. Where '
          'conduct also breaches those documents or applicable law, Zopiq may act '
          'under any or all of them.',
    ),
    LegalParagraph(
      'Our aim is a marketplace that is safe, respectful, honest, and reliable '
          'for all participants.',
    ),
    LegalHeading(1, '2. DEFINITIONS'),
    LegalParagraph(
      'User means any Customer, Restaurant Partner, or Delivery Partner using '
          'the Platform.',
    ),
    LegalParagraph(
      'Content means reviews, ratings, images, messages, or other material '
          'submitted to the Platform.',
    ),
    LegalParagraph(
      'Prohibited Conduct means any behaviour described in these Guidelines as '
          'not permitted.',
    ),
    LegalParagraph(
      'Enforcement Action means any measure taken by Zopiq in response to a '
          'breach, including warnings, restrictions, suspension, or termination.',
    ),
    LegalHeading(1, '3. CORE PRINCIPLES'),
    LegalParagraph(
      'All Users are expected to uphold the following principles:',
    ),
    LegalBullets(<String>[
        'Respect: treat others with courtesy, regardless of role, background, '
            'or circumstances.',
        'Honesty: provide accurate information and act in good faith.',
        'Safety: avoid conduct that endangers any person or the integrity of '
            'the Platform.',
        'Fairness: do not exploit, manipulate, or abuse Platform features, '
            'offers, or other Users.',
        'Compliance: follow these Guidelines, the Terms & Conditions, and '
            'applicable law.',
    ]),
    LegalHeading(1, '4. CUSTOMER CONDUCT'),
    LegalParagraph(
      'Customers agree to:',
    ),
    LegalBullets(<String>[
        'Provide accurate delivery information and remain reachable during '
            'delivery.',
        'Pay all applicable charges, including any COD balance due.',
        'Treat Restaurant Partners and Delivery Partners respectfully.',
        'Cooperate during dispute investigations.',
    ]),
    LegalParagraph(
      'Customers shall not:',
    ),
    LegalBullets(<String>[
        'Place fake orders or orders without the intention to complete the '
            'purchase.',
        'Abuse customer support or use abusive, threatening, discriminatory, or '
            'offensive language.',
        'Attempt payment fraud or submit false refund claims.',
        'Manipulate the rating system or abuse promotional offers.',
        'Create multiple accounts to evade restrictions.',
    ]),
    LegalHeading(1, '5. RESTAURANT PARTNER CONDUCT'),
    LegalParagraph(
      'Restaurant Partners agree to:',
    ),
    LegalBullets(<String>[
        'Display accurate menus, prices, and availability.',
        'Prepare food using hygienic practices and comply with food safety '
            'laws.',
        'Package food securely and honour accepted orders except where '
            'cancellation is permitted.',
        'Treat Customers and Delivery Partners professionally.',
    ]),
    LegalParagraph(
      'Restaurant Partners shall not:',
    ),
    LegalBullets(<String>[
        'List misleading menu items, prices, or images.',
        'Intentionally cancel accepted orders to manipulate availability, '
            'pricing, or ratings.',
        'List or sell prohibited items through the Platform.',
        'Engage in fraudulent settlement or order activity.',
    ]),
    LegalHeading(1, '6. DELIVERY PARTNER CONDUCT'),
    LegalParagraph(
      'Delivery Partners agree to:',
    ),
    LegalBullets(<String>[
        'Accept only assignments they intend to complete and reach pickup '
            'locations promptly.',
        'Deliver orders safely, professionally, and without unreasonable delay.',
        'Protect Customer privacy and the confidentiality of order information.',
        'Comply with applicable traffic and transport laws.',
    ]),
    LegalParagraph(
      'Delivery Partners shall not:',
    ),
    LegalBullets(<String>[
        'Tamper with, open, or consume Customer orders.',
        'Provide services while under the influence of alcohol or drugs.',
        'Request payments beyond Platform-authorised charges.',
        'Harass or threaten Customers or Restaurant staff.',
    ]),
    LegalHeading(1, '7. HARASSMENT AND ABUSE'),
    LegalParagraph(
      'Zopiq has zero tolerance for harassment. Prohibited conduct includes '
          'threats, intimidation, stalking, sexual harassment, hate speech, and '
          'persistent unwanted contact directed at any User or staff member. This '
          'applies across calls, chats, in-person interactions, and Content.',
    ),
    LegalHeading(2, '7.1 Reporting Harassment'),
    LegalParagraph(
      'Any User who experiences or witnesses harassment may report it through '
          'in-app support or the contact details in these Guidelines. Reports are '
          'treated seriously and, where appropriate, investigated promptly.',
    ),
    LegalHeading(1, '8. DISCRIMINATION'),
    LegalParagraph(
      'Discrimination or harassment on the basis of religion, caste, sex, '
          'gender, sexual orientation, disability, place of birth, or any other '
          'status protected by applicable law is strictly prohibited. Refusing '
          'service, providing degraded service, or directing abusive Content at a '
          'person on any such basis is a serious violation and may result in '
          'immediate Enforcement Action.',
    ),
    LegalHeading(1, '9. SPAM AND MISUSE OF COMMUNICATIONS'),
    LegalParagraph(
      'Users shall not send spam, unsolicited advertising, chain messages, or '
          'repetitive irrelevant communications through Platform channels. '
          'Communications features are provided to support orders, deliveries, and '
          'support, and must not be misused for marketing, solicitation, or '
          'harassment.',
    ),
    LegalHeading(1, '10. FRAUD AND DISHONEST CONDUCT'),
    LegalParagraph(
      'The following are prohibited: fake orders, coupon or referral abuse, '
          'chargeback fraud, payment fraud, identity fraud, submission of forged '
          'documents, delivery theft, food tampering, and manipulation of '
          'settlements or earnings. Suspected fraud is handled under the Fraud '
          'Prevention Policy and may lead to permanent termination and referral to '
          'law enforcement.',
    ),
    LegalHeading(1, '11. FAKE REVIEWS AND RATING MANIPULATION'),
    LegalParagraph(
      'Reviews and ratings must reflect genuine experiences. The following are '
          'prohibited:',
    ),
    LegalBullets(<String>[
        'Posting fake, incentivised, or paid reviews.',
        'Submitting reviews for orders that did not occur.',
        'Coordinated efforts to inflate or deflate ratings.',
        'Abusive, defamatory, discriminatory, or false content in reviews.',
    ]),
    LegalParagraph(
      'Zopiq may remove Content that violates these Guidelines and may take '
          'Enforcement Action against Users who manipulate the rating system.',
    ),
    LegalHeading(1, '12. PLATFORM ABUSE'),
    LegalParagraph(
      'Users shall not misuse the Platform, including by using bots or '
          'automated systems, attempting to hack or interfere with the Platform, '
          'uploading malware, scraping data, exploiting pricing errors, reselling '
          'Platform services without permission, or circumventing security or '
          'verification measures.',
    ),
    LegalHeading(1, '13. PROHIBITED AND ILLEGAL ITEMS'),
    LegalParagraph(
      'Ordering, listing, selling, or distributing prohibited items through the '
          'Platform is not permitted. Prohibited items include alcoholic beverages '
          '(where not permitted by the Platform or law), tobacco and nicotine '
          'products, illegal drugs or controlled substances, weapons, explosives, '
          'hazardous chemicals, counterfeit goods, and stolen property.',
    ),
    LegalHeading(1, '14. ENFORCEMENT AND ACCOUNT SUSPENSION'),
    LegalParagraph(
      'Where a User breaches these Guidelines, Zopiq may take proportionate '
          'Enforcement Action, considering the severity, frequency, and impact of '
          'the conduct.',
    ),
    LegalTable(
      headers: <String>['Enforcement Action', 'When Typically Applied'],
      rows: <List<String>>[
        <String>['Warning notice', 'First or minor breach where guidance is likely to correct behaviour.'],
        <String>['Feature restriction', 'Repeated minor breaches, or misuse of a specific feature (e.g. COD, '
              'reviews).'],
        <String>['Temporary suspension', 'Serious breach or repeated violations pending review.'],
        <String>['Permanent termination', 'Severe misconduct such as fraud, violence, food tampering, or '
              'repeated serious breaches.'],
      ],
    ),
    LegalParagraph(
      'For serious risks to safety or legal compliance, Zopiq may suspend or '
          'terminate an account immediately and without prior notice.',
    ),
    LegalHeading(1, '15. APPEAL PROCESS'),
    LegalParagraph(
      'A User who believes Enforcement Action was taken in error may appeal.',
    ),
    LegalHeading(2, '15.1 How to Appeal'),
    LegalParagraph(
      'Appeals may be submitted through in-app support or the contact details '
          'in these Guidelines, stating the account details, the action being '
          'appealed, and the reasons for the appeal, together with any supporting '
          'information.',
    ),
    LegalHeading(2, '15.2 Review'),
    LegalParagraph(
      'Zopiq will review appeals fairly and within a reasonable timeframe. The '
          'reviewer will consider the original decision, the User\'s submissions, '
          'and any relevant evidence. The outcome and, where appropriate, the '
          'reasons will be communicated to the User.',
    ),
    LegalHeading(2, '15.3 Outcome'),
    LegalParagraph(
      'Following review, Zopiq may uphold, modify, or reverse the original '
          'action. Decisions on serious violations such as fraud, violence, or food '
          'tampering may be final where necessary to protect users or comply with '
          'law.',
    ),
    LegalHeading(1, '16. CHANGES TO THESE GUIDELINES'),
    LegalParagraph(
      'Zopiq may update these Guidelines from time to time to reflect changes '
          'in law, Platform features, or community needs. Material changes will be '
          'communicated through the Platform or by other reasonable means. '
          'Continued use of the Platform after the effective date constitutes '
          'acceptance of the updated Guidelines.',
    ),
    LegalHeading(1, '17. CONTACT INFORMATION'),
    LegalParagraph(
      'For questions, requests, or concerns relating to this document, please '
          'contact:',
    ),
    LegalParagraph(
      'Hybrid Monks LLP',
    ),
    LegalParagraph(
      'Brand: Zopiq',
    ),
    LegalParagraph(
      'Registered Office: C/O Meena Dev, Main Road, Sadri, Rajasthan – 306702, '
          'India',
    ),
    LegalParagraph(
      'Email: hello@hybridmonks.com',
    ),
    LegalParagraph(
      'Phone: +91 96608 77411',
    ),
    LegalParagraph(
      'GSTIN: 08AATFH7649R1Z2',
    ),
  ],
);
