// GENERATED BY tool/import_legal.mjs — DO NOT EDIT.
// Source: legal/source/03_Cookie_Policy.docx
//
// Edit the Word document, run `node tool/import_legal.mjs`, commit both.
import 'package:zopiq_legal/src/legal_document.dart';

const LegalDocument cookiePolicy = LegalDocument(
  slug: 'cookie-policy',
  title: 'Cookie Policy',
  subtitle: 'Use of Cookies and Similar Technologies',
  docId: 'ZOPIQ-LEGAL-03',
  version: '1.0',
  effectiveDate: '18 August 2026',
  group: 'data',
  audiences: <LegalAudience>{LegalAudience.customer},
  requiresConsent: false,
  blocks: <LegalBlock>[
    LegalHeading(1, 'Document Control & Version History'),
    LegalParagraph(
      'This document is maintained under version control. Any material '
          'amendment will be recorded in the table below and reflected in the '
          'version number and effective date on the cover page.',
    ),
    LegalTable(
      headers: <String>['Version', 'Date', 'Summary of Changes', 'Approved By'],
      rows: <List<String>>[
        <String>['1.0', '18 August 2026', 'Initial publication-ready version.', 'Hybrid Monks LLP'],
      ],
    ),
    LegalHeading(1, '1. INTRODUCTION'),
    LegalParagraph(
      'This Cookie Policy ("Policy") explains how the Zopiq website and '
          'supported web services, operated by Hybrid Monks LLP ("Zopiq", '
          '"Company", "we", "our", or "us"), use cookies and similar technologies. '
          'It is intended to be read together with the Zopiq Privacy Policy, which '
          'describes how personal data is handled more generally.',
    ),
    LegalParagraph(
      'By using the Zopiq website, you agree to the use of cookies as described '
          'in this Policy, except for cookies that require your consent, which are '
          'used only where such consent has been provided in accordance with '
          'applicable law.',
    ),
    LegalHeading(1, '2. WHAT ARE COOKIES'),
    LegalParagraph(
      'Cookies are small text files placed on your device when you visit a '
          'website. They allow the website to recognise your device, remember your '
          'preferences, support security, and understand how the website is used. '
          'Similar technologies, such as pixels, tags, and local storage, perform '
          'comparable functions and are treated as cookies for the purpose of this '
          'Policy.',
    ),
    LegalHeading(2, '2.1 First-Party and Third-Party Cookies'),
    LegalParagraph(
      'First-party cookies are set by Zopiq. Third-party cookies are set by '
          'service providers acting on our behalf, such as analytics or security '
          'providers. This Policy covers both, though third-party providers also '
          'operate under their own privacy and cookie policies.',
    ),
    LegalHeading(2, '2.2 Session and Persistent Cookies'),
    LegalParagraph(
      'Session cookies exist only for the duration of your browsing session and '
          'are deleted when you close your browser. Persistent cookies remain on '
          'your device for a defined period or until you delete them.',
    ),
    LegalHeading(1, '3. CATEGORIES OF COOKIES WE USE'),
    LegalParagraph(
      'Zopiq uses the following categories of cookies.',
    ),
    LegalHeading(2, '3.1 Essential Cookies'),
    LegalParagraph(
      'These cookies are necessary for the website to function correctly and '
          'cannot be switched off in our systems. They are used for user '
          'authentication, security, session management, and fraud prevention. '
          'Without these cookies, core parts of the website will not work.',
    ),
    LegalHeading(2, '3.2 Preference Cookies'),
    LegalParagraph(
      'These cookies allow the website to remember choices you make to provide '
          'a more personalised experience. They are used to remember language '
          'preferences, saved settings, recently viewed restaurants, and user '
          'interface preferences.',
    ),
    LegalHeading(2, '3.3 Performance Cookies'),
    LegalParagraph(
      'These cookies help us understand how the website performs so we can '
          'improve it. They are used to understand website performance, loading '
          'times, feature usage, and error reporting. Where possible, information '
          'collected is aggregated.',
    ),
    LegalHeading(2, '3.4 Analytics Cookies'),
    LegalParagraph(
      'These cookies help us understand how visitors interact with the website. '
          'They are used to understand visitor trends, popular features, device '
          'types, and general usage patterns. Where possible, analytics data is '
          'aggregated or de-identified.',
    ),
    LegalHeading(1, '4. SUMMARY OF COOKIE CATEGORIES'),
    LegalTable(
      headers: <String>['Category', 'Purpose', 'Consent Required'],
      rows: <List<String>>[
        <String>['Essential', 'Authentication, security, session management, fraud prevention.', 'No — strictly necessary.'],
        <String>['Preference', 'Remember language, settings, recent restaurants, UI preferences.', 'Where required by law.'],
        <String>['Performance', 'Website performance, loading times, feature usage, error reporting.', 'Where required by law.'],
        <String>['Analytics', 'Visitor trends, popular features, device types, usage patterns.', 'Where required by law.'],
      ],
    ),
    LegalHeading(1, '5. THIRD-PARTY COOKIES'),
    LegalParagraph(
      'Some cookies are placed by third-party service providers that assist us '
          'in operating the website, such as analytics providers, security and '
          'fraud-prevention providers, and content delivery or hosting providers. '
          'These providers process information in accordance with our instructions '
          'and their own privacy and cookie policies. Zopiq is not responsible for '
          'the independent practices of third parties, and you should review their '
          'policies where relevant.',
    ),
    LegalHeading(1, '6. COOKIE RETENTION'),
    LegalParagraph(
      'The period for which a cookie remains on your device depends on its type '
          'and purpose.',
    ),
    LegalTable(
      headers: <String>['Cookie Type', 'Typical Retention'],
      rows: <List<String>>[
        <String>['Session cookies', 'Deleted automatically when you close your browser.'],
        <String>['Essential persistent cookies', 'Retained only as long as necessary for authentication, security, and '
              'session continuity.'],
        <String>['Preference cookies', 'Retained until you change or clear the relevant preference, or for a '
              'defined period.'],
        <String>['Performance & analytics cookies', 'Retained for a limited period appropriate to performance monitoring '
              'and analysis, then expired or refreshed.'],
      ],
    ),
    LegalParagraph(
      'Actual retention periods may vary by cookie and provider. Where '
          'information derived from cookies is no longer needed, it is deleted or '
          'anonymized, unless retention is required or permitted by law.',
    ),
    LegalHeading(1, '7. MANAGING COOKIES'),
    LegalParagraph(
      'You can control and manage cookies in several ways. Please note that '
          'disabling certain cookies may affect the functionality of the website.',
    ),
    LegalHeading(2, '7.1 Browser Settings'),
    LegalParagraph(
      'Most browsers allow you to view, manage, delete, and block cookies '
          'through their settings. You can usually set your browser to notify you '
          'when a cookie is set, or to refuse cookies altogether. The exact steps '
          'vary by browser and device.',
    ),
    LegalHeading(2, '7.2 Effect of Disabling Cookies'),
    LegalParagraph(
      'If you disable essential cookies, core features such as sign-in, '
          'security, and session management may not work correctly. Disabling '
          'preference, performance, or analytics cookies is generally possible '
          'without preventing core functionality, though your experience may be '
          'less personalised.',
    ),
    LegalHeading(2, '7.3 Consent Choices'),
    LegalParagraph(
      'Where consent is required by applicable law for non-essential cookies, '
          'you may accept or decline such cookies, and may withdraw consent at any '
          'time through the available cookie controls or your browser settings.',
    ),
    LegalHeading(1, '8. CHANGES TO THIS POLICY'),
    LegalParagraph(
      'Zopiq may update this Policy from time to time to reflect changes in '
          'law, technology, or our use of cookies. Material changes will be '
          'communicated through the website or by other reasonable means. The "Last '
          'Updated" date on the cover page indicates the latest version.',
    ),
    LegalHeading(1, '9. CONTACT INFORMATION'),
    LegalParagraph(
      'For questions, requests, or concerns relating to this document, please '
          'contact:',
    ),
    LegalParagraph(
      'Hybrid Monks LLP',
    ),
    LegalParagraph(
      'Brand: Zopiq',
    ),
    LegalParagraph(
      'Registered Office: C/O Meena Dev, Main Road, Sadri, Rajasthan – 306702, '
          'India',
    ),
    LegalParagraph(
      'Email: hello@hybridmonks.com',
    ),
    LegalParagraph(
      'Phone: +91 96608 77411',
    ),
    LegalParagraph(
      'GSTIN: 08AATFH7649R1Z2',
    ),
  ],
);
