// GENERATED BY tool/import_legal.mjs — DO NOT EDIT.
// Source: legal/source/16_Data_Breach_Response_Policy.docx
//
// Edit the Word document, run `node tool/import_legal.mjs`, commit both.
import 'package:zopiq_legal/src/legal_document.dart';

const LegalDocument dataBreachResponsePolicy = LegalDocument(
  slug: 'data-breach-response-policy',
  title: 'Data Breach Response Policy',
  subtitle: 'Detection, Response, Notification, and Recovery',
  docId: 'ZOPIQ-LEGAL-16',
  version: '1.0',
  effectiveDate: '18 August 2026',
  group: 'data',
  audiences: <LegalAudience>{LegalAudience.customer, LegalAudience.restaurant, LegalAudience.rider},
  requiresConsent: false,
  blocks: <LegalBlock>[
    LegalHeading(1, 'Document Control & Version History'),
    LegalParagraph(
      'This document is maintained under version control. Any material '
          'amendment will be recorded in the table below and reflected in the '
          'version number and effective date on the cover page.',
    ),
    LegalTable(
      headers: <String>['Version', 'Date', 'Summary of Changes', 'Approved By'],
      rows: <List<String>>[
        <String>['1.0', '18 August 2026', 'Initial publication-ready version.', 'Hybrid Monks LLP'],
      ],
    ),
    LegalHeading(1, '1. INTRODUCTION'),
    LegalParagraph(
      'This Data Breach Response Policy ("Policy") describes how Zopiq, '
          'operated by Hybrid Monks LLP ("Zopiq", "Company", "we", "our", or "us"), '
          'prepares for, detects, responds to, and recovers from personal data '
          'breaches and security incidents. It supports Zopiq\'s obligations under '
          'the Digital Personal Data Protection Act, 2023, the Information '
          'Technology Act, 2000, and other applicable law, and supplements the '
          'Privacy Policy.',
    ),
    LegalParagraph(
      'This Policy is primarily an internal operational document. It is '
          'summarised for transparency and to explain how Zopiq protects personal '
          'data.',
    ),
    LegalHeading(1, '2. DEFINITIONS'),
    LegalParagraph(
      'Personal Data means information that identifies or can reasonably '
          'identify an individual.',
    ),
    LegalParagraph(
      'Security Incident means an event that may compromise the '
          'confidentiality, integrity, or availability of Personal Data or systems.',
    ),
    LegalParagraph(
      'Data Breach means a Security Incident leading to unauthorised access to, '
          'disclosure of, alteration of, or loss of Personal Data.',
    ),
    LegalParagraph(
      'Incident Response Team means the individuals responsible for managing a '
          'Security Incident.',
    ),
    LegalHeading(1, '3. OBJECTIVES'),
    LegalParagraph(
      'The objectives of this Policy are to:',
    ),
    LegalBullets(<String>[
        'Detect and respond to Security Incidents promptly.',
        'Contain and mitigate harm to individuals and the Platform.',
        'Meet legal reporting and notification obligations.',
        'Recover affected systems and restore normal operations.',
        'Learn from incidents to strengthen security.',
    ]),
    LegalHeading(1, '4. INCIDENT RESPONSE FRAMEWORK'),
    LegalParagraph(
      'Zopiq follows a structured incident-response lifecycle: preparation, '
          'detection, containment, investigation, notification, recovery, and '
          'post-incident review. The stages may overlap depending on the incident.',
    ),
    LegalTable(
      headers: <String>['Stage', 'Objective'],
      rows: <List<String>>[
        <String>['Preparation', 'Maintain controls, roles, and readiness before incidents occur.'],
        <String>['Detection', 'Identify potential Security Incidents quickly.'],
        <String>['Containment', 'Limit the scope and impact of the incident.'],
        <String>['Investigation', 'Determine cause, scope, and affected data.'],
        <String>['Notification', 'Inform authorities and affected individuals where required.'],
        <String>['Recovery', 'Restore systems and services securely.'],
        <String>['Review', 'Document lessons and improve controls.'],
      ],
    ),
    LegalHeading(1, '5. INTERNAL REPORTING'),
    LegalParagraph(
      'Any employee, contractor, or service provider who becomes aware of a '
          'suspected Security Incident must report it promptly through the '
          'designated internal channel to the Incident Response Team. Early '
          'reporting is essential to limit harm. Suspected incidents should be '
          'reported even if not yet confirmed.',
    ),
    LegalHeading(1, '6. DETECTION'),
    LegalParagraph(
      'Zopiq uses administrative and technical measures to detect Security '
          'Incidents, which may include network monitoring, intrusion detection, '
          'audit logging, alerting, and review of unusual activity. Reports from '
          'Users or third parties are also treated as potential detection sources '
          'and assessed.',
    ),
    LegalHeading(1, '7. CONTAINMENT'),
    LegalParagraph(
      'On identifying a Security Incident, the Incident Response Team takes '
          'reasonable steps to contain it, which may include isolating affected '
          'systems, revoking or resetting credentials, blocking malicious activity, '
          'and preserving evidence. Containment aims to stop ongoing harm while '
          'maintaining information needed for investigation.',
    ),
    LegalHeading(1, '8. INVESTIGATION'),
    LegalParagraph(
      'Zopiq investigates the incident to determine its cause, scope, the '
          'categories of Personal Data involved, the number of individuals '
          'potentially affected, and the associated risk. The investigation informs '
          'notification decisions and recovery. Relevant evidence and actions are '
          'documented.',
    ),
    LegalHeading(1, '9. NOTIFICATION'),
    LegalParagraph(
      'Where a Data Breach triggers legal obligations, Zopiq will notify the '
          'relevant authorities and affected individuals as required by applicable '
          'law, within applicable timeframes.',
    ),
    LegalHeading(2, '9.1 Content of Notifications'),
    LegalParagraph(
      'Notifications will, to the extent known and permitted, describe the '
          'nature of the incident, the categories of data involved, the likely '
          'consequences, the measures taken or proposed, and any steps individuals '
          'can take to protect themselves.',
    ),
    LegalHeading(2, '9.2 Communication Channels'),
    LegalParagraph(
      'Affected individuals may be notified through in-app notifications, '
          'email, or other reasonable means. Zopiq will avoid disclosing '
          'information in a way that could increase risk to affected individuals or '
          'the investigation.',
    ),
    LegalHeading(1, '10. RECOVERY'),
    LegalParagraph(
      'Zopiq takes reasonable steps to restore affected systems and services '
          'securely, verify that vulnerabilities are addressed, and confirm the '
          'integrity of restored data where possible. Recovery includes monitoring '
          'for recurrence and confirming that containment measures remain '
          'effective.',
    ),
    LegalHeading(1, '11. DOCUMENTATION AND RECORD-KEEPING'),
    LegalParagraph(
      'Zopiq maintains records of Security Incidents and Data Breaches, '
          'including detection, actions taken, investigation findings, '
          'notifications, and recovery. These records support legal compliance, '
          'accountability, and improvement, and are retained in accordance with the '
          'Privacy Policy and Account Deletion & Data Retention Policy.',
    ),
    LegalHeading(1, '12. POST-INCIDENT REVIEW'),
    LegalParagraph(
      'After an incident, Zopiq conducts a review to identify root causes and '
          'improvement opportunities, and updates controls, training, or processes '
          'as appropriate. The goal is to reduce the likelihood and impact of '
          'future incidents.',
    ),
    LegalHeading(1, '13. ROLES AND RESPONSIBILITIES'),
    LegalParagraph(
      'The Incident Response Team coordinates the response, supported by '
          'relevant technical, legal, and management personnel. All personnel are '
          'responsible for reporting suspected incidents and following this Policy. '
          'Service providers processing Personal Data on Zopiq\'s behalf are '
          'expected to report incidents promptly and cooperate with response '
          'efforts.',
    ),
    LegalHeading(1, '14. CHANGES TO THIS POLICY'),
    LegalParagraph(
      'Zopiq may update this Policy from time to time to reflect changes in '
          'law, technology, or operations. The "Last Updated" date on the cover '
          'page indicates the latest version.',
    ),
    LegalHeading(1, '15. CONTACT INFORMATION'),
    LegalParagraph(
      'For questions, requests, or concerns relating to this document, please '
          'contact:',
    ),
    LegalParagraph(
      'Hybrid Monks LLP',
    ),
    LegalParagraph(
      'Brand: Zopiq',
    ),
    LegalParagraph(
      'Registered Office: C/O Meena Dev, Main Road, Sadri, Rajasthan – 306702, '
          'India',
    ),
    LegalParagraph(
      'Email: hello@hybridmonks.com',
    ),
    LegalParagraph(
      'Phone: +91 96608 77411',
    ),
    LegalParagraph(
      'GSTIN: 08AATFH7649R1Z2',
    ),
  ],
);
