// GENERATED BY tool/import_legal.mjs — DO NOT EDIT.
// Source: legal/source/14_Delivery_Partner_Verification_Policy.docx
//
// Edit the Word document, run `node tool/import_legal.mjs`, commit both.
import 'package:zopiq_legal/src/legal_document.dart';

const LegalDocument deliveryPartnerVerificationPolicy = LegalDocument(
  slug: 'delivery-partner-verification-policy',
  title: 'Delivery Partner Verification Policy',
  subtitle: 'Identity, Licence, Vehicle, and Ongoing Checks',
  docId: 'ZOPIQ-LEGAL-14',
  version: '1.0',
  effectiveDate: '18 August 2026',
  group: 'partner',
  audiences: <LegalAudience>{LegalAudience.rider},
  requiresConsent: false,
  blocks: <LegalBlock>[
    LegalHeading(1, 'Document Control & Version History'),
    LegalParagraph(
      'This document is maintained under version control. Any material '
          'amendment will be recorded in the table below and reflected in the '
          'version number and effective date on the cover page.',
    ),
    LegalTable(
      headers: <String>['Version', 'Date', 'Summary of Changes', 'Approved By'],
      rows: <List<String>>[
        <String>['1.0', '18 August 2026', 'Initial publication-ready version.', 'Hybrid Monks LLP'],
      ],
    ),
    LegalHeading(1, '1. INTRODUCTION'),
    LegalParagraph(
      'This Delivery Partner Verification Policy ("Policy") describes how '
          'Zopiq, operated by Hybrid Monks LLP ("Zopiq", "Company", "we", "our", or '
          '"us"), verifies Delivery Partners before and during their participation '
          'on the Platform. It supplements the Delivery Partner Agreement, Terms & '
          'Conditions, and Privacy Policy.',
    ),
    LegalParagraph(
      'Verification protects Customers, Restaurant Partners, and Delivery '
          'Partners themselves, and helps ensure that Delivery Partners are '
          'eligible and legally permitted to provide delivery services.',
    ),
    LegalHeading(1, '2. DEFINITIONS'),
    LegalParagraph(
      'Verification means the process of checking a Delivery Partner\'s '
          'identity, documents, and eligibility.',
    ),
    LegalParagraph(
      'Deactivation means suspension or termination of a Delivery Partner\'s '
          'access to the Platform.',
    ),
    LegalParagraph(
      'Compliance Monitoring means ongoing checks to confirm continued '
          'eligibility.',
    ),
    LegalHeading(1, '3. PRINCIPLES'),
    LegalParagraph(
      'Verification is guided by the following principles:',
    ),
    LegalBullets(<String>[
        'Only eligible, verified individuals may perform deliveries.',
        'Documents are collected and handled under the Privacy Policy and data '
            'minimization.',
        'Verification is ongoing, not only at onboarding.',
        'Invalid documents or failed checks may lead to Deactivation.',
    ]),
    LegalHeading(1, '4. ELIGIBILITY'),
    LegalParagraph(
      'To be verified, a Delivery Partner must be at least 18 years of age, '
          'hold a valid government-issued identity proof, possess a valid driving '
          'licence where applicable to the vehicle used, and operate a legally '
          'compliant vehicle where required. The Delivery Partner must be legally '
          'permitted to provide delivery services.',
    ),
    LegalHeading(1, '5. IDENTITY VERIFICATION'),
    LegalParagraph(
      'Delivery Partners provide a government-issued identity document and, '
          'where applicable, a verification photograph or selfie. Zopiq may verify '
          'identity to confirm that the person performing deliveries is the '
          'registered, verified individual. Providing false identity information or '
          'another person\'s documents is treated as identity fraud.',
    ),
    LegalHeading(1, '6. DRIVING LICENCE VERIFICATION'),
    LegalParagraph(
      'Where the Delivery Partner uses a vehicle requiring a licence, a valid '
          'driving licence must be provided and kept current. Zopiq may verify '
          'licence details and may restrict or deactivate Delivery Partners whose '
          'licence is invalid or expired until a valid licence is provided.',
    ),
    LegalHeading(1, '7. VEHICLE VERIFICATION'),
    LegalParagraph(
      'Where applicable, Delivery Partners provide vehicle details such as '
          'vehicle type and registration, and insurance details where required. '
          'Zopiq may verify these details and expects the vehicle to remain '
          'roadworthy and legally compliant. Delivery Partners are responsible for '
          'their vehicle, its documents, and compliance with the Motor Vehicles Act '
          'and other applicable laws.',
    ),
    LegalHeading(2, '7.1 Documents Summary'),
    LegalTable(
      headers: <String>['Document / Detail', 'Purpose'],
      rows: <List<String>>[
        <String>['Government-issued identity document', 'Confirm identity and age eligibility.'],
        <String>['Verification photograph (where applicable)', 'Confirm the person performing deliveries.'],
        <String>['Driving licence (where applicable)', 'Confirm legal authorisation to operate the vehicle.'],
        <String>['Vehicle registration (where applicable)', 'Confirm a legally compliant vehicle.'],
        <String>['Insurance details (where required)', 'Confirm required coverage.'],
        <String>['Bank / UPI details', 'Processing of daily Payouts.'],
      ],
    ),
    LegalHeading(1, '8. BACKGROUND CHECKS'),
    LegalParagraph(
      'Where permitted by applicable law, Zopiq may carry out background or '
          'verification checks appropriate to the delivery role, using authorised '
          'verification providers. Such checks are conducted consistently with the '
          'Privacy Policy and applicable law, and are limited to what is reasonably '
          'necessary for safety and eligibility. Delivery Partners may be required '
          'to consent to checks as a condition of participation.',
    ),
    LegalHeading(1, '9. DOCUMENT RENEWAL'),
    LegalParagraph(
      'Documents must remain valid throughout participation. Delivery Partners '
          'are responsible for renewing their driving licence, vehicle '
          'registration, insurance, and other applicable documents before they '
          'expire, and for updating Zopiq with current details. Zopiq may request '
          'updated documents periodically and may restrict or deactivate Delivery '
          'Partners whose required documents have lapsed until valid documents are '
          'provided.',
    ),
    LegalHeading(1, '10. COMPLIANCE MONITORING'),
    LegalParagraph(
      'Zopiq conducts ongoing Compliance Monitoring, which may include periodic '
          're-verification, review of safety reports or complaints, and checks '
          'triggered by risk indicators. Delivery Partners are expected to '
          'cooperate and provide reasonably requested information.',
    ),
    LegalHeading(1, '11. DEACTIVATION'),
    LegalParagraph(
      'Zopiq may deactivate a Delivery Partner where Verification fails, '
          'documents lapse or are invalid, false information or forged documents '
          'are provided, or serious safety or conduct concerns arise.',
    ),
    LegalHeading(2, '11.1 Temporary Deactivation'),
    LegalParagraph(
      'Temporary Deactivation may apply while documents are renewed, '
          'information is verified, or a concern is investigated. Access may be '
          'restored once the matter is resolved.',
    ),
    LegalHeading(2, '11.2 Permanent Deactivation'),
    LegalParagraph(
      'Permanent Deactivation may apply for serious matters such as identity '
          'fraud, forged documents, delivery theft, food tampering, violence, or '
          'repeated serious violations. Such decisions may be final where necessary '
          'to protect users or comply with law.',
    ),
    LegalHeading(1, '12. DATA HANDLING'),
    LegalParagraph(
      'Documents and information collected for Verification are handled in '
          'accordance with the Privacy Policy, including confidentiality, access '
          'controls, and retention only for as long as necessary or as required by '
          'law. Verification data is used only for verification, safety, '
          'compliance, fraud prevention, and related legitimate purposes.',
    ),
    LegalHeading(1, '13. CHANGES TO THIS POLICY'),
    LegalParagraph(
      'Zopiq may update this Policy from time to time to reflect changes in '
          'law, regulatory requirements, or process. Material changes will be '
          'communicated through the Platform or by other reasonable means. The '
          '"Last Updated" date on the cover page indicates the latest version.',
    ),
    LegalHeading(1, '14. CONTACT INFORMATION'),
    LegalParagraph(
      'For questions, requests, or concerns relating to this document, please '
          'contact:',
    ),
    LegalParagraph(
      'Hybrid Monks LLP',
    ),
    LegalParagraph(
      'Brand: Zopiq',
    ),
    LegalParagraph(
      'Registered Office: C/O Meena Dev, Main Road, Sadri, Rajasthan – 306702, '
          'India',
    ),
    LegalParagraph(
      'Email: hello@hybridmonks.com',
    ),
    LegalParagraph(
      'Phone: +91 96608 77411',
    ),
    LegalParagraph(
      'GSTIN: 08AATFH7649R1Z2',
    ),
  ],
);
