// GENERATED BY tool/import_legal.mjs — DO NOT EDIT.
// Source: legal/source/06_Delivery_Partner_Handbook.docx
//
// Edit the Word document, run `node tool/import_legal.mjs`, commit both.
import 'package:zopiq_legal/src/legal_document.dart';

const LegalDocument deliveryPartnerHandbook = LegalDocument(
  slug: 'delivery-partner-handbook',
  title: 'Delivery Partner Handbook',
  subtitle: 'Operational Guide for Zopiq Delivery Partners',
  docId: 'ZOPIQ-OPS-06',
  version: '1.0',
  effectiveDate: '18 August 2026',
  group: 'partner',
  audiences: <LegalAudience>{LegalAudience.rider},
  requiresConsent: false,
  blocks: <LegalBlock>[
    LegalHeading(1, 'Document Control & Version History'),
    LegalParagraph(
      'This document is maintained under version control. Any material '
          'amendment will be recorded in the table below and reflected in the '
          'version number and effective date on the cover page.',
    ),
    LegalTable(
      headers: <String>['Version', 'Date', 'Summary of Changes', 'Approved By'],
      rows: <List<String>>[
        <String>['1.0', '18 August 2026', 'Initial publication-ready version.', 'Hybrid Monks LLP'],
      ],
    ),
    LegalHeading(1, '1. INTRODUCTION'),
    LegalParagraph(
      'This Delivery Partner Handbook ("Handbook") is a practical operational '
          'guide for Delivery Partners working with Zopiq, operated by Hybrid Monks '
          'LLP ("Zopiq", "Company", "we", "our", or "us"). It explains onboarding, '
          'verification, pickup and delivery procedures, cash handling, conduct, '
          'safety, and how earnings and performance work.',
    ),
    LegalParagraph(
      'This Handbook is operational guidance and supplements the Delivery '
          'Partner Agreement, Terms & Conditions, and other policies. Where this '
          'Handbook and a binding agreement differ, the agreement prevails. '
          'Delivery Partners operate as independent contractors, not employees of '
          'Hybrid Monks LLP.',
    ),
    LegalHeading(1, '2. DEFINITIONS'),
    LegalParagraph(
      'Delivery Partner Application means the app through which you receive '
          'assignments, navigate, and track earnings.',
    ),
    LegalParagraph(
      'Assignment means an order allocated to you for pickup and delivery.',
    ),
    LegalParagraph(
      'Pickup means collecting a prepared order from a Restaurant Partner.',
    ),
    LegalParagraph(
      'Drop means handing over the order to the Customer at the delivery '
          'location.',
    ),
    LegalParagraph(
      'COD means Cash on Delivery, where the Customer pays a balance on '
          'delivery after a 40% online advance.',
    ),
    LegalHeading(1, '3. ONBOARDING'),
    LegalParagraph(
      'Onboarding brings you onto the Platform in a verified, ready-to-work '
          'state.',
    ),
    LegalHeading(2, '3.1 Eligibility'),
    LegalParagraph(
      'You must be at least 18 years of age, hold a valid government-issued '
          'identity proof, possess a valid driving licence where applicable, and '
          'operate a legally compliant vehicle where required.',
    ),
    LegalHeading(2, '3.2 Onboarding Steps'),
    LegalBullets(<String>[
        'Register and provide your personal and contact details.',
        'Submit identity, licence, and vehicle documents for verification.',
        'Complete any required verification photograph or checks.',
        'Add bank or UPI details for payouts.',
        'Review and accept the Delivery Partner Agreement and applicable '
            'policies.',
        'Go online once verification is complete.',
    ]),
    LegalHeading(1, '4. DOCUMENT VERIFICATION'),
    LegalParagraph(
      'Verification protects Customers, Restaurant Partners, and you. Documents '
          'are handled under the Delivery Partner Verification Policy and Privacy '
          'Policy.',
    ),
    LegalHeading(2, '4.1 Documents Required'),
    LegalBullets(<String>[
        'Government-issued identity document.',
        'Driving licence (where applicable to your vehicle).',
        'Vehicle registration details (where applicable).',
        'Insurance details (where required).',
        'A verification photograph (where applicable).',
    ]),
    LegalHeading(2, '4.2 Keeping Documents Valid'),
    LegalParagraph(
      'You must keep all documents current. Expired licences, registration, or '
          'insurance may lead to temporary deactivation until valid documents are '
          'provided.',
    ),
    LegalHeading(1, '5. PICKUP STANDARD OPERATING PROCEDURE'),
    LegalParagraph(
      'A clean pickup keeps deliveries on time and food intact.',
    ),
    LegalBullets(<String>[
        'Accept only assignments you intend to complete.',
        'Travel promptly and safely to the Restaurant Partner.',
        'Confirm the order reference before collecting.',
        'Check that the order is sealed and appears complete; do not open or '
            'tamper with packaging.',
        'Handle the order carefully to avoid spills, keeping it upright and '
            'stable.',
        'Mark the pickup as collected in the app and proceed to the delivery '
            'location.',
    ]),
    LegalHeading(1, '6. DELIVERY STANDARD OPERATING PROCEDURE'),
    LegalParagraph(
      'The delivery is where Customer experience is won or lost.',
    ),
    LegalBullets(<String>[
        'Navigate safely to the delivery address using the in-app or preferred '
            'navigation.',
        'Follow reasonable delivery instructions provided by the Customer.',
        'Contact the Customer through in-app or masked calling if needed, '
            'respectfully and briefly.',
        'For COD, collect the correct balance before handover (see Cash '
            'Handling).',
        'Hand over the correct, sealed order and confirm completion in the app.',
        'If the Customer is unreachable, follow the app\'s prompts and '
            'reasonable attempts before marking a failed delivery.',
    ]),
    LegalHeading(1, '7. CASH HANDLING'),
    LegalParagraph(
      'Many orders are Cash on Delivery, and correct cash handling is '
          'essential.',
    ),
    LegalHeading(2, '7.1 COD Basics'),
    LegalParagraph(
      'For a COD order, the Customer has paid a 40% advance online. Collect the '
          'remaining balance in cash (or another accepted method) before handing '
          'over the order, unless the Platform expressly permits another '
          'arrangement.',
    ),
    LegalHeading(2, '7.2 Good Practices'),
    LegalBullets(<String>[
        'Confirm the exact balance shown in the app before collecting.',
        'Carry reasonable change where possible.',
        'Do not request any amount beyond Platform-authorised charges.',
        'Keep collected cash secure; reconcile with your app records.',
    ]),
    LegalHeading(2, '7.3 Refused or Failed COD'),
    LegalParagraph(
      'If a Customer refuses to pay the balance or the delivery otherwise fails '
          'due to Customer fault, follow the app\'s process to record a failed '
          'delivery. The Customer\'s 40% advance is non-refundable in such cases '
          'under the Refund & Cancellation Policy.',
    ),
    LegalHeading(1, '8. CUSTOMER INTERACTION'),
    LegalParagraph(
      'Professional, respectful interaction builds trust and ratings.',
    ),
    LegalBullets(<String>[
        'Be polite and courteous at all times.',
        'Respect Customer privacy and never reuse or retain Customer '
            'information.',
        'Keep communications brief and relevant to the delivery.',
        'Never use abusive, threatening, discriminatory, or offensive language.',
    ]),
    LegalHeading(1, '9. PROFESSIONAL CONDUCT'),
    LegalParagraph(
      'You represent the Platform experience at the doorstep. Conduct '
          'expectations include punctuality, honesty, respect for Customers and '
          'Restaurant staff, and adherence to these standards. Harassment, '
          'tampering with food, consuming Customer orders, or requesting extra '
          'payments are serious violations that may result in permanent '
          'deactivation.',
    ),
    LegalHeading(1, '10. DRESS CODE AND PRESENTATION'),
    LegalParagraph(
      'While you are an independent contractor, a neat and presentable '
          'appearance improves Customer confidence and safety.',
    ),
    LegalBullets(<String>[
        'Wear clean, appropriate clothing suitable for delivery work.',
        'Where provided or required, use approved delivery bags to keep food '
            'secure and at temperature.',
        'Keep delivery equipment clean and in good condition.',
        'Maintain personal hygiene, particularly when handling food packages.',
    ]),
    LegalHeading(1, '11. FOOD HANDLING'),
    LegalParagraph(
      'Even though food is prepared and sealed by the Restaurant Partner, safe '
          'handling in transit matters.',
    ),
    LegalBullets(<String>[
        'Keep orders upright and stable to prevent spills.',
        'Use an insulated delivery bag to maintain temperature where possible.',
        'Keep hot and cold items appropriately separated.',
        'Never open, tamper with, or consume any part of a Customer order.',
        'Deliver without unreasonable delay to preserve freshness.',
    ]),
    LegalHeading(1, '12. NAVIGATION'),
    LegalParagraph(
      'Efficient, safe navigation improves delivery times and earnings.',
    ),
    LegalBullets(<String>[
        'Use in-app or reliable navigation and follow lawful, safe routes.',
        'Do not interact with navigation while riding; stop safely if you need '
            'to check directions.',
        'Account for traffic, weather, and local conditions.',
        'Contact the Customer for clarification if an address is unclear, '
            'rather than guessing.',
    ]),
    LegalHeading(1, '13. EMERGENCY SITUATIONS'),
    LegalParagraph(
      'Your safety comes first. In an emergency, prioritise personal safety '
          'over completing a delivery.',
    ),
    LegalHeading(2, '13.1 General Emergencies'),
    LegalParagraph(
      'If you face a threat to your safety, move to a safe location and contact '
          'local emergency services where appropriate. Use any in-app safety or SOS '
          'features that are available, and inform Zopiq support as soon as it is '
          'safe to do so.',
    ),
    LegalHeading(2, '13.2 Unsafe Delivery Locations'),
    LegalParagraph(
      'If a delivery location is unsafe, do not put yourself at risk. Follow '
          'the app\'s process for unsafe locations and contact support for '
          'guidance.',
    ),
    LegalHeading(1, '14. ACCIDENTS'),
    LegalParagraph(
      'If you are involved in a road accident:',
    ),
    LegalBullets(<String>[
        'Prioritise safety and seek medical help where needed.',
        'Contact local emergency services and comply with applicable law.',
        'Where safe, secure the situation and exchange required information.',
        'Inform Zopiq support once it is safe, so the affected order can be '
            'managed.',
    ]),
    LegalParagraph(
      'You are responsible for compliance with applicable traffic laws and for '
          'damage caused by your own negligence, as set out in the Delivery Partner '
          'Agreement.',
    ),
    LegalHeading(1, '15. SAFETY'),
    LegalParagraph(
      'Ongoing safe practices protect you and others.',
    ),
    LegalBullets(<String>[
        'Wear a helmet and required safety gear; obey traffic laws and speed '
            'limits.',
        'Never deliver under the influence of alcohol or drugs.',
        'Take breaks to avoid fatigue, especially on long shifts.',
        'Keep your vehicle roadworthy and documents valid.',
        'Be aware of your surroundings, particularly during night deliveries.',
    ]),
    LegalHeading(1, '16. PERFORMANCE METRICS'),
    LegalParagraph(
      'Your performance is measured across several dimensions that affect '
          'assignments and standing.',
    ),
    LegalTable(
      headers: <String>['Metric', 'What It Measures'],
      rows: <List<String>>[
        <String>['Acceptance rate', 'How often you accept offered assignments.'],
        <String>['On-time performance', 'Timely pickups and deliveries relative to estimates.'],
        <String>['Completion rate', 'Assignments completed versus cancelled or dropped.'],
        <String>['Customer ratings', 'Feedback from Customers on your deliveries.'],
        <String>['Conduct compliance', 'Adherence to these standards and policies.'],
      ],
    ),
    LegalParagraph(
      'Repeated no-pickups, cancellations, unsafe conduct, or policy violations '
          'may result in warnings, suspension, or deactivation.',
    ),
    LegalHeading(1, '17. EARNINGS EXPLANATION'),
    LegalParagraph(
      'Your earnings are made up of delivery fees and any applicable '
          'incentives, subject to applicable deductions and taxes.',
    ),
    LegalHeading(2, '17.1 Delivery Fees'),
    LegalParagraph(
      'Delivery fees are dynamic and may vary based on distance, demand, '
          'weather (including rain), time of day (including night), availability of '
          'Delivery Partners, and special events. The applicable fee for an '
          'assignment is shown in the app.',
    ),
    LegalHeading(2, '17.2 Incentives'),
    LegalParagraph(
      'From time to time, Zopiq may offer incentives for completing a number of '
          'deliveries, working during peak periods, or similar. Incentive terms are '
          'communicated in the app and may change.',
    ),
    LegalHeading(2, '17.3 Settlements'),
    LegalParagraph(
      'Verified earnings are settled daily, subject to reconciliation, fraud '
          'review, taxes, and applicable deductions. Your earnings and settlement '
          'history are available in the Delivery Partner Application. Zopiq may '
          'withhold or adjust payouts where fraud, duplicate deliveries, or policy '
          'violations are reasonably suspected, pending investigation.',
    ),
    LegalHeading(1, '18. BEST PRACTICES'),
    LegalParagraph(
      'A concise checklist for reliable, high-quality deliveries:',
    ),
    LegalBullets(<String>[
        'Keep your documents valid and your vehicle roadworthy.',
        'Accept assignments you can complete; travel safely and promptly.',
        'Confirm order references at pickup and drop; never tamper with food.',
        'Collect the correct COD balance before handover.',
        'Communicate respectfully and protect Customer privacy.',
        'Prioritise safety in all situations, especially at night and in bad '
            'weather.',
        'Review your earnings and metrics regularly.',
    ]),
    LegalHeading(1, '19. CONTACT INFORMATION'),
    LegalParagraph(
      'For questions, requests, or concerns relating to this document, please '
          'contact:',
    ),
    LegalParagraph(
      'Hybrid Monks LLP',
    ),
    LegalParagraph(
      'Brand: Zopiq',
    ),
    LegalParagraph(
      'Registered Office: C/O Meena Dev, Main Road, Sadri, Rajasthan – 306702, '
          'India',
    ),
    LegalParagraph(
      'Email: hello@hybridmonks.com',
    ),
    LegalParagraph(
      'Phone: +91 96608 77411',
    ),
    LegalParagraph(
      'GSTIN: 08AATFH7649R1Z2',
    ),
  ],
);
