// GENERATED BY tool/import_legal.mjs — DO NOT EDIT.
// Source: legal/source/10_Fraud_Prevention_Policy.docx
//
// Edit the Word document, run `node tool/import_legal.mjs`, commit both.
import 'package:zopiq_legal/src/legal_document.dart';

const LegalDocument fraudPreventionPolicy = LegalDocument(
  slug: 'fraud-prevention-policy',
  title: 'Fraud Prevention Policy',
  subtitle: 'Detection, Prevention, and Response to Fraud and Abuse',
  docId: 'ZOPIQ-LEGAL-10',
  version: '1.0',
  effectiveDate: '18 August 2026',
  group: 'conduct',
  audiences: <LegalAudience>{LegalAudience.customer, LegalAudience.restaurant, LegalAudience.rider},
  requiresConsent: false,
  blocks: <LegalBlock>[
    LegalHeading(1, 'Document Control & Version History'),
    LegalParagraph(
      'This document is maintained under version control. Any material '
          'amendment will be recorded in the table below and reflected in the '
          'version number and effective date on the cover page.',
    ),
    LegalTable(
      headers: <String>['Version', 'Date', 'Summary of Changes', 'Approved By'],
      rows: <List<String>>[
        <String>['1.0', '18 August 2026', 'Initial publication-ready version.', 'Hybrid Monks LLP'],
      ],
    ),
    LegalHeading(1, '1. INTRODUCTION'),
    LegalParagraph(
      'This Fraud Prevention Policy ("Policy") describes how Zopiq, operated by '
          'Hybrid Monks LLP ("Zopiq", "Company", "we", "our", or "us"), detects, '
          'prevents, and responds to fraud and abuse on the Platform. It applies to '
          'Customers, Restaurant Partners, and Delivery Partners, and supplements '
          'the Terms & Conditions, Partner Agreements, and Payment & Settlement '
          'Policy.',
    ),
    LegalParagraph(
      'Fraud harms Customers, honest partners, and the Platform. Zopiq takes a '
          'firm, evidence-based approach to fraud while respecting due process and '
          'applicable law.',
    ),
    LegalHeading(1, '2. DEFINITIONS'),
    LegalParagraph(
      'Fraud means any dishonest act intended to obtain an unfair or unlawful '
          'gain, or to cause loss to another, in connection with the Platform.',
    ),
    LegalParagraph(
      'Abuse means misuse of Platform features, offers, or processes, whether '
          'or not it constitutes Fraud.',
    ),
    LegalParagraph(
      'Investigation means the process by which Zopiq reviews suspected Fraud '
          'or Abuse.',
    ),
    LegalParagraph(
      'Enforcement Action means any measure taken in response to Fraud or '
          'Abuse, including holds, restrictions, suspension, termination, or '
          'referral to authorities.',
    ),
    LegalHeading(1, '3. PRINCIPLES'),
    LegalParagraph(
      'Zopiq\'s approach to fraud is guided by the following principles:',
    ),
    LegalBullets(<String>[
        'Prevention first: reduce opportunities for Fraud through verification '
            'and controls.',
        'Proportionality: responses match the severity and evidence of the '
            'conduct.',
        'Fairness: affected Users are handled with due process, subject to '
            'safety and legal limits.',
        'Privacy: personal data used in fraud prevention is handled under the '
            'Privacy Policy.',
        'Compliance: serious Fraud may be reported to relevant authorities.',
    ]),
    LegalHeading(1, '4. FAKE ORDERS'),
    LegalParagraph(
      'Placing fake orders, orders without intent to complete the purchase, or '
          'orders using false information is prohibited. Indicators include '
          'repeated refusals, unreachable Customers, invalid addresses, and '
          'abnormal ordering patterns. Zopiq may restrict COD, require prepayment, '
          'or suspend accounts engaged in fake ordering.',
    ),
    LegalHeading(1, '5. COD ABUSE'),
    LegalParagraph(
      'Cash on Delivery is offered subject to a mandatory 40% advance to reduce '
          'abandoned and fraudulent orders. Abuse includes repeatedly refusing COD '
          'deliveries, providing wrong addresses, or being deliberately unreachable '
          'after ordering.',
    ),
    LegalHeading(2, '5.1 Consequences'),
    LegalParagraph(
      'Repeated COD abuse may result in forfeiture of the non-refundable 40% '
          'advance (where the failure is the Customer\'s fault), temporary '
          'suspension of COD privileges, mandatory prepaid-only ordering, or '
          'account suspension, consistent with the Terms & Conditions and Refund & '
          'Cancellation Policy.',
    ),
    LegalHeading(1, '6. COUPON AND REFERRAL ABUSE'),
    LegalParagraph(
      'Promotional offers and referral programs are for genuine use by eligible '
          'Users. Prohibited conduct includes creating multiple or fake accounts to '
          'claim offers, exploiting technical errors, self-referral, and '
          'coordinated schemes to extract promotional value. Zopiq may reverse '
          'improperly obtained benefits and take Enforcement Action.',
    ),
    LegalHeading(1, '7. RESTAURANT FRAUD'),
    LegalParagraph(
      'Restaurant-side Fraud includes falsified licences, misleading listings '
          'intended to deceive, manipulation of orders or settlements, collusion to '
          'generate fake orders, and billing for items not provided. Zopiq may '
          'withhold settlements pending Investigation, remove listings, and suspend '
          'or terminate Restaurant Partners engaged in Fraud, and may report '
          'unlawful conduct.',
    ),
    LegalHeading(1, '8. DELIVERY FRAUD'),
    LegalParagraph(
      'Delivery-side Fraud includes marking deliveries as completed without '
          'delivering, delivery theft or tampering, collusion with Customers or '
          'restaurants, manipulation of location or proof-of-delivery, and '
          'generating duplicate or fictitious deliveries. Zopiq may withhold or '
          'adjust payouts pending Investigation and deactivate Delivery Partners '
          'engaged in Fraud.',
    ),
    LegalHeading(1, '9. PAYMENT FRAUD'),
    LegalParagraph(
      'Payment Fraud includes unauthorised use of payment instruments, '
          'chargeback fraud, and manipulation of refunds or settlements. Zopiq '
          'works with authorised payment providers, does not store complete card or '
          'UPI PIN credentials, and may hold or reverse transactions, restrict '
          'payment methods, and take Enforcement Action where Payment Fraud is '
          'reasonably suspected.',
    ),
    LegalHeading(1, '10. IDENTITY FRAUD'),
    LegalParagraph(
      'Identity Fraud includes providing false identity information, using '
          'another person\'s identity or documents, and submitting forged '
          'documents. Zopiq may require identity verification, suspend accounts '
          'pending verification, and terminate accounts and refer matters to '
          'authorities where Identity Fraud is established.',
    ),
    LegalHeading(1, '11. ACCOUNT VERIFICATION AND CONTROLS'),
    LegalParagraph(
      'To prevent Fraud, Zopiq may implement verification and detection '
          'measures, including:',
    ),
    LegalBullets(<String>[
        'Device and IP analysis.',
        'Payment risk assessment.',
        'Multiple-account detection.',
        'Order and delivery pattern analysis.',
        'Identity and location verification.',
        'Behavioural analytics.',
    ]),
    LegalParagraph(
      'These measures are applied consistently with the Privacy Policy and '
          'principles of data minimization.',
    ),
    LegalHeading(1, '12. INVESTIGATION PROCEDURES'),
    LegalParagraph(
      'Where Fraud or Abuse is reasonably suspected, Zopiq may investigate.',
    ),
    LegalHeading(2, '12.1 Interim Measures'),
    LegalParagraph(
      'During an Investigation, Zopiq may hold or delay payments and '
          'settlements, restrict payment methods, disable COD, request additional '
          'verification, or temporarily suspend accounts, to the extent reasonably '
          'necessary and subject to applicable law.',
    ),
    LegalHeading(2, '12.2 Conducting the Investigation'),
    LegalParagraph(
      'Zopiq reviews relevant data and evidence, may request information from '
          'affected Users, and assesses the matter objectively. Users are expected '
          'to cooperate and provide reasonably requested information.',
    ),
    LegalHeading(2, '12.3 Outcomes'),
    LegalTable(
      headers: <String>['Finding', 'Typical Outcome'],
      rows: <List<String>>[
        <String>['No Fraud found', 'Interim measures lifted; normal service resumes.'],
        <String>['Minor Abuse', 'Warning, reversal of improper benefit, or feature restriction.'],
        <String>['Serious or repeated Fraud', 'Suspension or permanent termination; settlement adjustments.'],
        <String>['Unlawful conduct', 'Referral to relevant authorities and possible legal action.'],
      ],
    ),
    LegalHeading(1, '13. CONSEQUENCES AND ENFORCEMENT'),
    LegalParagraph(
      'Enforcement Action is proportionate to the conduct and may include '
          'warnings, reversal of improperly obtained value, restriction of features '
          'or payment methods, withholding or adjustment of settlements or payouts, '
          'suspension, permanent termination, and referral to law enforcement. '
          'Providing false information, forged documents, or engaging in payment '
          'fraud may lead to permanent account termination and legal action.',
    ),
    LegalHeading(1, '14. APPEALS'),
    LegalParagraph(
      'A User affected by Enforcement Action may appeal through in-app support '
          'or the contact details in this Policy, providing relevant information. '
          'Zopiq will review appeals fairly and within a reasonable timeframe. '
          'Decisions on serious Fraud may be final where necessary to protect users '
          'or comply with law.',
    ),
    LegalHeading(1, '15. CHANGES TO THIS POLICY'),
    LegalParagraph(
      'Zopiq may update this Policy from time to time to reflect changes in '
          'law, fraud patterns, or technology. Material changes will be '
          'communicated through the Platform or by other reasonable means. The '
          '"Last Updated" date on the cover page indicates the latest version.',
    ),
    LegalHeading(1, '16. CONTACT INFORMATION'),
    LegalParagraph(
      'For questions, requests, or concerns relating to this document, please '
          'contact:',
    ),
    LegalParagraph(
      'Hybrid Monks LLP',
    ),
    LegalParagraph(
      'Brand: Zopiq',
    ),
    LegalParagraph(
      'Registered Office: C/O Meena Dev, Main Road, Sadri, Rajasthan – 306702, '
          'India',
    ),
    LegalParagraph(
      'Email: hello@hybridmonks.com',
    ),
    LegalParagraph(
      'Phone: +91 96608 77411',
    ),
    LegalParagraph(
      'GSTIN: 08AATFH7649R1Z2',
    ),
  ],
);
