// GENERATED BY tool/import_legal.mjs — DO NOT EDIT.
// Source: legal/source/08_Grievance_Redressal_Policy.docx
//
// Edit the Word document, run `node tool/import_legal.mjs`, commit both.
import 'package:zopiq_legal/src/legal_document.dart';

const LegalDocument grievanceRedressalPolicy = LegalDocument(
  slug: 'grievance-redressal-policy',
  title: 'Grievance Redressal Policy',
  subtitle: 'Complaints, Escalation, and Resolution',
  docId: 'ZOPIQ-LEGAL-08',
  version: '1.0',
  effectiveDate: '18 August 2026',
  group: 'support',
  audiences: <LegalAudience>{LegalAudience.customer, LegalAudience.restaurant, LegalAudience.rider},
  requiresConsent: false,
  blocks: <LegalBlock>[
    LegalHeading(1, 'Document Control & Version History'),
    LegalParagraph(
      'This document is maintained under version control. Any material '
          'amendment will be recorded in the table below and reflected in the '
          'version number and effective date on the cover page.',
    ),
    LegalTable(
      headers: <String>['Version', 'Date', 'Summary of Changes', 'Approved By'],
      rows: <List<String>>[
        <String>['1.0', '18 August 2026', 'Initial publication-ready version.', 'Hybrid Monks LLP'],
      ],
    ),
    LegalHeading(1, '1. INTRODUCTION'),
    LegalParagraph(
      'This Grievance Redressal Policy ("Policy") explains how Customers, '
          'Restaurant Partners, and Delivery Partners can raise complaints and '
          'grievances relating to the Zopiq platform, operated by Hybrid Monks LLP '
          '("Zopiq", "Company", "we", "our", or "us"), and how those grievances are '
          'handled. It is designed to provide a fair, accessible, and time-bound '
          'process, consistent with applicable Indian law, including the Consumer '
          'Protection Act, 2019, the Information Technology Act, 2000, and the '
          'Digital Personal Data Protection Act, 2023.',
    ),
    LegalHeading(1, '2. DEFINITIONS'),
    LegalParagraph(
      'Grievance means any complaint, concern, or dispute raised by a User '
          'relating to the Platform, an order, a settlement, conduct, or the '
          'handling of personal data.',
    ),
    LegalParagraph(
      'Complainant means the User raising a Grievance.',
    ),
    LegalParagraph(
      'Grievance Officer means the person designated by Zopiq to oversee '
          'grievance handling.',
    ),
    LegalParagraph(
      'Resolution means the outcome communicated to the Complainant after '
          'review.',
    ),
    LegalHeading(1, '3. PRINCIPLES'),
    LegalParagraph(
      'Grievance handling is guided by the following principles:',
    ),
    LegalBullets(<String>[
        'Accessibility: multiple channels are available to raise a Grievance.',
        'Fairness: Grievances are assessed objectively and on their merits.',
        'Timeliness: Grievances are acknowledged and resolved within reasonable '
            'timeframes.',
        'Transparency: outcomes are communicated to the Complainant.',
        'Confidentiality: personal data is handled in line with the Privacy '
            'Policy.',
    ]),
    LegalHeading(1, '4. HOW TO SUBMIT A COMPLAINT'),
    LegalParagraph(
      'A Grievance may be submitted through any of the following channels:',
    ),
    LegalBullets(<String>[
        'In-app support within the Customer, Restaurant Partner, or Delivery '
            'Partner Application.',
        'Email to hello@hybridmonks.com.',
        'Phone at +91 96608 77411.',
        'Written correspondence to the registered office address.',
    ]),
    LegalHeading(2, '4.1 Information to Include'),
    LegalParagraph(
      'To help resolve a Grievance efficiently, the Complainant should provide '
          'account details, the relevant order or reference number, a clear '
          'description of the issue, and any supporting information or evidence.',
    ),
    LegalHeading(1, '5. RESOLUTION TIMELINES'),
    LegalParagraph(
      'Zopiq aims to acknowledge and resolve Grievances within reasonable '
          'timeframes, which may vary with complexity. Indicative targets are set '
          'out below.',
    ),
    LegalTable(
      headers: <String>['Stage', 'Indicative Timeframe'],
      rows: <List<String>>[
        <String>['Acknowledgement of Grievance', 'Promptly after receipt, typically within a few working days.'],
        <String>['First response / assessment', 'Within a reasonable period after acknowledgement.'],
        <String>['Resolution of standard Grievances', 'Within a reasonable period, subject to investigation and complexity.'],
        <String>['Complex or disputed matters', 'May require additional time; the Complainant will be kept informed.'],
      ],
    ),
    LegalParagraph(
      'These are service targets and not guarantees; statutory timeframes, '
          'where applicable, are observed.',
    ),
    LegalHeading(1, '6. ESCALATION'),
    LegalParagraph(
      'If a Complainant is not satisfied with the initial response, the '
          'Grievance may be escalated.',
    ),
    LegalHeading(2, '6.1 Escalation to the Grievance Officer'),
    LegalParagraph(
      'Unresolved or escalated Grievances may be directed to the Grievance '
          'Officer, who will review the matter afresh, consider the Complainant\'s '
          'submissions and relevant evidence, and communicate an outcome.',
    ),
    LegalHeading(2, '6.2 Grievance Officer Details'),
    LegalParagraph(
      'Zopiq designates a Grievance Officer for the Platform. The Grievance '
          'Officer can be reached via the contact details in this Policy. Zopiq '
          'will publish or update the Grievance Officer\'s designation as required '
          'by applicable law.',
    ),
    LegalHeading(1, '7. CONSUMER COMPLAINTS'),
    LegalParagraph(
      'Consumer Grievances typically relate to orders, refunds, missing or '
          'damaged items, delivery issues, payments, or service quality. These are '
          'handled under this Policy together with the Refund & Cancellation Policy '
          'and Payment & Settlement Policy. Nothing in this Policy limits a '
          'consumer\'s rights under the Consumer Protection Act, 2019, or the '
          'ability to approach a competent consumer forum.',
    ),
    LegalHeading(1, '8. RESTAURANT PARTNER COMPLAINTS'),
    LegalParagraph(
      'Restaurant Partner Grievances typically relate to settlements, '
          'deductions, order disputes, ratings, account actions, or support. These '
          'are handled under this Policy together with the Restaurant Partner '
          'Agreement, Merchant SLA, and Payment & Settlement Policy. Restaurant '
          'Partners should raise settlement-related Grievances with relevant order '
          'and settlement references.',
    ),
    LegalHeading(1, '9. DELIVERY PARTNER COMPLAINTS'),
    LegalParagraph(
      'Delivery Partner Grievances typically relate to earnings, payouts, '
          'deductions, assignments, account actions, or safety. These are handled '
          'under this Policy together with the Delivery Partner Agreement and '
          'Payment & Settlement Policy. Safety-related Grievances are treated with '
          'priority.',
    ),
    LegalHeading(1, '10. PRIVACY AND DATA COMPLAINTS'),
    LegalParagraph(
      'Grievances relating to the handling of personal data — including access, '
          'correction, deletion, or withdrawal of consent — are handled in '
          'accordance with the Privacy Policy and the Digital Personal Data '
          'Protection Act, 2023. Such Grievances may be directed to the Grievance '
          'Officer or the contact details in this Policy. Zopiq may require '
          'reasonable identity verification before acting on data-related requests.',
    ),
    LegalHeading(1, '11. LEGAL NOTICES'),
    LegalParagraph(
      'Formal legal notices should be sent in writing to the registered office '
          'address or to hello@hybridmonks.com, unless Zopiq designates another '
          'address in writing. Before initiating legal proceedings, Users are '
          'encouraged to make reasonable efforts to resolve disputes through this '
          'Policy and, where appropriate, may mutually agree to mediation, '
          'consistent with the dispute-resolution provisions of the Terms & '
          'Conditions and relevant agreements.',
    ),
    LegalHeading(1, '12. RECORD-KEEPING'),
    LegalParagraph(
      'Zopiq maintains records of Grievances and their resolution for service '
          'quality, dispute resolution, and legal compliance, in accordance with '
          'the Privacy Policy and Account Deletion & Data Retention Policy.',
    ),
    LegalHeading(1, '13. CHANGES TO THIS POLICY'),
    LegalParagraph(
      'Zopiq may update this Policy from time to time to reflect changes in '
          'law, Platform features, or process. Material changes will be '
          'communicated through the Platform or by other reasonable means. The '
          '"Last Updated" date on the cover page indicates the latest version.',
    ),
    LegalHeading(1, '14. CONTACT INFORMATION'),
    LegalParagraph(
      'For questions, requests, or concerns relating to this document, please '
          'contact:',
    ),
    LegalParagraph(
      'Hybrid Monks LLP',
    ),
    LegalParagraph(
      'Brand: Zopiq',
    ),
    LegalParagraph(
      'Registered Office: C/O Meena Dev, Main Road, Sadri, Rajasthan – 306702, '
          'India',
    ),
    LegalParagraph(
      'Email: hello@hybridmonks.com',
    ),
    LegalParagraph(
      'Phone: +91 96608 77411',
    ),
    LegalParagraph(
      'GSTIN: 08AATFH7649R1Z2',
    ),
  ],
);
