// GENERATED BY tool/import_legal.mjs — DO NOT EDIT.
// Source: legal/source/09_Intellectual_Property_Policy.docx
//
// Edit the Word document, run `node tool/import_legal.mjs`, commit both.
import 'package:zopiq_legal/src/legal_document.dart';

const LegalDocument intellectualPropertyPolicy = LegalDocument(
  slug: 'intellectual-property-policy',
  title: 'Intellectual Property Policy',
  subtitle: 'Ownership, Licensing, and Infringement Reporting',
  docId: 'ZOPIQ-LEGAL-09',
  version: '1.0',
  effectiveDate: '18 August 2026',
  group: 'conduct',
  audiences: <LegalAudience>{LegalAudience.customer, LegalAudience.restaurant, LegalAudience.rider},
  requiresConsent: false,
  blocks: <LegalBlock>[
    LegalHeading(1, 'Document Control & Version History'),
    LegalParagraph(
      'This document is maintained under version control. Any material '
          'amendment will be recorded in the table below and reflected in the '
          'version number and effective date on the cover page.',
    ),
    LegalTable(
      headers: <String>['Version', 'Date', 'Summary of Changes', 'Approved By'],
      rows: <List<String>>[
        <String>['1.0', '18 August 2026', 'Initial publication-ready version.', 'Hybrid Monks LLP'],
      ],
    ),
    LegalHeading(1, '1. INTRODUCTION'),
    LegalParagraph(
      'This Intellectual Property Policy ("Policy") explains the ownership and '
          'permitted use of intellectual property in connection with the Zopiq '
          'platform, operated by Hybrid Monks LLP ("Zopiq", "Company", "we", "our", '
          'or "us"), and the procedure for reporting alleged infringement. It '
          'supplements the intellectual property provisions of the Terms & '
          'Conditions and the Partner Agreements.',
    ),
    LegalHeading(1, '2. DEFINITIONS'),
    LegalParagraph(
      'Platform IP means intellectual property owned by or licensed to Hybrid '
          'Monks LLP, including the Zopiq name, logos, software, source code, APIs, '
          'designs, and related materials.',
    ),
    LegalParagraph(
      'User Content means content submitted by Users, such as reviews, images, '
          'and menu information.',
    ),
    LegalParagraph(
      'Rights Holder means a person who owns or controls intellectual property '
          'rights.',
    ),
    LegalParagraph(
      'Infringement means the unauthorised use of intellectual property in a '
          'manner that violates a Rights Holder\'s rights.',
    ),
    LegalHeading(1, '3. OWNERSHIP OF PLATFORM IP'),
    LegalParagraph(
      'All rights, title, and interest in and to the Platform, including the '
          'Zopiq name, logo, mobile applications, website, software, source code, '
          'APIs, UI/UX designs, icons, graphics, animations, databases, business '
          'processes, documentation, and related materials, are owned by or '
          'licensed to Hybrid Monks LLP and are protected under applicable '
          'copyright, trademark, patent, trade secret, and other intellectual '
          'property laws.',
    ),
    LegalParagraph(
      'Nothing in this Policy or in the use of the Platform transfers ownership '
          'of any Platform IP to any User.',
    ),
    LegalHeading(1, '4. COPYRIGHT'),
    LegalParagraph(
      'Original works on the Platform, including software, text, graphics, and '
          'design, are protected by copyright. Users must not copy, reproduce, '
          'modify, distribute, or create derivative works from Platform IP except '
          'as expressly permitted. Copyright in User Content remains with the User '
          'or its owner, subject to the licence granted to Zopiq described in this '
          'Policy and the Terms & Conditions.',
    ),
    LegalHeading(1, '5. TRADEMARK'),
    LegalParagraph(
      '"Zopiq", its logos, branding elements, slogans, and associated marks are '
          'trademarks or registered trademarks of Hybrid Monks LLP. Users shall not '
          'use these marks without prior written permission, and shall not use any '
          'confusingly similar marks or use the marks in a way that suggests '
          'endorsement or affiliation that does not exist.',
    ),
    LegalHeading(1, '6. LIMITED LICENCE TO USERS'),
    LegalParagraph(
      'Subject to compliance with the Terms & Conditions, Zopiq grants Users a '
          'limited, non-exclusive, non-transferable, revocable licence to access '
          'and use the Platform solely for its intended purpose. This licence does '
          'not permit copying, modifying, reverse engineering, selling, '
          'redistributing, scraping, or creating competing products using Zopiq '
          'technology.',
    ),
    LegalHeading(1, '7. RESTAURANT IMAGES AND MENU OWNERSHIP'),
    LegalHeading(2, '7.1 Ownership'),
    LegalParagraph(
      'Restaurant Partners retain ownership of their own menu content, '
          'restaurant images, and branding that they lawfully provide, subject to '
          'the licence they grant to Zopiq.',
    ),
    LegalHeading(2, '7.2 Licence to Zopiq'),
    LegalParagraph(
      'By uploading menu content, images, and branding, the Restaurant Partner '
          'grants Zopiq a non-exclusive, worldwide, royalty-free, sublicensable '
          'licence to host, store, display, reproduce, format, publish, and '
          'distribute such content for the purpose of operating, promoting, '
          'improving, and securing the Platform.',
    ),
    LegalHeading(2, '7.3 Warranty'),
    LegalParagraph(
      'Restaurant Partners warrant that they own or are licensed to use the '
          'content they upload, that it does not infringe third-party rights, and '
          'that it is lawful and not misleading.',
    ),
    LegalHeading(1, '8. USER-GENERATED CONTENT'),
    LegalParagraph(
      'Users may upload reviews, ratings, photographs, and comments permitted '
          'by the Platform. Users retain ownership of their content but grant Zopiq '
          'a worldwide, non-exclusive, royalty-free, sublicensable licence to host, '
          'store, display, reproduce, format, publish, and distribute such content '
          'in connection with operating, improving, promoting, and securing the '
          'Platform. Users warrant that their content is lawful, non-infringing, '
          'and not misleading.',
    ),
    LegalHeading(1, '9. BRAND USAGE'),
    LegalParagraph(
      'Any use of Zopiq brand assets by Restaurant Partners, Delivery Partners, '
          'or third parties requires prior written permission and must comply with '
          'any brand guidelines Zopiq provides. Permitted use must not damage the '
          'brand, imply false endorsement, or mislead Users. Zopiq may revoke '
          'permission to use its brand assets at any time.',
    ),
    LegalHeading(1, '10. INFRINGEMENT REPORTING AND NOTICE PROCEDURE'),
    LegalParagraph(
      'Zopiq respects intellectual property rights and provides a procedure for '
          'Rights Holders to report alleged Infringement on the Platform.',
    ),
    LegalHeading(2, '10.1 How to Submit a Notice'),
    LegalParagraph(
      'A Rights Holder (or their authorised agent) may submit a notice of '
          'alleged Infringement to hello@hybridmonks.com or the registered office '
          'address. To enable Zopiq to act, the notice should include:',
    ),
    LegalBullets(<String>[
        'Identification of the work or right claimed to be infringed.',
        'Identification of the allegedly infringing material and its location '
            'on the Platform.',
        'The Rights Holder\'s contact details.',
        'A statement that the complainant believes in good faith that the use '
            'is not authorised.',
        'A statement that the information in the notice is accurate, and that '
            'the complainant is the Rights Holder or authorised to act on their '
            'behalf.',
    ]),
    LegalHeading(2, '10.2 Action on a Valid Notice'),
    LegalParagraph(
      'On receiving a valid notice, Zopiq may remove or disable access to the '
          'allegedly infringing material, notify the User who provided it where '
          'appropriate, and take further action consistent with its policies and '
          'applicable law.',
    ),
    LegalHeading(2, '10.3 Counter-Notice'),
    LegalParagraph(
      'A User whose content is removed may submit a counter-notice explaining '
          'why the content is not infringing, including their contact details and a '
          'good-faith statement. Zopiq may restore content where appropriate after '
          'considering the counter-notice, unless doing so would be unlawful.',
    ),
    LegalHeading(2, '10.4 Repeat Infringers'),
    LegalParagraph(
      'Zopiq may suspend or terminate the accounts of Users who repeatedly '
          'infringe intellectual property rights.',
    ),
    LegalHeading(1, '11. MISUSE OF THIS PROCEDURE'),
    LegalParagraph(
      'Submitting false or bad-faith notices or counter-notices is prohibited '
          'and may result in Enforcement Action and liability under applicable law. '
          'Zopiq is not obliged to act on notices that are incomplete or that do '
          'not appear to be made in good faith.',
    ),
    LegalHeading(1, '12. CHANGES TO THIS POLICY'),
    LegalParagraph(
      'Zopiq may update this Policy from time to time to reflect changes in '
          'law, Platform features, or process. Material changes will be '
          'communicated through the Platform or by other reasonable means. The '
          '"Last Updated" date on the cover page indicates the latest version.',
    ),
    LegalHeading(1, '13. CONTACT INFORMATION'),
    LegalParagraph(
      'For questions, requests, or concerns relating to this document, please '
          'contact:',
    ),
    LegalParagraph(
      'Hybrid Monks LLP',
    ),
    LegalParagraph(
      'Brand: Zopiq',
    ),
    LegalParagraph(
      'Registered Office: C/O Meena Dev, Main Road, Sadri, Rajasthan – 306702, '
          'India',
    ),
    LegalParagraph(
      'Email: hello@hybridmonks.com',
    ),
    LegalParagraph(
      'Phone: +91 96608 77411',
    ),
    LegalParagraph(
      'GSTIN: 08AATFH7649R1Z2',
    ),
  ],
);
