// GENERATED BY tool/import_legal.mjs — DO NOT EDIT.
// Source: legal/source/07_Merchant_SLA.docx
//
// Edit the Word document, run `node tool/import_legal.mjs`, commit both.
import 'package:zopiq_legal/src/legal_document.dart';

const LegalDocument merchantSla = LegalDocument(
  slug: 'merchant-sla',
  title: 'Merchant Service Level Agreement',
  subtitle: 'Performance Standards for Restaurant Partners',
  docId: 'ZOPIQ-OPS-07',
  version: '1.0',
  effectiveDate: '18 August 2026',
  group: 'partner',
  audiences: <LegalAudience>{LegalAudience.restaurant},
  requiresConsent: false,
  blocks: <LegalBlock>[
    LegalHeading(1, 'Document Control & Version History'),
    LegalParagraph(
      'This document is maintained under version control. Any material '
          'amendment will be recorded in the table below and reflected in the '
          'version number and effective date on the cover page.',
    ),
    LegalTable(
      headers: <String>['Version', 'Date', 'Summary of Changes', 'Approved By'],
      rows: <List<String>>[
        <String>['1.0', '18 August 2026', 'Initial publication-ready version.', 'Hybrid Monks LLP'],
      ],
    ),
    LegalHeading(1, '1. INTRODUCTION'),
    LegalParagraph(
      'This Merchant Service Level Agreement ("SLA") sets out the service '
          'levels expected of Restaurant Partners on the Zopiq platform, operated '
          'by Hybrid Monks LLP ("Zopiq", "Company", "we", "our", or "us"), and the '
          'framework used to monitor performance and apply consequences where '
          'standards are not met.',
    ),
    LegalParagraph(
      'This SLA supplements the Restaurant Partner Agreement, Terms & '
          'Conditions, and Restaurant Partner Handbook. Where this SLA and a '
          'binding agreement differ, the agreement prevails. Zopiq may set or '
          'update specific numeric thresholds prospectively with reasonable notice.',
    ),
    LegalHeading(1, '2. DEFINITIONS'),
    LegalParagraph(
      'Acceptance Rate means the proportion of offered orders that a Restaurant '
          'Partner accepts over a defined period.',
    ),
    LegalParagraph(
      'Preparation Time means the time from order acceptance to the order being '
          'ready for pickup.',
    ),
    LegalParagraph(
      'Cancellation Rate means the proportion of accepted orders cancelled by '
          'the Restaurant Partner.',
    ),
    LegalParagraph(
      'Availability means the extent to which a Restaurant Partner is open and '
          'accepting orders during its stated operating hours.',
    ),
    LegalParagraph(
      'Measurement Period means the rolling period over which a metric is '
          'assessed.',
    ),
    LegalHeading(1, '3. GENERAL PRINCIPLES'),
    LegalParagraph(
      'The SLA is designed to be fair, transparent, and improvement-focused:',
    ),
    LegalBullets(<String>[
        'Metrics are assessed over a Measurement Period rather than single '
            'orders, save for serious breaches.',
        'Genuine operational reasons and Force Majeure Events are taken into '
            'account.',
        'Consequences are proportionate and escalate with severity and '
            'frequency.',
        'Restaurant Partners can view their performance and are given '
            'opportunities to improve.',
    ]),
    LegalHeading(1, '4. ACCEPTANCE RATE'),
    LegalParagraph(
      'Restaurant Partners are expected to accept orders reliably during their '
          'stated operating hours. A high Acceptance Rate reduces failed orders and '
          'improves Customer experience.',
    ),
    LegalHeading(2, '4.1 Expectation'),
    LegalParagraph(
      'Restaurant Partners should accept the substantial majority of valid '
          'orders received while shown as open. Persistent low acceptance suggests '
          'inaccurate availability or operating hours that should be corrected.',
    ),
    LegalHeading(2, '4.2 Exclusions'),
    LegalParagraph(
      'Orders that cannot reasonably be fulfilled due to genuine operational '
          'reasons, safety issues, or Force Majeure Events are considered when '
          'assessing Acceptance Rate.',
    ),
    LegalHeading(1, '5. PREPARATION TIME'),
    LegalParagraph(
      'Accurate and reliable preparation times keep deliveries on schedule and '
          'food fresh.',
    ),
    LegalHeading(2, '5.1 Expectation'),
    LegalParagraph(
      'Restaurant Partners should set realistic preparation times and prepare '
          'orders within them. Consistent overruns affect delivery coordination and '
          'Customer satisfaction.',
    ),
    LegalHeading(2, '5.2 Managing Peaks'),
    LegalParagraph(
      'During busy periods, Restaurant Partners should adjust preparation times '
          'or availability to reflect actual capacity rather than accept orders '
          'they cannot prepare on time.',
    ),
    LegalHeading(1, '6. CANCELLATION LIMITS'),
    LegalParagraph(
      'Cancellations by Restaurant Partners should be rare and only for genuine '
          'operational reasons.',
    ),
    LegalHeading(2, '6.1 Permitted Reasons'),
    LegalParagraph(
      'Acceptable reasons include item unavailability, kitchen malfunction, '
          'restaurant closure, a safety or health emergency, or a Force Majeure '
          'Event.',
    ),
    LegalHeading(2, '6.2 Prohibited Cancellations'),
    LegalParagraph(
      'Restaurant Partners must not cancel accepted orders to manipulate '
          'availability, pricing, ratings, or Customer experience. Repeated or '
          'manipulative cancellations are treated as a serious breach.',
    ),
    LegalHeading(1, '7. PACKAGING SLA'),
    LegalParagraph(
      'Packaging must protect food during transit. Restaurant Partners are '
          'expected to seal liquids securely, use appropriate containers, avoid '
          'overfilling, and label orders clearly. Packaging failures leading to '
          'leaks, spills, or mix-ups are attributable to the Restaurant Partner and '
          'may result in refunds deducted from settlements, as set out in the '
          'Refund & Cancellation Policy.',
    ),
    LegalHeading(1, '8. AVAILABILITY'),
    LegalParagraph(
      'Restaurant Partners should be open and accepting orders during their '
          'stated operating hours and keep availability accurate in real time. '
          'Frequent unexpected closures during stated hours, or failure to update '
          'availability, degrade Customer experience and are considered in '
          'performance assessment.',
    ),
    LegalHeading(1, '9. SUPPORT RESPONSE'),
    LegalParagraph(
      'Zopiq aims to provide timely support to Restaurant Partners, and '
          'Restaurant Partners are expected to respond promptly to operational and '
          'support communications.',
    ),
    LegalTable(
      headers: <String>['Interaction', 'Target Approach'],
      rows: <List<String>>[
        <String>['Order-related issues (live orders)', 'Handled with priority to protect the Customer experience.'],
        <String>['Operational queries', 'Addressed within a reasonable timeframe through support channels.'],
        <String>['Settlement queries', 'Investigated and reconciled in line with the settlement process.'],
        <String>['Restaurant responsiveness', 'Restaurant Partners should respond promptly to alerts affecting live '
              'orders.'],
      ],
    ),
    LegalParagraph(
      'Support targets are service goals and may vary with volume and '
          'complexity; they do not create a guarantee.',
    ),
    LegalHeading(1, '10. PERFORMANCE MONITORING'),
    LegalParagraph(
      'Zopiq monitors performance across the metrics in this SLA using data '
          'from the Platform.',
    ),
    LegalHeading(2, '10.1 Visibility'),
    LegalParagraph(
      'Restaurant Partners can view relevant performance metrics through the '
          'Restaurant Partner Application, along with operational insights such as '
          'order volumes, peak times, and average preparation times.',
    ),
    LegalHeading(2, '10.2 Assessment'),
    LegalParagraph(
      'Metrics are assessed over the Measurement Period, taking into account '
          'genuine operational context. Isolated issues are treated differently '
          'from persistent underperformance.',
    ),
    LegalHeading(1, '11. PENALTY FRAMEWORK'),
    LegalParagraph(
      'Where performance falls below expectations, Zopiq may apply '
          'proportionate consequences that escalate with severity and frequency.',
    ),
    LegalTable(
      headers: <String>['Stage', 'Typical Trigger', 'Consequence'],
      rows: <List<String>>[
        <String>['Guidance', 'First or minor shortfall.', 'Feedback and improvement guidance.'],
        <String>['Warning', 'Continued shortfall after guidance.', 'Formal warning and improvement expectation.'],
        <String>['Reduced visibility', 'Persistent underperformance.', 'Temporary reduction in Platform visibility.'],
        <String>['Suspension', 'Serious or repeated breaches.', 'Temporary suspension pending improvement or review.'],
        <String>['Removal', 'Severe or persistent breaches; manipulation; safety issues.', 'Permanent removal from the Platform.'],
      ],
    ),
    LegalParagraph(
      'For serious risks to Customers, food safety, or Platform integrity, '
          'Zopiq may suspend or remove a Restaurant Partner immediately, consistent '
          'with the Restaurant Partner Agreement.',
    ),
    LegalHeading(1, '12. IMPROVEMENT AND REVIEW'),
    LegalParagraph(
      'Restaurant Partners subject to a consequence may improve their metrics '
          'over subsequent Measurement Periods and request review. Zopiq will '
          'consider improvement and relevant context when reviewing standing. '
          'Nothing in this SLA limits Zopiq\'s rights under the Restaurant Partner '
          'Agreement or applicable law.',
    ),
    LegalHeading(1, '13. CHANGES TO THIS SLA'),
    LegalParagraph(
      'Zopiq may update this SLA and its thresholds prospectively to reflect '
          'operational needs, with reasonable notice to Restaurant Partners. '
          'Continued participation after the effective date constitutes acceptance '
          'of the updated SLA.',
    ),
    LegalHeading(1, '14. CONTACT INFORMATION'),
    LegalParagraph(
      'For questions, requests, or concerns relating to this document, please '
          'contact:',
    ),
    LegalParagraph(
      'Hybrid Monks LLP',
    ),
    LegalParagraph(
      'Brand: Zopiq',
    ),
    LegalParagraph(
      'Registered Office: C/O Meena Dev, Main Road, Sadri, Rajasthan – 306702, '
          'India',
    ),
    LegalParagraph(
      'Email: hello@hybridmonks.com',
    ),
    LegalParagraph(
      'Phone: +91 96608 77411',
    ),
    LegalParagraph(
      'GSTIN: 08AATFH7649R1Z2',
    ),
  ],
);
