// GENERATED BY tool/import_legal.mjs — DO NOT EDIT.
// Source: legal/source/12_Payment_and_Settlement_Policy.docx
//
// Edit the Word document, run `node tool/import_legal.mjs`, commit both.
import 'package:zopiq_legal/src/legal_document.dart';

const LegalDocument paymentAndSettlementPolicy = LegalDocument(
  slug: 'payment-and-settlement-policy',
  title: 'Payment & Settlement Policy',
  subtitle: 'Payments, Refunds, Settlements, and Payouts',
  docId: 'ZOPIQ-LEGAL-12',
  version: '1.0',
  effectiveDate: '18 August 2026',
  group: 'orders',
  audiences: <LegalAudience>{LegalAudience.restaurant, LegalAudience.rider},
  requiresConsent: false,
  blocks: <LegalBlock>[
    LegalHeading(1, 'Document Control & Version History'),
    LegalParagraph(
      'This document is maintained under version control. Any material '
          'amendment will be recorded in the table below and reflected in the '
          'version number and effective date on the cover page.',
    ),
    LegalTable(
      headers: <String>['Version', 'Date', 'Summary of Changes', 'Approved By'],
      rows: <List<String>>[
        <String>['1.0', '18 August 2026', 'Initial publication-ready version.', 'Hybrid Monks LLP'],
      ],
    ),
    LegalHeading(1, '1. INTRODUCTION'),
    LegalParagraph(
      'This Payment & Settlement Policy ("Policy") explains how payments, '
          'refunds, settlements, and payouts work on the Zopiq platform, operated '
          'by Hybrid Monks LLP ("Zopiq", "Company", "we", "our", or "us"). It '
          'applies to Customers, Restaurant Partners, and Delivery Partners, and '
          'supplements the Terms & Conditions, Refund & Cancellation Policy, and '
          'Partner Agreements.',
    ),
    LegalHeading(1, '2. DEFINITIONS'),
    LegalParagraph(
      'Advance Payment means the mandatory 40% of the total order value paid '
          'online before confirmation of a COD order.',
    ),
    LegalParagraph(
      'COD means Cash on Delivery, where the Customer pays the Advance Payment '
          'online and the balance on delivery.',
    ),
    LegalParagraph(
      'Commission means the platform fee payable to Zopiq in respect of items '
          'sold, being ₹10 per item unless otherwise agreed in writing.',
    ),
    LegalParagraph(
      'Settlement means the amount payable to a Restaurant Partner after '
          'applicable deductions.',
    ),
    LegalParagraph(
      'Payout means the amount payable to a Delivery Partner after applicable '
          'deductions.',
    ),
    LegalParagraph(
      'Reconciliation means the process of verifying transactions before '
          'Settlement or Payout.',
    ),
    LegalHeading(1, '3. PAYMENT METHODS'),
    LegalParagraph(
      'Zopiq supports electronic payment methods including UPI, debit cards, '
          'credit cards, net banking, and other options made available on the '
          'Platform. Cash on Delivery is available only where offered by Zopiq. '
          'Payment processing is handled by authorised third-party payment service '
          'providers; Zopiq does not store complete card or UPI PIN credentials and '
          'is not responsible for failures, delays, or errors caused by external '
          'payment systems.',
    ),
    LegalHeading(1, '4. CUSTOMER PAYMENT STRUCTURE'),
    LegalHeading(2, '4.1 40% Advance Payment'),
    LegalParagraph(
      'For every COD order, the Customer pays 40% of the total order value '
          'online as an Advance Payment before the order is confirmed. An order '
          'requiring an Advance Payment is not confirmed until the required amount '
          'has been successfully received.',
    ),
    LegalHeading(2, '4.2 60% on Delivery'),
    LegalParagraph(
      'The remaining 60% is paid in cash, or by another accepted method, upon '
          'successful delivery, if permitted by the Platform. Where a balance is '
          'due at delivery, the Customer must pay it before taking possession of '
          'the order, unless another arrangement is expressly permitted.',
    ),
    LegalHeading(2, '4.3 Non-Refundable Advance'),
    LegalParagraph(
      'Where a COD order fails due to Customer fault — refusal, unreachability, '
          'a wrong address, or abandonment after preparation — the 40% Advance '
          'Payment is non-refundable, as set out in the Refund & Cancellation '
          'Policy.',
    ),
    LegalHeading(2, '4.4 Prepaid Orders'),
    LegalParagraph(
      'For prepaid orders, the full amount is collected online at the time of '
          'placement, subject to the same confirmation and refund principles.',
    ),
    LegalHeading(1, '5. DELIVERY FEES'),
    LegalParagraph(
      'Delivery fees are dynamic and may vary based on distance, demand, '
          'weather (including rain), time of day (including night), availability of '
          'Delivery Partners, government restrictions, and special events. Zopiq '
          'does not guarantee fixed delivery fees, and Customers are informed of '
          'the applicable charges before confirming an order.',
    ),
    LegalHeading(1, '6. RESTAURANT COMMISSION'),
    LegalParagraph(
      'Unless otherwise agreed in writing, Zopiq charges a platform Commission '
          'of ₹10 per item sold through the Platform. Commission is deducted before '
          'Settlement. Zopiq may revise commission structures prospectively with '
          'reasonable notice to Restaurant Partners.',
    ),
    LegalHeading(1, '7. RESTAURANT SETTLEMENT'),
    LegalParagraph(
      'Settlements to Restaurant Partners are processed daily, subject to '
          'Reconciliation, applicable deductions, refunds, chargebacks, and legal '
          'requirements.',
    ),
    LegalHeading(2, '7.1 Deductions'),
    LegalParagraph(
      'Settlements are net of Commission, refunds or adjustments attributable '
          'to the Restaurant Partner, and any applicable taxes or statutory '
          'deductions.',
    ),
    LegalHeading(2, '7.2 Settlement Reports'),
    LegalParagraph(
      'Settlement reports are made available through the Restaurant Partner '
          'Application or dashboard, so Restaurant Partners can review amounts and '
          'deductions.',
    ),
    LegalHeading(2, '7.3 Withholding'),
    LegalParagraph(
      'Zopiq may withhold or adjust Settlements where fraud, duplicate '
          'transactions, or policy violations are reasonably suspected, pending '
          'Investigation and subject to applicable law.',
    ),
    LegalHeading(1, '8. DELIVERY PARTNER PAYOUTS'),
    LegalParagraph(
      'Payouts to Delivery Partners are processed daily, subject to '
          'verification of completed deliveries and applicable deductions or '
          'adjustments.',
    ),
    LegalHeading(2, '8.1 Composition'),
    LegalParagraph(
      'Payouts comprise delivery fees for completed deliveries and any '
          'applicable incentives, net of applicable deductions and taxes.',
    ),
    LegalHeading(2, '8.2 Records'),
    LegalParagraph(
      'Earnings and settlement history are available in the Delivery Partner '
          'Application.',
    ),
    LegalHeading(2, '8.3 Withholding'),
    LegalParagraph(
      'Zopiq may withhold or adjust Payouts where fraud, duplicate deliveries, '
          'or policy violations are reasonably suspected, pending Investigation and '
          'subject to applicable law.',
    ),
    LegalHeading(1, '9. FAILED PAYMENTS'),
    LegalParagraph(
      'Where a payment fails or an amount is debited without a confirmed order, '
          'the amount is generally reversed by the payment provider within its '
          'standard timelines. If a reversal does not occur automatically, the '
          'Customer should contact Customer Support with the transaction reference '
          'for reconciliation. In the event of a payment processing issue affecting '
          'Settlement, Zopiq may deduct a platform processing fee of ₹10, and the '
          'remaining eligible amount is settled to the Restaurant Partner in '
          'accordance with the settlement process, subject to applicable laws and '
          'Reconciliation.',
    ),
    LegalHeading(1, '10. REFUND SETTLEMENT'),
    LegalParagraph(
      'Approved refunds are issued to the original payment method unless '
          'another method is expressly agreed, in accordance with the Refund & '
          'Cancellation Policy. Refunds or adjustments attributable to a Restaurant '
          'Partner may be deducted from that Restaurant Partner\'s Settlements. The '
          'time for a refund to reflect depends on the payment provider and the '
          'Customer\'s bank.',
    ),
    LegalHeading(1, '11. TAXES'),
    LegalParagraph(
      'Amounts may be subject to applicable taxes, including Goods and Services '
          'Tax, as required by law. Restaurant Partners and Delivery Partners are '
          'responsible for their own tax obligations arising from their activities '
          'on the Platform. Zopiq applies tax treatment and deductions as required '
          'by applicable law and makes relevant records available where '
          'appropriate.',
    ),
    LegalHeading(1, '12. RECONCILIATION'),
    LegalParagraph(
      'Before Settlements and Payouts are finalised, Zopiq reconciles '
          'transactions to verify completed orders and deliveries, apply '
          'deductions, and account for refunds and chargebacks. Reconciliation '
          'protects all parties against errors and fraud, and may cause short, '
          'reasonable delays where verification is required.',
    ),
    LegalHeading(1, '13. PAYMENT AND SETTLEMENT DISPUTES'),
    LegalParagraph(
      'Disputes relating to payments, Settlements, or Payouts should be raised '
          'through in-app support or the contact details in this Policy, with '
          'relevant order and settlement references.',
    ),
    LegalHeading(2, '13.1 Handling'),
    LegalParagraph(
      'Zopiq investigates payment and settlement disputes, may request '
          'supporting information, and communicates an outcome. Users are expected '
          'to cooperate and provide reasonably requested information.',
    ),
    LegalHeading(2, '13.2 Chargebacks'),
    LegalParagraph(
      'Customers are encouraged to contact support before initiating a '
          'chargeback. Chargeback fraud — reversing payment for a validly delivered '
          'order — is prohibited and may result in withheld settlements, '
          'suspension, or legal action.',
    ),
    LegalHeading(1, '14. SUMMARY OF KEY COMMERCIAL TERMS'),
    LegalTable(
      headers: <String>['Item', 'Term'],
      rows: <List<String>>[
        <String>['COD advance', '40% of order value, paid online before confirmation.'],
        <String>['COD balance', '60% on delivery (or another accepted method), where permitted.'],
        <String>['Non-refundable advance', 'Where COD order fails due to Customer fault.'],
        <String>['Restaurant commission', '₹10 per item sold, unless otherwise agreed in writing.'],
        <String>['Restaurant settlement', 'Daily, subject to reconciliation and deductions.'],
        <String>['Delivery payout', 'Daily, subject to verification and deductions.'],
        <String>['Delivery fee', 'Dynamic; based on distance, demand, weather, time, availability.'],
        <String>['Processing fee (settlement issue)', '₹10 may be deducted where a payment processing issue affects '
              'settlement.'],
      ],
    ),
    LegalHeading(1, '15. CHANGES TO THIS POLICY'),
    LegalParagraph(
      'Zopiq may update this Policy prospectively to reflect changes in law, '
          'payment methods, or commercial terms, with reasonable notice where '
          'appropriate. Continued use of the Platform after the effective date '
          'constitutes acceptance of the updated Policy.',
    ),
    LegalHeading(1, '16. CONTACT INFORMATION'),
    LegalParagraph(
      'For questions, requests, or concerns relating to this document, please '
          'contact:',
    ),
    LegalParagraph(
      'Hybrid Monks LLP',
    ),
    LegalParagraph(
      'Brand: Zopiq',
    ),
    LegalParagraph(
      'Registered Office: C/O Meena Dev, Main Road, Sadri, Rajasthan – 306702, '
          'India',
    ),
    LegalParagraph(
      'Email: hello@hybridmonks.com',
    ),
    LegalParagraph(
      'Phone: +91 96608 77411',
    ),
    LegalParagraph(
      'GSTIN: 08AATFH7649R1Z2',
    ),
  ],
);
