// GENERATED BY tool/import_legal.mjs — DO NOT EDIT.
// Source: legal/source/11_Platform_Safety_Policy.docx
//
// Edit the Word document, run `node tool/import_legal.mjs`, commit both.
import 'package:zopiq_legal/src/legal_document.dart';

const LegalDocument platformSafetyPolicy = LegalDocument(
  slug: 'platform-safety-policy',
  title: 'Platform Safety Policy',
  subtitle: 'Safety of Customers, Partners, and the Community',
  docId: 'ZOPIQ-LEGAL-11',
  version: '1.0',
  effectiveDate: '18 August 2026',
  group: 'conduct',
  audiences: <LegalAudience>{LegalAudience.customer, LegalAudience.restaurant, LegalAudience.rider},
  requiresConsent: false,
  blocks: <LegalBlock>[
    LegalHeading(1, 'Document Control & Version History'),
    LegalParagraph(
      'This document is maintained under version control. Any material '
          'amendment will be recorded in the table below and reflected in the '
          'version number and effective date on the cover page.',
    ),
    LegalTable(
      headers: <String>['Version', 'Date', 'Summary of Changes', 'Approved By'],
      rows: <List<String>>[
        <String>['1.0', '18 August 2026', 'Initial publication-ready version.', 'Hybrid Monks LLP'],
      ],
    ),
    LegalHeading(1, '1. INTRODUCTION'),
    LegalParagraph(
      'This Platform Safety Policy ("Policy") sets out how Zopiq, operated by '
          'Hybrid Monks LLP ("Zopiq", "Company", "we", "our", or "us"), promotes '
          'the safety of Customers, Restaurant Partners, and Delivery Partners, and '
          'how the Platform responds to safety risks, threats, and harmful conduct. '
          'It supplements the Community Guidelines, Terms & Conditions, and Partner '
          'Agreements.',
    ),
    LegalParagraph(
      'Safety is a shared responsibility. Zopiq provides tools and standards, '
          'and expects all Users to act responsibly and lawfully.',
    ),
    LegalHeading(1, '2. DEFINITIONS'),
    LegalParagraph(
      'Safety Incident means any event involving actual or threatened harm to a '
          'person, or a serious risk to safety, in connection with the Platform.',
    ),
    LegalParagraph(
      'Emergency means a situation requiring immediate action to protect life, '
          'health, or safety.',
    ),
    LegalParagraph(
      'Harmful Conduct means threats, harassment, violence, or other behaviour '
          'that endangers a person.',
    ),
    LegalHeading(1, '3. GENERAL SAFETY PRINCIPLES'),
    LegalParagraph(
      'Our safety approach is guided by the following principles:',
    ),
    LegalBullets(<String>[
        'Personal safety takes priority over completing any order or delivery.',
        'All Users are entitled to be treated without threats, violence, or '
            'harassment.',
        'Serious safety risks are escalated and, where appropriate, reported to '
            'authorities.',
        'Safety tools and reporting channels are provided within the '
            'applications.',
    ]),
    LegalHeading(1, '4. CUSTOMER SAFETY'),
    LegalParagraph(
      'Zopiq supports Customer safety through measures such as order tracking, '
          'in-app or masked communication where available, and reporting channels. '
          'Customers should provide accurate delivery details, choose safe handover '
          'points, protect their account credentials, and report any unsafe '
          'interaction with a Delivery Partner or restaurant through in-app '
          'support.',
    ),
    LegalHeading(1, '5. RESTAURANT SAFETY'),
    LegalParagraph(
      'Restaurant Partners are responsible for maintaining a safe environment '
          'for their staff and for Delivery Partners collecting orders. This '
          'includes safe pickup areas, respectful treatment of Delivery Partners, '
          'and compliance with health and safety and food safety laws. Restaurant '
          'Partners should report threats or unsafe conduct by any User to Zopiq.',
    ),
    LegalHeading(1, '6. DELIVERY PARTNER SAFETY'),
    LegalParagraph(
      'Delivery Partner safety is a priority given the nature of the work.',
    ),
    LegalHeading(2, '6.1 Safe Practices'),
    LegalBullets(<String>[
        'Obey traffic laws, wear a helmet and required safety gear, and avoid '
            'fatigue.',
        'Never work under the influence of alcohol or drugs.',
        'Be cautious at unfamiliar or poorly lit locations, especially at '
            'night.',
        'Use in-app safety features and reporting channels where available.',
    ]),
    LegalHeading(2, '6.2 Right to Decline Unsafe Situations'),
    LegalParagraph(
      'Delivery Partners should not put themselves at risk to complete a '
          'delivery. Where a location or situation is unsafe, they should follow '
          'the app\'s process for unsafe situations and contact support.',
    ),
    LegalHeading(1, '7. FOOD SAFETY'),
    LegalParagraph(
      'Food safety is primarily the responsibility of Restaurant Partners, who '
          'must comply with applicable food safety laws, maintain hygiene, use '
          'fresh ingredients, and package food securely. Delivery Partners must '
          'handle sealed orders carefully and never tamper with or consume food. '
          'Zopiq does not prepare food and does not inspect or guarantee food '
          'quality, but takes food-safety complaints seriously and investigates '
          'reports of unsafe, contaminated, or spoiled food.',
    ),
    LegalHeading(1, '8. THREATS, HARASSMENT, AND VIOLENCE'),
    LegalParagraph(
      'Zopiq has zero tolerance for threats, harassment, and violence.',
    ),
    LegalHeading(2, '8.1 Prohibited Conduct'),
    LegalParagraph(
      'Prohibited conduct includes threats of harm, intimidation, stalking, '
          'sexual harassment, hate speech, physical violence, and any conduct that '
          'endangers another person. This applies to all interactions connected '
          'with the Platform.',
    ),
    LegalHeading(2, '8.2 Response'),
    LegalParagraph(
      'Reports of threats, harassment, or violence are treated with priority. '
          'Zopiq may suspend or terminate accounts immediately where necessary to '
          'protect safety, preserve relevant information, and report serious '
          'matters to law enforcement.',
    ),
    LegalHeading(1, '9. ILLEGAL PRODUCTS AND ACTIVITIES'),
    LegalParagraph(
      'The Platform must not be used to order, list, sell, or distribute '
          'prohibited or illegal items, including alcoholic beverages (where not '
          'permitted), tobacco and nicotine products, illegal drugs or controlled '
          'substances, weapons, explosives, hazardous chemicals, counterfeit goods, '
          'and stolen property. Zopiq may remove listings, suspend or terminate '
          'accounts, and report unlawful activity to authorities.',
    ),
    LegalHeading(1, '10. EMERGENCY RESPONSE'),
    LegalParagraph(
      'In an Emergency, personal safety comes first.',
    ),
    LegalHeading(2, '10.1 Immediate Steps'),
    LegalParagraph(
      'Any person facing an Emergency should contact local emergency services '
          'where appropriate, move to safety, and use any in-app safety or SOS '
          'features that are available. Users should inform Zopiq support as soon '
          'as it is safe to do so.',
    ),
    LegalHeading(2, '10.2 Zopiq\'s Role'),
    LegalParagraph(
      'On becoming aware of a Safety Incident, Zopiq will take reasonable steps '
          'to support affected Users, manage the affected order or delivery, '
          'preserve relevant information, and cooperate with authorities where '
          'required by law. Zopiq is an intermediary and cannot guarantee '
          'prevention of all incidents, but is committed to responding responsibly.',
    ),
    LegalHeading(1, '11. REPORTING SAFETY CONCERNS'),
    LegalParagraph(
      'Users can report safety concerns through in-app support, email to '
          'hello@hybridmonks.com, or phone at +91 96608 77411. Reports should '
          'include relevant details such as the order reference, location, and a '
          'description of the concern. Safety reports are prioritised and handled '
          'sensitively, consistent with the Privacy Policy.',
    ),
    LegalHeading(1, '12. CHANGES TO THIS POLICY'),
    LegalParagraph(
      'Zopiq may update this Policy from time to time to reflect changes in '
          'law, operations, or safety practices. Material changes will be '
          'communicated through the Platform or by other reasonable means. The '
          '"Last Updated" date on the cover page indicates the latest version.',
    ),
    LegalHeading(1, '13. CONTACT INFORMATION'),
    LegalParagraph(
      'For questions, requests, or concerns relating to this document, please '
          'contact:',
    ),
    LegalParagraph(
      'Hybrid Monks LLP',
    ),
    LegalParagraph(
      'Brand: Zopiq',
    ),
    LegalParagraph(
      'Registered Office: C/O Meena Dev, Main Road, Sadri, Rajasthan – 306702, '
          'India',
    ),
    LegalParagraph(
      'Email: hello@hybridmonks.com',
    ),
    LegalParagraph(
      'Phone: +91 96608 77411',
    ),
    LegalParagraph(
      'GSTIN: 08AATFH7649R1Z2',
    ),
  ],
);
