// GENERATED BY tool/import_legal.mjs — DO NOT EDIT.
// Source: legal/source/Zopiq_Privacy_Policy.docx
//
// Edit the Word document, run `node tool/import_legal.mjs`, commit both.
import 'package:zopiq_legal/src/legal_document.dart';

const LegalDocument privacyPolicy = LegalDocument(
  slug: 'privacy-policy',
  title: 'Zopiq Privacy Policy',
  subtitle: null,
  docId: null,
  version: '1.0',
  effectiveDate: '18 August 2026',
  group: 'core',
  audiences: <LegalAudience>{LegalAudience.customer, LegalAudience.restaurant, LegalAudience.rider},
  requiresConsent: true,
  blocks: <LegalBlock>[
    LegalHeading(1, '1. INTRODUCTION'),
    LegalParagraph(
      'Welcome to Zopiq, a food ordering and delivery platform owned and '
          'operated by Hybrid Monks LLP ("Hybrid Monks", "Zopiq", "Company", "we", '
          '"our", or "us").',
    ),
    LegalParagraph(
      'At Zopiq, we value your privacy and are committed to protecting your '
          'personal information. This Privacy Policy explains how we collect, use, '
          'store, disclose, retain, and protect personal data when you use:',
    ),
    LegalBullets(<String>[
        'Zopiq Customer App',
        'Zopiq Restaurant Partner App',
        'Zopiq Delivery Partner App',
        'Website',
        'APIs',
        'Customer Support Services',
        'Other services provided by Hybrid Monks LLP',
    ]),
    LegalParagraph(
      'This Privacy Policy is prepared considering the Digital Personal Data '
          'Protection Act, 2023 (India), the Information Technology Act, 2000, and '
          'other applicable Indian laws.',
    ),
    LegalParagraph(
      'By creating an account or using Zopiq, you acknowledge that you have '
          'read and understood this Privacy Policy.',
    ),
    LegalHeading(1, '2. WHO WE ARE'),
    LegalParagraph(
      'Platform Owner',
    ),
    LegalParagraph(
      'Hybrid Monks LLP',
    ),
    LegalParagraph(
      'Registered Office',
    ),
    LegalParagraph(
      'C/O Meena Dev',
    ),
    LegalParagraph(
      'Main Road',
    ),
    LegalParagraph(
      'Sadri',
    ),
    LegalParagraph(
      'Rajasthan – 306702',
    ),
    LegalParagraph(
      'India',
    ),
    LegalParagraph(
      'Email: hello@hybridmonks.com',
    ),
    LegalParagraph(
      'Phone: +91 96608 77411',
    ),
    LegalParagraph(
      'GSTIN: 08AATFH7649R1Z2',
    ),
    LegalHeading(1, '3. SCOPE OF THIS POLICY'),
    LegalParagraph(
      'This Privacy Policy applies to:',
    ),
    LegalBullets(<String>[
        'Customers',
        'Restaurant Partners',
        'Restaurant Owners',
        'Restaurant Employees',
        'Delivery Partners',
        'Website Visitors',
        'Customer Support Users',
        'Applicants using Platform Services',
    ]),
    LegalParagraph(
      'This policy applies regardless of the device used, including:',
    ),
    LegalBullets(<String>[
        'Android',
        'iPhone',
        'Tablets',
        'Desktop browsers',
        'Web applications',
    ]),
    LegalHeading(1, '4. DEFINITIONS'),
    LegalParagraph(
      'Personal Data',
    ),
    LegalParagraph(
      'Any information that identifies or can reasonably identify an '
          'individual.',
    ),
    LegalParagraph(
      'Examples include:',
    ),
    LegalBullets(<String>[
        'Name',
        'Mobile number',
        'Email',
        'Delivery address',
        'GPS location',
        'Government-issued identification (where required)',
        'Payment-related information',
        'Device identifiers',
    ]),
    LegalParagraph(
      'Processing',
    ),
    LegalParagraph(
      'Any operation performed on Personal Data, including:',
    ),
    LegalBullets(<String>[
        'Collection',
        'Recording',
        'Storage',
        'Modification',
        'Analysis',
        'Sharing',
        'Deletion',
        'Destruction',
    ]),
    LegalParagraph(
      'User',
    ),
    LegalParagraph(
      'Any Customer, Restaurant Partner, Delivery Partner, or visitor using the '
          'Platform.',
    ),
    LegalHeading(1, '5. INFORMATION WE COLLECT'),
    LegalParagraph(
      'We collect information directly from users, automatically through '
          'devices, and from trusted third parties where permitted by law.',
    ),
    LegalParagraph(
      'The categories of information collected vary depending on the type of '
          'user.',
    ),
    LegalHeading(1, '6. INFORMATION COLLECTED FROM CUSTOMERS'),
    LegalParagraph(
      'When a Customer creates an account or places an order, Zopiq may '
          'collect:',
    ),
    LegalParagraph(
      'Identity Information',
    ),
    LegalBullets(<String>[
        'Full name',
        'Mobile number',
        'Email address',
        'Profile photograph (optional)',
    ]),
    LegalParagraph(
      'Delivery Information',
    ),
    LegalBullets(<String>[
        'Delivery address',
        'Saved addresses',
        'Landmark information',
        'Apartment or building details',
        'Delivery instructions',
    ]),
    LegalParagraph(
      'Account Information',
    ),
    LegalBullets(<String>[
        'Username',
        'Password (stored securely in hashed form where applicable)',
        'Login activity',
        'Verification status',
    ]),
    LegalParagraph(
      'Order Information',
    ),
    LegalBullets(<String>[
        'Restaurant selected',
        'Food items ordered',
        'Quantity',
        'Price',
        'Coupons applied',
        'Payment method',
        'Order history',
        'Delivery status',
        'Refund history',
    ]),
    LegalParagraph(
      'Customer Support Information',
    ),
    LegalParagraph(
      'If you contact support, we may collect:',
    ),
    LegalBullets(<String>[
        'Complaint details',
        'Chat history',
        'Call recordings (where legally permitted and with notice where '
            'required)',
        'Emails',
        'Screenshots you voluntarily provide',
    ]),
    LegalHeading(1, '7. INFORMATION COLLECTED FROM RESTAURANT PARTNERS'),
    LegalParagraph(
      'Restaurant Partners may provide:',
    ),
    LegalParagraph(
      'Business Information',
    ),
    LegalBullets(<String>[
        'Restaurant name',
        'Business address',
        'Owner details',
        'Contact numbers',
        'Email address',
    ]),
    LegalParagraph(
      'Legal Information',
    ),
    LegalBullets(<String>[
        'GST Number',
        'FSSAI Licence Number',
        'PAN (if required)',
        'Bank account details',
        'Business registration details',
    ]),
    LegalParagraph(
      'Restaurant Operations',
    ),
    LegalBullets(<String>[
        'Menu',
        'Pricing',
        'Item availability',
        'Operating hours',
        'Images',
        'Promotional offers',
    ]),
    LegalParagraph(
      'Financial Information',
    ),
    LegalBullets(<String>[
        'Settlement account details',
        'Daily payout information',
        'Commission deductions',
        'Tax invoices',
    ]),
    LegalHeading(1, '8. INFORMATION COLLECTED FROM DELIVERY PARTNERS'),
    LegalParagraph(
      'Delivery Partners may provide:',
    ),
    LegalParagraph(
      'Personal Information',
    ),
    LegalBullets(<String>[
        'Full name',
        'Phone number',
        'Email',
        'Residential address',
        'Date of birth',
    ]),
    LegalParagraph(
      'Identity Verification',
    ),
    LegalBullets(<String>[
        'Government-issued identity document (where required)',
        'Selfie or verification photograph (where applicable)',
        'Driving licence (where applicable)',
    ]),
    LegalParagraph(
      'Vehicle Information',
    ),
    LegalBullets(<String>[
        'Vehicle type',
        'Registration number',
        'Insurance details (if required)',
        'Other legally required documents',
    ]),
    LegalParagraph(
      'Earnings Information',
    ),
    LegalBullets(<String>[
        'Daily earnings',
        'Bank account details',
        'UPI ID (if provided)',
        'Settlement history',
        'Incentive records',
    ]),
    LegalHeading(1, '9. PAYMENT INFORMATION'),
    LegalParagraph(
      'Payments are processed through authorized third-party payment service '
          'providers.',
    ),
    LegalParagraph(
      'Depending on the payment method, we may receive limited information such '
          'as:',
    ),
    LegalBullets(<String>[
        'Payment status',
        'Transaction reference number',
        'Payment method',
        'Amount paid',
        'Refund status',
    ]),
    LegalParagraph(
      'Zopiq does not store complete debit card, credit card, or UPI PIN '
          'credentials.',
    ),
    LegalParagraph(
      'Sensitive payment information is handled by certified payment providers '
          'in accordance with applicable standards.',
    ),
    LegalHeading(1, '10. DEVICE INFORMATION'),
    LegalParagraph(
      'When you use the Platform, we may automatically collect technical '
          'information, including:',
    ),
    LegalBullets(<String>[
        'Device model',
        'Operating system',
        'App version',
        'Browser type',
        'Language settings',
        'IP address',
        'Device identifiers',
        'Crash logs',
        'Performance logs',
        'Network information',
    ]),
    LegalParagraph(
      'This information helps us maintain security, improve performance, and '
          'diagnose technical issues.',
    ),
    LegalHeading(1, '11. LOCATION INFORMATION'),
    LegalHeading(2, 'Customers'),
    LegalParagraph(
      'With your permission, Zopiq may access your location to:',
    ),
    LegalBullets(<String>[
        'Display nearby restaurants',
        'Estimate delivery charges',
        'Improve address accuracy',
        'Provide order tracking',
    ]),
    LegalParagraph(
      'Location access is optional; however, certain features may not function '
          'correctly without it.',
    ),
    LegalHeading(2, 'Delivery Partners'),
    LegalParagraph(
      'Delivery Partners are required to share real-time location while:',
    ),
    LegalBullets(<String>[
        'Online for deliveries',
        'Travelling to pickup locations',
        'Delivering active orders',
    ]),
    LegalParagraph(
      'This enables order assignment, navigation, customer tracking, and safety '
          'features.',
    ),
    LegalParagraph(
      'Location tracking generally stops when the Delivery Partner goes '
          'offline, except where limited background processing is necessary for '
          'completing active deliveries or complying with applicable law.',
    ),
    LegalHeading(2, 'Restaurant Partners'),
    LegalParagraph(
      'Restaurants may share business location information to:',
    ),
    LegalBullets(<String>[
        'Display restaurant locations',
        'Estimate delivery zones',
        'Improve logistics',
    ]),
    LegalHeading(1, '12. COOKIES AND SIMILAR TECHNOLOGIES'),
    LegalParagraph(
      'Our website and certain Platform services may use cookies and similar '
          'technologies to:',
    ),
    LegalBullets(<String>[
        'Keep users signed in',
        'Remember preferences',
        'Improve security',
        'Measure performance',
        'Detect fraud',
        'Analyze usage trends',
    ]),
    LegalParagraph(
      'Users may manage cookie preferences through their browser settings. '
          'Disabling cookies may affect certain website features.',
    ),
    LegalHeading(1, '13. INFORMATION FROM THIRD PARTIES'),
    LegalParagraph(
      'We may receive information from trusted third parties such as:',
    ),
    LegalBullets(<String>[
        'Payment gateways (payment status)',
        'Mapping and navigation providers',
        'Identity verification providers (where applicable)',
        'Customer support platforms',
        'Fraud prevention services',
    ]),
    LegalParagraph(
      'We use such information only for purposes consistent with this Privacy '
          'Policy and applicable law.',
    ),
    LegalHeading(1, '14. HOW WE USE YOUR PERSONAL DATA'),
    LegalParagraph(
      'Zopiq collects and processes personal data only for legitimate business '
          'purposes, to provide Platform services, comply with legal obligations, '
          'and improve the user experience.',
    ),
    LegalParagraph(
      'Depending on your role (Customer, Restaurant Partner, or Delivery '
          'Partner), we may use your information to:',
    ),
    LegalHeading(2, '14.1 Provide Platform Services'),
    LegalBullets(<String>[
        'Create and manage your account.',
        'Authenticate your identity.',
        'Process food orders.',
        'Assign Delivery Partners.',
        'Enable Restaurant Partners to receive and fulfill orders.',
        'Facilitate deliveries.',
        'Process settlements and payouts.',
        'Provide customer support.',
    ]),
    LegalHeading(2, '14.2 Improve the Platform'),
    LegalParagraph(
      'We may analyze usage information to:',
    ),
    LegalBullets(<String>[
        'Improve app performance.',
        'Fix bugs and technical issues.',
        'Optimize restaurant recommendations.',
        'Improve delivery routing.',
        'Enhance search functionality.',
        'Develop new features and services.',
    ]),
    LegalParagraph(
      'Where practical, analytics are performed using aggregated or '
          'de-identified data.',
    ),
    LegalHeading(2, '14.3 Fraud Prevention and Security'),
    LegalParagraph(
      'We may use information to:',
    ),
    LegalBullets(<String>[
        'Detect fake accounts.',
        'Prevent payment fraud.',
        'Identify suspicious order patterns.',
        'Prevent coupon or referral abuse.',
        'Detect unauthorized access.',
        'Investigate chargebacks.',
        'Protect Restaurant Partners, Delivery Partners, Customers, and the '
            'Platform.',
    ]),
    LegalHeading(2, '14.4 Communication'),
    LegalParagraph(
      'We may contact users regarding:',
    ),
    LegalBullets(<String>[
        'Order confirmations.',
        'Delivery updates.',
        'OTP verification.',
        'Password resets.',
        'Security alerts.',
        'Policy updates.',
        'Customer support.',
        'Settlement notifications.',
        'Restaurant operational alerts.',
    ]),
    LegalHeading(2, '14.5 Legal Compliance'),
    LegalParagraph(
      'We may process information to:',
    ),
    LegalBullets(<String>[
        'Comply with applicable laws.',
        'Respond to lawful government requests.',
        'Meet tax and accounting obligations.',
        'Prevent unlawful activities.',
        'Enforce our agreements.',
    ]),
    LegalHeading(1, '15. LEGAL BASIS FOR PROCESSING'),
    LegalParagraph(
      'Where required under applicable law, we process personal data on one or '
          'more of the following grounds:',
    ),
    LegalBullets(<String>[
        'Your consent.',
        'Performance of a contract (for example, fulfilling your food order or '
            'processing restaurant settlements).',
        'Compliance with legal obligations.',
        'Legitimate business interests, provided such interests do not override '
            'your rights.',
        'Protection of vital interests where necessary.',
    ]),
    LegalParagraph(
      'You may withdraw consent for certain processing activities where consent '
          'is the legal basis, subject to legal or contractual limitations and the '
          'continued ability to provide the relevant service.',
    ),
    LegalHeading(1, '16. HOW WE SHARE YOUR INFORMATION'),
    LegalParagraph(
      'We do not sell your personal data.',
    ),
    LegalParagraph(
      'We share personal information only where necessary to operate the '
          'Platform or comply with legal obligations.',
    ),
    LegalHeading(2, '16.1 Restaurant Partners'),
    LegalParagraph(
      'When you place an order, the Restaurant Partner receives information '
          'necessary to prepare and fulfill it, such as:',
    ),
    LegalBullets(<String>[
        'Your name (or first name, where appropriate).',
        'Delivery address.',
        'Contact number.',
        'Ordered items.',
        'Delivery instructions.',
    ]),
    LegalParagraph(
      'Restaurant Partners must use this information only for fulfilling orders '
          'and related customer service.',
    ),
    LegalHeading(2, '16.2 Delivery Partners'),
    LegalParagraph(
      'Delivery Partners receive only the information reasonably necessary to '
          'complete a delivery, including:',
    ),
    LegalBullets(<String>[
        'Customer name.',
        'Delivery address.',
        'Contact number.',
        'Delivery instructions.',
        'Order details relevant to delivery.',
    ]),
    LegalParagraph(
      'Delivery Partners are prohibited from using customer information for '
          'personal purposes or retaining it beyond what is necessary to complete '
          'the delivery and resolve legitimate disputes.',
    ),
    LegalHeading(2, '16.3 Payment Service Providers'),
    LegalParagraph(
      'Payments are processed through authorized third-party providers.',
    ),
    LegalParagraph(
      'Payment providers may receive information such as:',
    ),
    LegalBullets(<String>[
        'Transaction amount.',
        'Payment method.',
        'Payment reference.',
        'Refund request.',
        'Merchant information.',
    ]),
    LegalParagraph(
      'Their handling of payment data is governed by their own privacy policies '
          'and applicable payment security standards.',
    ),
    LegalHeading(2, '16.4 Technology Service Providers'),
    LegalParagraph(
      'We may share limited information with service providers that assist us '
          'in operating the Platform, including:',
    ),
    LegalBullets(<String>[
        'Cloud hosting providers.',
        'Mapping and navigation services.',
        'Notification providers.',
        'SMS and email providers.',
        'Customer support systems.',
        'Security monitoring providers.',
        'Analytics providers.',
    ]),
    LegalParagraph(
      'These providers are required to process information only on our '
          'instructions and implement appropriate security measures.',
    ),
    LegalHeading(2, '16.5 Corporate Transactions'),
    LegalParagraph(
      'If Hybrid Monks LLP undergoes a merger, acquisition, investment, '
          'restructuring, or sale of assets, personal data may be transferred as '
          'part of that transaction, subject to applicable law and appropriate '
          'safeguards.',
    ),
    LegalHeading(2, '16.6 Legal and Regulatory Disclosures'),
    LegalParagraph(
      'We may disclose information where required to:',
    ),
    LegalBullets(<String>[
        'Comply with applicable laws.',
        'Respond to lawful requests from courts or government authorities.',
        'Enforce our Terms and Conditions.',
        'Protect the rights, safety, or property of users or the Platform.',
        'Prevent fraud or criminal activity.',
    ]),
    LegalParagraph(
      'We will limit disclosures to what is reasonably necessary unless a '
          'broader disclosure is legally required.',
    ),
    LegalHeading(1, '17. MARKETING COMMUNICATIONS'),
    LegalParagraph(
      'With your consent where required by law, Zopiq may send:',
    ),
    LegalBullets(<String>[
        'Promotional offers.',
        'Discount coupons.',
        'New restaurant announcements.',
        'Feature updates.',
        'Referral programs.',
        'Surveys and feedback requests.',
    ]),
    LegalParagraph(
      'You may opt out of marketing communications at any time through the app '
          'settings, the unsubscribe link in emails, or by contacting Customer '
          'Support.',
    ),
    LegalParagraph(
      'Even if you opt out of marketing, we may still send service-related '
          'communications such as order updates, security notices, and legal or '
          'policy changes.',
    ),
    LegalHeading(1, '18. ANALYTICS AND PLATFORM IMPROVEMENT'),
    LegalParagraph(
      'We use analytics tools to better understand how the Platform is used and '
          'to improve performance.',
    ),
    LegalParagraph(
      'Analytics may include information such as:',
    ),
    LegalBullets(<String>[
        'Device type.',
        'Operating system.',
        'App version.',
        'Screen interactions.',
        'Session duration.',
        'Crash reports.',
        'Feature usage.',
        'Approximate location (where appropriate).',
    ]),
    LegalParagraph(
      'Where possible, analytics are performed using aggregated or '
          'de-identified information.',
    ),
    LegalHeading(1, '19. PAYMENT SECURITY'),
    LegalParagraph(
      'Although payment processing is handled by third-party providers, Zopiq '
          'implements measures to help protect transaction integrity, including:',
    ),
    LegalBullets(<String>[
        'Secure transmission of payment requests.',
        'Verification of payment status.',
        'Fraud monitoring.',
        'Order verification for suspicious transactions.',
    ]),
    LegalParagraph(
      'Customers are responsible for ensuring that payment information provided '
          'to payment service providers is accurate and authorized.',
    ),
    LegalHeading(1, '20. PUSH NOTIFICATIONS'),
    LegalParagraph(
      'The Platform may send push notifications for:',
    ),
    LegalBullets(<String>[
        'Order status.',
        'Delivery tracking.',
        'Account security.',
        'Support updates.',
        'Restaurant alerts.',
        'Delivery assignments (Delivery Partners).',
        'Settlement notifications (Restaurant and Delivery Partners).',
    ]),
    LegalParagraph(
      'You can manage most push notification preferences through your device '
          'settings or within the app, although certain essential service '
          'notifications may remain necessary for core Platform functionality.',
    ),
    LegalHeading(1, '21. BUSINESS INSIGHTS'),
    LegalParagraph(
      'To improve restaurant performance, Zopiq may provide Restaurant Partners '
          'with aggregated operational insights such as:',
    ),
    LegalBullets(<String>[
        'Order volumes.',
        'Peak ordering times.',
        'Average preparation times.',
        'Customer ratings.',
        'Delivery performance.',
    ]),
    LegalParagraph(
      'These reports are designed to help Restaurant Partners improve service '
          'quality and do not intentionally disclose unrelated users\' personal '
          'information.',
    ),
    LegalHeading(1, '22. DATA SECURITY'),
    LegalParagraph(
      'Zopiq is committed to protecting personal data against unauthorized '
          'access, alteration, disclosure, loss, or destruction.',
    ),
    LegalParagraph(
      'We implement administrative, technical, and organizational safeguards '
          'appropriate to the nature of the information we process.',
    ),
    LegalParagraph(
      'These safeguards may include:',
    ),
    LegalBullets(<String>[
        'Encryption of data in transit using industry-standard protocols.',
        'Encryption of sensitive stored data where appropriate.',
        'Secure authentication mechanisms.',
        'Password hashing using industry-standard cryptographic algorithms.',
        'Multi-factor authentication for administrative systems where '
            'appropriate.',
        'Access controls based on job responsibilities.',
        'Network monitoring and intrusion detection measures.',
        'Regular security updates and vulnerability management.',
        'Audit logging for critical system activities.',
        'Periodic backup and disaster recovery procedures.',
    ]),
    LegalParagraph(
      'While we strive to protect your information, no method of electronic '
          'transmission or storage is completely secure. Accordingly, we cannot '
          'guarantee absolute security.',
    ),
    LegalParagraph(
      'Users are responsible for maintaining the confidentiality of their login '
          'credentials and should notify Zopiq immediately if they suspect '
          'unauthorized access to their account.',
    ),
    LegalHeading(1, '23. DATA RETENTION'),
    LegalParagraph(
      'We retain personal data only for as long as necessary to:',
    ),
    LegalBullets(<String>[
        'Provide Platform services.',
        'Fulfil contractual obligations.',
        'Resolve disputes.',
        'Prevent fraud.',
        'Meet legal, accounting, tax, and regulatory requirements.',
        'Enforce our agreements.',
    ]),
    LegalParagraph(
      'The retention period depends on the type of information and the purpose '
          'for which it was collected.',
    ),
    LegalParagraph(
      'Examples include:',
    ),
    LegalTable(
      headers: <String>['Data Category', 'Typical Retention Purpose'],
      rows: <List<String>>[
        <String>['Account information', 'While the account is active and for a reasonable period thereafter '
              'as required by law or legitimate business purposes.'],
        <String>['Order history', 'Customer support, dispute resolution, tax, accounting, and legal '
              'compliance.'],
        <String>['Payment records', 'Accounting, tax compliance, fraud prevention, and audit '
              'requirements.'],
        <String>['Support communications', 'Quality assurance, dispute resolution, and legal compliance.'],
        <String>['Restaurant settlement records', 'Financial reporting and statutory compliance.'],
        <String>['Delivery payout records', 'Financial reporting and statutory compliance.'],
      ],
    ),
    LegalParagraph(
      'Where retention is no longer necessary, we will delete or anonymize the '
          'information unless continued retention is required or permitted by '
          'applicable law.',
    ),
    LegalHeading(1, '24. USER RIGHTS'),
    LegalParagraph(
      'Subject to applicable law, users may have the right to:',
    ),
    LegalBullets(<String>[
        'Request confirmation of whether we process their personal data.',
        'Access certain personal information held by Zopiq.',
        'Request correction of inaccurate or incomplete information.',
        'Request deletion of personal data where legally permissible.',
        'Withdraw consent where processing is based on consent.',
        'Request information about how their data has been processed.',
        'Lodge complaints regarding the handling of personal data.',
    ]),
    LegalParagraph(
      'These rights may be subject to legal limitations, including where '
          'retaining or processing information is necessary to comply with legal '
          'obligations, prevent fraud, or resolve disputes.',
    ),
    LegalParagraph(
      'Requests may be submitted through the contact details provided in this '
          'Privacy Policy.',
    ),
    LegalHeading(1, '25. CORRECTION OF INFORMATION'),
    LegalParagraph(
      'Users are responsible for keeping their information accurate and up to '
          'date.',
    ),
    LegalParagraph(
      'Many account details can be updated directly within the Platform.',
    ),
    LegalParagraph(
      'Where changes cannot be made through the app, users may contact Customer '
          'Support.',
    ),
    LegalParagraph(
      'We may request reasonable verification before making changes to protect '
          'against unauthorized modifications.',
    ),
    LegalHeading(1, '26. ACCOUNT DELETION'),
    LegalParagraph(
      'Users may request deletion of their Zopiq account at any time through '
          'the app or by contacting Customer Support.',
    ),
    LegalParagraph(
      'Before processing a deletion request, Zopiq may verify the identity of '
          'the requester.',
    ),
    LegalParagraph(
      'Deletion of an account generally results in:',
    ),
    LegalBullets(<String>[
        'Removal of access to the Platform.',
        'Deactivation of the account.',
        'Deletion or anonymization of personal data where legally permissible.',
    ]),
    LegalParagraph(
      'However, certain information may be retained where necessary to:',
    ),
    LegalBullets(<String>[
        'Comply with legal obligations.',
        'Complete pending financial settlements.',
        'Detect or prevent fraud.',
        'Resolve disputes.',
        'Maintain tax and accounting records.',
        'Enforce contractual obligations.',
    ]),
    LegalParagraph(
      'Restaurant Partners and Delivery Partners must ensure that outstanding '
          'settlements, obligations, or compliance requirements are completed '
          'before account deletion can be finalized.',
    ),
    LegalParagraph(
      'Deleted accounts may not be recoverable.',
    ),
    LegalHeading(1, '27. CHILDREN\'S PRIVACY'),
    LegalParagraph(
      'Zopiq is not intended for independent use by young children.',
    ),
    LegalParagraph(
      'Individuals under the age of 18 may use the Platform only under the '
          'supervision and with the consent of a parent or legal guardian.',
    ),
    LegalParagraph(
      'Parents and guardians are responsible for monitoring the activities of '
          'minors using the Platform.',
    ),
    LegalParagraph(
      'If we become aware that personal information has been collected from a '
          'child in violation of applicable law or this Privacy Policy, we will '
          'take reasonable steps to delete the information or otherwise comply with '
          'legal requirements.',
    ),
    LegalHeading(1, '28. INTERNATIONAL DATA TRANSFERS'),
    LegalParagraph(
      'Zopiq primarily processes information in India.',
    ),
    LegalParagraph(
      'Where personal data is transferred or accessed outside India—for '
          'example, through cloud infrastructure or service providers—we will take '
          'reasonable steps to ensure that appropriate safeguards are in place and '
          'that such transfers comply with applicable laws.',
    ),
    LegalHeading(1, '29. AUTOMATED PROCESSING'),
    LegalParagraph(
      'Zopiq may use automated systems to support operational decisions, '
          'including:',
    ),
    LegalBullets(<String>[
        'Fraud detection.',
        'Spam prevention.',
        'Order risk assessment.',
        'Coupon abuse detection.',
        'Assignment of delivery orders.',
        'Restaurant recommendations.',
        'Delivery route optimization.',
    ]),
    LegalParagraph(
      'These automated processes are intended to improve Platform security, '
          'efficiency, and user experience.',
    ),
    LegalParagraph(
      'Material decisions that significantly affect users may also involve '
          'human review where appropriate.',
    ),
    LegalHeading(1, '30. SECURITY INCIDENT RESPONSE'),
    LegalParagraph(
      'If Zopiq becomes aware of a security incident affecting personal data, '
          'we will take reasonable steps to:',
    ),
    LegalBullets(<String>[
        'Investigate the incident.',
        'Contain and mitigate the impact.',
        'Restore affected systems where possible.',
        'Comply with applicable legal reporting obligations.',
        'Notify affected users or authorities where required by law.',
    ]),
    LegalHeading(1, '31. GRIEVANCE REDRESSAL'),
    LegalParagraph(
      'If you have questions, concerns, or complaints regarding this Privacy '
          'Policy or the processing of your personal data, you may contact us using '
          'the details below.',
    ),
    LegalParagraph(
      'Privacy Contact',
    ),
    LegalParagraph(
      'Hybrid Monks LLP',
    ),
    LegalParagraph(
      'Email: hello@hybridmonks.com',
    ),
    LegalParagraph(
      'Phone: +91 96608 77411',
    ),
    LegalParagraph(
      'Address:',
    ),
    LegalParagraph(
      'C/O Meena Dev',
    ),
    LegalParagraph(
      'Main Road',
    ),
    LegalParagraph(
      'Sadri, Rajasthan – 306702',
    ),
    LegalParagraph(
      'India',
    ),
    LegalParagraph(
      'We aim to acknowledge and address privacy-related concerns within a '
          'reasonable timeframe, subject to the complexity of the request and '
          'applicable legal requirements.',
    ),
    LegalHeading(1, '32. USER RESPONSIBILITIES'),
    LegalParagraph(
      'Users are responsible for:',
    ),
    LegalBullets(<String>[
        'Providing accurate information.',
        'Keeping login credentials secure.',
        'Updating contact details when they change.',
        'Logging out from shared devices.',
        'Promptly reporting suspected unauthorized access.',
        'Using the Platform in accordance with applicable laws and the Terms & '
            'Conditions.',
    ]),
    LegalParagraph(
      'Failure to follow these responsibilities may affect our ability to '
          'provide services securely.',
    ),
    LegalHeading(1, '33. CHANGES TO THIS PRIVACY POLICY'),
    LegalParagraph(
      'Hybrid Monks LLP may update this Privacy Policy from time to time to '
          'reflect:',
    ),
    LegalBullets(<String>[
        'Changes in applicable laws or regulations.',
        'New Platform features.',
        'Security improvements.',
        'Business operations.',
        'Technology changes.',
        'User feedback.',
        'Regulatory requirements.',
    ]),
    LegalParagraph(
      'Where material changes are made, Zopiq will notify users through one or '
          'more of the following:',
    ),
    LegalBullets(<String>[
        'In-app notifications.',
        'Email (where available).',
        'Push notifications.',
        'Website notices.',
    ]),
    LegalParagraph(
      'The "Last Updated" date at the top of this Privacy Policy will always '
          'indicate the latest version.',
    ),
    LegalParagraph(
      'Your continued use of the Platform after the revised Privacy Policy '
          'becomes effective constitutes your acknowledgment of the updated policy, '
          'subject to applicable law.',
    ),
    LegalHeading(1, '34. RETENTION SCHEDULE (SUMMARY)'),
    LegalParagraph(
      'The following table provides a general overview of how Zopiq manages '
          'different categories of information. Actual retention periods may vary '
          'where longer retention is required by law or necessary for fraud '
          'prevention, dispute resolution, or legitimate business purposes.',
    ),
    LegalTable(
      headers: <String>['Data Category', 'Purpose', 'Retention Approach'],
      rows: <List<String>>[
        <String>['Account Information', 'Account management', 'Until account deletion request is processed, plus any period '
              'required by law or legitimate business needs'],
        <String>['Order History', 'Customer service, disputes, analytics', 'Retained as necessary for legal, tax, accounting, fraud prevention, '
              'and customer support purposes'],
        <String>['Payment Records', 'Financial reporting', 'Retained in accordance with applicable tax and accounting laws'],
        <String>['Restaurant Settlement Records', 'Financial reconciliation', 'Retained in accordance with applicable financial and tax obligations'],
        <String>['Delivery Partner Earnings', 'Payout processing', 'Retained in accordance with applicable financial and tax obligations'],
        <String>['Customer Support Records', 'Complaint handling', 'Retained for service quality, dispute resolution, and legal '
              'compliance'],
        <String>['Security Logs', 'Platform security', 'Retained for security monitoring and incident investigation for an '
              'appropriate period'],
        <String>['Device Information', 'Security and diagnostics', 'Retained only as long as reasonably necessary for operational and '
              'security purposes'],
        <String>['Marketing Preferences', 'Communication management', 'Until withdrawn or no longer required'],
      ],
    ),
    LegalParagraph(
      'Where information is no longer needed, Zopiq will delete it or anonymize '
          'it, unless retention is required or permitted by law.',
    ),
    LegalHeading(1, '35. COOKIE POLICY'),
    LegalParagraph(
      'When using the Zopiq website or supported web services, we may use '
          'cookies and similar technologies.',
    ),
    LegalParagraph(
      'Cookies are small text files stored on your device to improve '
          'functionality and user experience.',
    ),
    LegalParagraph(
      'We may use:',
    ),
    LegalParagraph(
      'Essential Cookies',
    ),
    LegalParagraph(
      'Required for:',
    ),
    LegalBullets(<String>[
        'User authentication.',
        'Security.',
        'Session management.',
        'Fraud prevention.',
    ]),
    LegalParagraph(
      'These cookies are necessary for the Platform to function correctly.',
    ),
    LegalParagraph(
      'Preference Cookies',
    ),
    LegalParagraph(
      'Used to remember:',
    ),
    LegalBullets(<String>[
        'Language preferences.',
        'Saved settings.',
        'Recently viewed restaurants.',
        'User interface preferences.',
    ]),
    LegalParagraph(
      'Performance Cookies',
    ),
    LegalParagraph(
      'Used to understand:',
    ),
    LegalBullets(<String>[
        'Website performance.',
        'Loading times.',
        'Feature usage.',
        'Error reporting.',
    ]),
    LegalParagraph(
      'These help us improve the Platform.',
    ),
    LegalParagraph(
      'Analytics Cookies',
    ),
    LegalParagraph(
      'Used to understand:',
    ),
    LegalBullets(<String>[
        'Visitor trends.',
        'Popular features.',
        'Device types.',
        'General usage patterns.',
    ]),
    LegalParagraph(
      'Where possible, analytics data is aggregated or de-identified.',
    ),
    LegalParagraph(
      'You can control cookies through your browser settings. Disabling certain '
          'cookies may affect the functionality of the website.',
    ),
    LegalHeading(1, '36. THIRD-PARTY LINKS'),
    LegalParagraph(
      'The Platform may contain links to third-party websites, applications, or '
          'services.',
    ),
    LegalParagraph(
      'Zopiq is not responsible for the privacy practices, content, or security '
          'of third-party platforms.',
    ),
    LegalParagraph(
      'Users should review the privacy policies of those third parties before '
          'providing personal information.',
    ),
    LegalHeading(1, '37. CONFIDENTIALITY'),
    LegalParagraph(
      'Employees, contractors, and service providers who process personal data '
          'on behalf of Zopiq are required to maintain confidentiality and may '
          'access personal data only to the extent necessary to perform their '
          'authorized duties.',
    ),
    LegalHeading(1, '38. DATA MINIMIZATION'),
    LegalParagraph(
      'Zopiq strives to collect only the personal data reasonably necessary to '
          'provide and improve the Platform, comply with legal obligations, and '
          'protect users.',
    ),
    LegalParagraph(
      'We avoid collecting unnecessary information and periodically review our '
          'data practices to support this principle.',
    ),
    LegalHeading(1, '39. PRIVACY BY DESIGN'),
    LegalParagraph(
      'When developing new features or services, Zopiq seeks to incorporate '
          'privacy and security considerations into the design process where '
          'reasonably practicable.',
    ),
    LegalParagraph(
      'This includes evaluating:',
    ),
    LegalBullets(<String>[
        'The types of data collected.',
        'The necessity of collection.',
        'Security controls.',
        'Access restrictions.',
        'Data retention needs.',
    ]),
    LegalHeading(1, '40. CROSS-APP DATA USE'),
    LegalParagraph(
      'Because Zopiq operates separate applications for Customers, Restaurant '
          'Partners, and Delivery Partners, certain information may be shared '
          'internally between these applications where necessary to:',
    ),
    LegalBullets(<String>[
        'Process orders.',
        'Coordinate deliveries.',
        'Manage settlements.',
        'Provide customer support.',
        'Prevent fraud.',
        'Maintain platform security.',
        'Comply with legal obligations.',
    ]),
    LegalParagraph(
      'Such sharing is limited to the information reasonably necessary for '
          'these purposes.',
    ),
    LegalHeading(1, '41. PRIVACY RIGHTS REQUESTS'),
    LegalParagraph(
      'Users may submit requests relating to their personal data by contacting:',
    ),
    LegalParagraph(
      'Email: hello@hybridmonks.com',
    ),
    LegalParagraph(
      'Requests may include:',
    ),
    LegalBullets(<String>[
        'Access to eligible personal information.',
        'Correction of inaccurate information.',
        'Deletion requests.',
        'Withdrawal of consent (where applicable).',
        'Questions regarding data processing.',
    ]),
    LegalParagraph(
      'To protect user privacy, Zopiq may require reasonable identity '
          'verification before processing such requests.',
    ),
    LegalHeading(1, '42. CONTACT INFORMATION'),
    LegalParagraph(
      'For privacy-related questions or concerns, please contact:',
    ),
    LegalParagraph(
      'Hybrid Monks LLP',
    ),
    LegalParagraph(
      'Brand: Zopiq',
    ),
    LegalParagraph(
      'Registered Office:',
    ),
    LegalParagraph(
      'C/O Meena Dev',
    ),
    LegalParagraph(
      'Main Road',
    ),
    LegalParagraph(
      'Sadri',
    ),
    LegalParagraph(
      'Rajasthan – 306702',
    ),
    LegalParagraph(
      'India',
    ),
    LegalParagraph(
      'Email: hello@hybridmonks.com',
    ),
    LegalParagraph(
      'Phone: +91 96608 77411',
    ),
    LegalParagraph(
      'GSTIN: 08AATFH7649R1Z2',
    ),
    LegalHeading(1, '43. POLICY HIERARCHY'),
    LegalParagraph(
      'This Privacy Policy should be read together with:',
    ),
    LegalBullets(<String>[
        'Zopiq Terms & Conditions.',
        'Account Deletion & Data Retention Policy.',
        'Restaurant Partner Agreement.',
        'Delivery Partner Agreement.',
        'Any additional policies or notices published by Zopiq.',
    ]),
    LegalParagraph(
      'If there is a conflict between this Privacy Policy and another policy '
          'regarding the handling of personal data, this Privacy Policy will govern '
          'to the extent of that conflict, unless applicable law requires '
          'otherwise.',
    ),
    LegalHeading(1, '44. SEVERABILITY'),
    LegalParagraph(
      'If any provision of this Privacy Policy is held to be invalid or '
          'unenforceable by a court or competent authority, the remaining '
          'provisions shall continue in full force and effect.',
    ),
    LegalHeading(1, '45. ENTIRE PRIVACY POLICY'),
    LegalParagraph(
      'This Privacy Policy constitutes the complete statement of Zopiq\'s '
          'practices regarding the collection, use, disclosure, storage, and '
          'protection of personal data for the Platform, subject to applicable laws '
          'and any additional notices provided for specific services.',
    ),
  ],
);
