// GENERATED BY tool/import_legal.mjs — DO NOT EDIT.
// Source: legal/source/01_Refund_and_Cancellation_Policy.docx
//
// Edit the Word document, run `node tool/import_legal.mjs`, commit both.
import 'package:zopiq_legal/src/legal_document.dart';

const LegalDocument refundAndCancellationPolicy = LegalDocument(
  slug: 'refund-and-cancellation-policy',
  title: 'Refund & Cancellation Policy',
  subtitle: 'Customer Orders, Cancellations, and Refunds',
  docId: 'ZOPIQ-LEGAL-01',
  version: '1.0',
  effectiveDate: '18 August 2026',
  group: 'orders',
  audiences: <LegalAudience>{LegalAudience.customer, LegalAudience.restaurant},
  requiresConsent: false,
  blocks: <LegalBlock>[
    LegalHeading(1, 'Document Control & Version History'),
    LegalParagraph(
      'This document is maintained under version control. Any material '
          'amendment will be recorded in the table below and reflected in the '
          'version number and effective date on the cover page.',
    ),
    LegalTable(
      headers: <String>['Version', 'Date', 'Summary of Changes', 'Approved By'],
      rows: <List<String>>[
        <String>['1.0', '18 August 2026', 'Initial publication-ready version.', 'Hybrid Monks LLP'],
      ],
    ),
    LegalHeading(1, '1. INTRODUCTION'),
    LegalParagraph(
      'This Refund & Cancellation Policy ("Policy") sets out the circumstances '
          'in which orders placed on the Zopiq platform, operated by Hybrid Monks '
          'LLP ("Zopiq", "Company", "we", "our", or "us"), may be cancelled, and '
          'the basis on which refunds are issued. It applies to all Customers and '
          'is intended to be read together with the Zopiq Terms & Conditions, '
          'Privacy Policy, and Payment & Settlement Policy, each of which forms an '
          'integral part of the arrangement between the Customer and Hybrid Monks '
          'LLP.',
    ),
    LegalParagraph(
      'Zopiq operates as a technology platform connecting Customers, Restaurant '
          'Partners, and Delivery Partners. Food is prepared by independent '
          'Restaurant Partners and delivered by independent Delivery Partners. This '
          'Policy reflects that intermediary role.',
    ),
    LegalHeading(1, '2. DEFINITIONS'),
    LegalParagraph(
      'Advance Payment means the mandatory 40% of the total order value paid '
          'online before confirmation of a Cash on Delivery order.',
    ),
    LegalParagraph(
      'Cash on Delivery (COD) means an order for which the Customer pays the '
          'Advance Payment online and the balance upon delivery.',
    ),
    LegalParagraph(
      'Order means a confirmed request placed through the Platform for food or '
          'related items.',
    ),
    LegalParagraph(
      'Prepaid Order means an order paid in full online at the time of '
          'placement.',
    ),
    LegalParagraph(
      'Restaurant Partner means a restaurant, cloud kitchen, café, food vendor, '
          'or business registered on the Platform for selling food.',
    ),
    LegalParagraph(
      'Delivery Partner means an independent individual or entity responsible '
          'for collecting and delivering Customer orders.',
    ),
    LegalHeading(1, '3. GENERAL PRINCIPLES'),
    LegalParagraph(
      'The following principles govern all cancellations and refunds under this '
          'Policy:',
    ),
    LegalBullets(<String>[
        'Refunds are issued only in accordance with this Policy and applicable '
            'law.',
        'Nothing in this Policy limits any non-waivable rights available to '
            'consumers under the Consumer Protection Act, 2019, or other applicable '
            'law.',
        'Whether a refund is due depends on the reason an order failed and the '
            'party responsible.',
        'Refund amounts and timelines depend on the payment method and the '
            'outcome of any verification or investigation.',
    ]),
    LegalHeading(1, '4. CUSTOMER CANCELLATIONS'),
    LegalHeading(2, '4.1 Before Restaurant Acceptance'),
    LegalParagraph(
      'A Customer may cancel an Order before the Restaurant Partner accepts it. '
          'Where payment has already been collected, the applicable amount will be '
          'refunded in accordance with this Policy.',
    ),
    LegalHeading(2, '4.2 After Restaurant Acceptance'),
    LegalParagraph(
      'Once a Restaurant Partner has accepted an Order, cancellation by the '
          'Customer is not permitted, because preparation may already have begun.',
    ),
    LegalHeading(2, '4.3 During Food Preparation'),
    LegalParagraph(
      'Orders cannot be cancelled once food preparation has commenced.',
    ),
    LegalHeading(2, '4.4 After Dispatch'),
    LegalParagraph(
      'Orders cannot be cancelled once assigned to a Delivery Partner or '
          'dispatched from the Restaurant.',
    ),
    LegalHeading(2, '4.5 Abuse of Cancellation'),
    LegalParagraph(
      'Zopiq reserves the right to suspend, restrict, or permanently terminate '
          'accounts that repeatedly misuse the cancellation facility or place '
          'orders without the intention to complete the purchase.',
    ),
    LegalHeading(1, '5. RESTAURANT CANCELLATIONS'),
    LegalParagraph(
      'A Restaurant Partner may cancel an Order only for genuine operational '
          'reasons, including item unavailability, kitchen malfunction, restaurant '
          'closure, a safety or health emergency, or a Force Majeure Event.',
    ),
    LegalHeading(2, '5.1 Effect on the Customer'),
    LegalParagraph(
      'Where a Restaurant Partner cancels an Order before preparation due to '
          'reasons attributable to the restaurant, the Customer will receive a '
          'refund of any amount paid, including the Advance Payment, in accordance '
          'with this Policy.',
    ),
    LegalHeading(2, '5.2 Consequences for the Restaurant'),
    LegalParagraph(
      'Restaurants shall not intentionally cancel accepted Orders to manipulate '
          'availability, pricing, ratings, or Customer experience. Repeated '
          'cancellations may result in warning notices, reduced platform '
          'visibility, temporary suspension, or permanent removal from the '
          'Platform.',
    ),
    LegalHeading(1, '6. DELIVERY FAILURES'),
    LegalParagraph(
      'A delivery may be treated as unsuccessful where the Customer refuses '
          'delivery, is unreachable, provides an incorrect or incomplete address, '
          'refuses to pay the remaining COD balance, the delivery location is '
          'unsafe, or fraud is suspected.',
    ),
    LegalHeading(2, '6.1 Delivery Failure Due to Customer Fault'),
    LegalParagraph(
      'Where delivery fails due to Customer fault, the 40% Advance Payment '
          'remains non-refundable, the Customer may be charged applicable delivery '
          'costs where permitted by law, and Zopiq may restrict future COD orders '
          'or suspend the Customer account.',
    ),
    LegalHeading(2, '6.2 Delivery Failure Not Attributable to the Customer'),
    LegalParagraph(
      'Where a delivery fails for reasons not attributable to the Customer — '
          'for example, an error by the Restaurant Partner or Delivery Partner — '
          'Zopiq will investigate and, where appropriate, arrange a refund or other '
          'suitable resolution.',
    ),
    LegalHeading(1, '7. REFUND RULES BY SCENARIO'),
    LegalParagraph(
      'The following table summarises how common scenarios are treated. Each '
          'case remains subject to verification and applicable law.',
    ),
    LegalTable(
      headers: <String>['Scenario', 'Outcome'],
      rows: <List<String>>[
        <String>['Wrong item delivered', 'Exchange or replacement where reasonably possible; no monetary '
              'refund is issued for this scenario alone. Replacement availability '
              'depends on the Restaurant Partner.'],
        <String>['Missing item(s)', 'Refund equivalent only to the value of the verified missing item(s).'],
        <String>['Damaged food', 'Partial refund after verification.'],
        <String>['Spilled food', 'Partial refund after investigation.'],
        <String>['Late delivery', 'No automatic refund where the delay is caused by traffic, weather, '
              'festivals, road closures, restaurant preparation, government '
              'restrictions, or Force Majeure.'],
        <String>['Incorrect / incomplete address', 'No refund where delivery fails because the Customer entered an '
              'incorrect or incomplete address.'],
        <String>['Failed COD order (Customer fault)', 'The 40% Advance Payment is non-refundable.'],
        <String>['Taste complaint', 'No refund merely for taste preference. Complaints of stale, unsafe, '
              'contaminated, or spoiled food are investigated individually.'],
      ],
    ),
    LegalHeading(1, '8. NON-REFUNDABLE SITUATIONS'),
    LegalParagraph(
      'Refunds will not be issued, except where required by applicable law, in '
          'the following situations:',
    ),
    LegalBullets(<String>[
        'The 40% Advance Payment on a COD order where the Customer refuses '
            'delivery, is unreachable, provides a wrong address, or otherwise '
            'causes the order to fail after preparation.',
        'Delivery delays caused by traffic, weather, festivals, road closures, '
            'restaurant preparation, government restrictions, or Force Majeure '
            'Events.',
        'Dissatisfaction based solely on personal taste preference.',
        'Failure of delivery due to an incorrect or incomplete address supplied '
            'by the Customer.',
    ]),
    LegalHeading(1, '9. PAYMENT FAILURES'),
    LegalParagraph(
      'Payment processing is handled by authorised third-party payment service '
          'providers. Zopiq does not store complete card or UPI PIN credentials and '
          'is not responsible for failures, delays, or errors caused by external '
          'payment systems.',
    ),
    LegalHeading(2, '9.1 Amounts Debited Without Order Confirmation'),
    LegalParagraph(
      'Where an amount is debited but an Order is not confirmed, the amount is '
          'generally reversed by the payment provider within the provider\'s '
          'standard processing timelines. Where a reversal does not occur '
          'automatically, the Customer should contact Customer Support with the '
          'transaction reference so the matter can be reconciled.',
    ),
    LegalHeading(2, '9.2 Advance Payment Not Received'),
    LegalParagraph(
      'For orders requiring an Advance Payment, an Order will not be confirmed '
          'until the required amount has been successfully received.',
    ),
    LegalHeading(1, '10. CHARGEBACKS'),
    LegalParagraph(
      'A chargeback is a reversal of a payment initiated through the '
          'Customer\'s bank or card issuer. Customers are encouraged to contact '
          'Zopiq Customer Support before initiating a chargeback, so that the '
          'matter can be investigated and resolved directly.',
    ),
    LegalHeading(2, '10.1 Chargeback Fraud'),
    LegalParagraph(
      'Initiating a chargeback for an Order that was validly delivered, or '
          'otherwise misusing the chargeback process, is treated as chargeback '
          'fraud. Zopiq may suspend or permanently terminate accounts engaged in '
          'chargeback fraud, withhold settlements pending investigation, and take '
          'legal action where appropriate.',
    ),
    LegalHeading(1, '11. REFUND TIMELINES AND METHOD'),
    LegalParagraph(
      'Approved refunds are issued to the original payment method used for the '
          'Order, unless another method is expressly agreed. Once a refund is '
          'approved and initiated by Zopiq, the time taken for the amount to '
          'reflect in the Customer\'s account depends on the payment provider and '
          'the Customer\'s bank.',
    ),
    LegalTable(
      headers: <String>['Payment Method', 'Typical Time to Reflect After Approval'],
      rows: <List<String>>[
        <String>['UPI', 'Usually within a few business days, subject to the payment provider '
              'and bank.'],
        <String>['Debit / Credit Card', 'Usually within a standard bank processing period after the refund is '
              'initiated.'],
        <String>['Net Banking', 'Usually within a standard bank processing period after the refund is '
              'initiated.'],
        <String>['Wallet / Platform Credit (where offered)', 'Usually reflected promptly after approval.'],
      ],
    ),
    LegalParagraph(
      'Indicative timelines are provided for convenience only and do not '
          'constitute a guarantee, as final crediting depends on third-party '
          'systems.',
    ),
    LegalHeading(1, '12. WORKED EXAMPLES'),
    LegalParagraph(
      'The following non-binding examples illustrate how this Policy operates. '
          'Actual outcomes depend on verification and the facts of each case.',
    ),
    LegalHeading(3, '12.1 Example — Missing Item'),
    LegalParagraph(
      'A Customer orders three items. On delivery, one item is missing. '
          'Following verification, the Customer receives a refund equal to the '
          'value of the single missing item; the remainder of the Order is not '
          'refunded.',
    ),
    LegalHeading(3, '12.2 Example — Customer Unreachable on a COD Order'),
    LegalParagraph(
      'A Customer places a COD Order, pays the 40% Advance Payment, and is then '
          'unreachable at delivery after reasonable attempts. The Advance Payment '
          'is forfeited and is not refunded.',
    ),
    LegalHeading(3, '12.3 Example — Restaurant Cancels Before Preparation'),
    LegalParagraph(
      'A Customer pays the Advance Payment. The Restaurant Partner then cancels '
          'before preparation due to stock unavailability. The Customer receives a '
          'full refund of the Advance Payment.',
    ),
    LegalHeading(3, '12.4 Example — Late Delivery Due to Rain'),
    LegalParagraph(
      'An Order is delivered later than the estimated time because of heavy '
          'rain and traffic. As the delay is outside anyone\'s reasonable control, '
          'no automatic refund is due.',
    ),
    LegalHeading(1, '13. FREQUENTLY ASKED QUESTIONS'),
    LegalHeading(3, '13.1 Is the 40% advance always non-refundable?'),
    LegalParagraph(
      'No. The Advance Payment is non-refundable only where the order fails due '
          'to Customer fault — for example, refusal, unreachability, a wrong '
          'address, or abandonment after preparation. Where the Restaurant Partner '
          'cancels before preparation, the Advance Payment is refunded.',
    ),
    LegalHeading(3, '13.2 I didn\'t like the taste of my food. Can I get a refund?'),
    LegalParagraph(
      'Refunds are not granted merely because of personal taste preference. '
          'However, complaints that food was stale, unsafe, contaminated, or '
          'spoiled are investigated individually.',
    ),
    LegalHeading(3, '13.3 The wrong item was delivered. Do I get my money back?'),
    LegalParagraph(
      'For a wrong item, Zopiq arranges a replacement or exchange where '
          'reasonably possible rather than a monetary refund. If items are missing, '
          'you receive a refund for the value of the verified missing item(s).',
    ),
    LegalHeading(3, '13.4 Money was deducted but I didn\'t get a confirmation. What now?'),
    LegalParagraph(
      'Amounts debited without a confirmed Order are generally reversed by the '
          'payment provider. If the amount is not reversed automatically, contact '
          'Customer Support with your transaction reference.',
    ),
    LegalHeading(3, '13.5 How long do refunds take?'),
    LegalParagraph(
      'Once approved and initiated by Zopiq, the time to reflect depends on '
          'your payment provider and bank. See Section 11 for indicative timelines.',
    ),
    LegalHeading(1, '14. CHANGES TO THIS POLICY'),
    LegalParagraph(
      'Zopiq may update this Policy from time to time to reflect changes in '
          'law, Platform features, or business operations. Material changes will be '
          'communicated through the Platform or by other reasonable means. '
          'Continued use of the Platform after the effective date of the revised '
          'Policy constitutes acceptance of the updated Policy.',
    ),
    LegalHeading(1, '15. CONTACT INFORMATION'),
    LegalParagraph(
      'For questions, requests, or concerns relating to this document, please '
          'contact:',
    ),
    LegalParagraph(
      'Hybrid Monks LLP',
    ),
    LegalParagraph(
      'Brand: Zopiq',
    ),
    LegalParagraph(
      'Registered Office: C/O Meena Dev, Main Road, Sadri, Rajasthan – 306702, '
          'India',
    ),
    LegalParagraph(
      'Email: hello@hybridmonks.com',
    ),
    LegalParagraph(
      'Phone: +91 96608 77411',
    ),
    LegalParagraph(
      'GSTIN: 08AATFH7649R1Z2',
    ),
  ],
);
