// GENERATED BY tool/import_legal.mjs — DO NOT EDIT.
// Source: legal/source/13_Restaurant_Verification_Policy.docx
//
// Edit the Word document, run `node tool/import_legal.mjs`, commit both.
import 'package:zopiq_legal/src/legal_document.dart';

const LegalDocument restaurantVerificationPolicy = LegalDocument(
  slug: 'restaurant-verification-policy',
  title: 'Restaurant Verification Policy',
  subtitle: 'Onboarding Checks and Ongoing Compliance',
  docId: 'ZOPIQ-LEGAL-13',
  version: '1.0',
  effectiveDate: '18 August 2026',
  group: 'partner',
  audiences: <LegalAudience>{LegalAudience.restaurant},
  requiresConsent: false,
  blocks: <LegalBlock>[
    LegalHeading(1, 'Document Control & Version History'),
    LegalParagraph(
      'This document is maintained under version control. Any material '
          'amendment will be recorded in the table below and reflected in the '
          'version number and effective date on the cover page.',
    ),
    LegalTable(
      headers: <String>['Version', 'Date', 'Summary of Changes', 'Approved By'],
      rows: <List<String>>[
        <String>['1.0', '18 August 2026', 'Initial publication-ready version.', 'Hybrid Monks LLP'],
      ],
    ),
    LegalHeading(1, '1. INTRODUCTION'),
    LegalParagraph(
      'This Restaurant Verification Policy ("Policy") describes how Zopiq, '
          'operated by Hybrid Monks LLP ("Zopiq", "Company", "we", "our", or "us"), '
          'verifies Restaurant Partners before and during their participation on '
          'the Platform. It supplements the Restaurant Partner Agreement, Terms & '
          'Conditions, and Privacy Policy.',
    ),
    LegalParagraph(
      'Verification protects Customers and the integrity of the Platform, and '
          'helps ensure that Restaurant Partners are legally entitled to operate a '
          'food business.',
    ),
    LegalHeading(1, '2. DEFINITIONS'),
    LegalParagraph(
      'Verification means the process of checking a Restaurant Partner\'s '
          'identity, licences, and details.',
    ),
    LegalParagraph(
      'Onboarding means the initial process of bringing a Restaurant Partner '
          'onto the Platform.',
    ),
    LegalParagraph(
      'Compliance Monitoring means ongoing checks to confirm continued '
          'eligibility.',
    ),
    LegalHeading(1, '3. PRINCIPLES'),
    LegalParagraph(
      'Verification is guided by the following principles:',
    ),
    LegalBullets(<String>[
        'Only legally registered food businesses may operate on the Platform.',
        'Documents are collected and handled under the Privacy Policy and data '
            'minimization.',
        'Verification is ongoing, not only at onboarding.',
        'Non-compliance may lead to suspension or removal.',
    ]),
    LegalHeading(1, '4. FSSAI VERIFICATION'),
    LegalParagraph(
      'Restaurant Partners must hold a valid FSSAI registration or licence '
          'appropriate to their business, where required by law. During Onboarding, '
          'the Restaurant Partner provides FSSAI details, which Zopiq may verify. A '
          'valid FSSAI registration or licence must be maintained for the duration '
          'of participation, and Zopiq may request evidence at any time.',
    ),
    LegalHeading(1, '5. GST VERIFICATION'),
    LegalParagraph(
      'Where applicable, Restaurant Partners provide GST registration details. '
          'Zopiq may verify GST details for tax, invoicing, and settlement '
          'purposes. Restaurant Partners are responsible for the accuracy of their '
          'GST information and for their own tax obligations.',
    ),
    LegalHeading(1, '6. PAN VERIFICATION'),
    LegalParagraph(
      'Where required, Restaurant Partners provide PAN details for taxation and '
          'financial-compliance purposes. PAN information is handled confidentially '
          'and used only for permitted purposes consistent with the Privacy Policy.',
    ),
    LegalHeading(1, '7. BANK VERIFICATION'),
    LegalParagraph(
      'To enable Settlements, Restaurant Partners provide bank account details, '
          'which Zopiq may verify to reduce the risk of settlement errors and '
          'fraud. Restaurant Partners are responsible for keeping bank details '
          'accurate and up to date; incorrect details are a common cause of '
          'settlement delays.',
    ),
    LegalHeading(1, '8. BUSINESS VERIFICATION'),
    LegalParagraph(
      'Zopiq may verify business registration, ownership, and contact details, '
          'and confirm that the individual accepting the Restaurant Partner '
          'Agreement is authorised to bind the business. Zopiq may request '
          'supporting documents such as business registration or ownership '
          'evidence.',
    ),
    LegalHeading(2, '8.1 Documents Summary'),
    LegalTable(
      headers: <String>['Document / Detail', 'Purpose'],
      rows: <List<String>>[
        <String>['FSSAI registration / licence', 'Confirm legal authorisation to operate a food business.'],
        <String>['GST registration (where applicable)', 'Tax, invoicing, and settlement.'],
        <String>['PAN (where required)', 'Taxation and financial compliance.'],
        <String>['Bank account details', 'Processing of daily Settlements.'],
        <String>['Business / ownership details', 'Confirm identity and authority of the business.'],
      ],
    ),
    LegalHeading(1, '9. RENEWALS'),
    LegalParagraph(
      'Licences and registrations must remain valid throughout participation. '
          'Restaurant Partners are responsible for renewing FSSAI, GST, and other '
          'applicable registrations before they expire and for updating Zopiq with '
          'current details. Zopiq may request updated documents periodically and '
          'may restrict or suspend Restaurant Partners whose required documents '
          'have lapsed until valid documents are provided.',
    ),
    LegalHeading(1, '10. COMPLIANCE MONITORING'),
    LegalParagraph(
      'Zopiq conducts ongoing Compliance Monitoring, which may include periodic '
          're-verification, review of complaints or food-safety reports, and checks '
          'triggered by risk indicators. Restaurant Partners are expected to '
          'cooperate with Compliance Monitoring and provide reasonably requested '
          'information.',
    ),
    LegalHeading(1, '11. CONSEQUENCES OF NON-COMPLIANCE'),
    LegalParagraph(
      'Where a Restaurant Partner fails Verification, provides false '
          'information, or allows required documents to lapse, Zopiq may restrict '
          'listings, suspend the account pending resolution, or terminate '
          'participation for serious or persistent non-compliance. Falsified '
          'licences or documents are treated as fraud and may result in permanent '
          'termination and referral to authorities.',
    ),
    LegalHeading(1, '12. DATA HANDLING'),
    LegalParagraph(
      'Documents and information collected for Verification are handled in '
          'accordance with the Privacy Policy, including confidentiality, access '
          'controls, and retention only for as long as necessary or as required by '
          'law. Verification data is used only for verification, compliance, fraud '
          'prevention, and related legitimate purposes.',
    ),
    LegalHeading(1, '13. CHANGES TO THIS POLICY'),
    LegalParagraph(
      'Zopiq may update this Policy from time to time to reflect changes in '
          'law, regulatory requirements, or process. Material changes will be '
          'communicated through the Platform or by other reasonable means. The '
          '"Last Updated" date on the cover page indicates the latest version.',
    ),
    LegalHeading(1, '14. CONTACT INFORMATION'),
    LegalParagraph(
      'For questions, requests, or concerns relating to this document, please '
          'contact:',
    ),
    LegalParagraph(
      'Hybrid Monks LLP',
    ),
    LegalParagraph(
      'Brand: Zopiq',
    ),
    LegalParagraph(
      'Registered Office: C/O Meena Dev, Main Road, Sadri, Rajasthan – 306702, '
          'India',
    ),
    LegalParagraph(
      'Email: hello@hybridmonks.com',
    ),
    LegalParagraph(
      'Phone: +91 96608 77411',
    ),
    LegalParagraph(
      'GSTIN: 08AATFH7649R1Z2',
    ),
  ],
);
