// GENERATED BY tool/import_legal.mjs — DO NOT EDIT.
// Source: legal/source/05_Restaurant_Partner_Handbook.docx
//
// Edit the Word document, run `node tool/import_legal.mjs`, commit both.
import 'package:zopiq_legal/src/legal_document.dart';

const LegalDocument restaurantPartnerHandbook = LegalDocument(
  slug: 'restaurant-partner-handbook',
  title: 'Restaurant Partner Handbook',
  subtitle: 'Operational Guide for Zopiq Restaurant Partners',
  docId: 'ZOPIQ-OPS-05',
  version: '1.0',
  effectiveDate: '18 August 2026',
  group: 'partner',
  audiences: <LegalAudience>{LegalAudience.restaurant},
  requiresConsent: false,
  blocks: <LegalBlock>[
    LegalHeading(1, 'Document Control & Version History'),
    LegalParagraph(
      'This document is maintained under version control. Any material '
          'amendment will be recorded in the table below and reflected in the '
          'version number and effective date on the cover page.',
    ),
    LegalTable(
      headers: <String>['Version', 'Date', 'Summary of Changes', 'Approved By'],
      rows: <List<String>>[
        <String>['1.0', '18 August 2026', 'Initial publication-ready version.', 'Hybrid Monks LLP'],
      ],
    ),
    LegalHeading(1, '1. INTRODUCTION'),
    LegalParagraph(
      'This Restaurant Partner Handbook ("Handbook") is a practical operational '
          'guide for restaurants, cloud kitchens, cafés, and food vendors '
          'partnering with Zopiq, operated by Hybrid Monks LLP ("Zopiq", "Company", '
          '"we", "our", or "us"). It explains how to onboard, manage listings, '
          'prepare and package food, handle pickups and complaints, and maintain '
          'the quality standards expected on the Platform.',
    ),
    LegalParagraph(
      'This Handbook is operational guidance and supplements the Restaurant '
          'Partner Agreement, Terms & Conditions, Merchant SLA, and other policies. '
          'Where this Handbook and a binding agreement differ, the agreement '
          'prevails.',
    ),
    LegalHeading(1, '2. DEFINITIONS'),
    LegalParagraph(
      'Restaurant Partner Application means the app or dashboard through which '
          'you manage listings, orders, and settlements.',
    ),
    LegalParagraph(
      'Preparation Time means the time from order acceptance to the order being '
          'ready for pickup.',
    ),
    LegalParagraph(
      'Pickup means collection of a prepared order by a Delivery Partner.',
    ),
    LegalParagraph(
      'SLA means the service levels set out in the Merchant Service Level '
          'Agreement.',
    ),
    LegalHeading(1, '3. RESTAURANT ONBOARDING'),
    LegalParagraph(
      'Onboarding brings your restaurant onto the Platform in a compliant, '
          'ready-to-operate state.',
    ),
    LegalHeading(2, '3.1 Documents Required'),
    LegalParagraph(
      'You will typically be asked to provide the following, subject to the '
          'Restaurant Verification Policy:',
    ),
    LegalBullets(<String>[
        'FSSAI registration or licence (as applicable to your business).',
        'GST registration details (where applicable).',
        'PAN (where required).',
        'Bank account details for settlements.',
        'Business registration or ownership details.',
        'Menu, pricing, and operating hours.',
    ]),
    LegalHeading(2, '3.2 Onboarding Steps'),
    LegalParagraph(
      'The typical onboarding sequence is:',
    ),
    LegalBullets(<String>[
        'Register and submit business and legal information.',
        'Complete verification of licences and bank details.',
        'Build your menu with accurate items, descriptions, prices, and images.',
        'Configure operating hours and preparation times.',
        'Review and accept the Restaurant Partner Agreement and applicable '
            'policies.',
        'Go live once verification and setup are complete.',
    ]),
    LegalHeading(2, '3.3 Keeping Details Current'),
    LegalParagraph(
      'You are responsible for keeping licences, bank details, menus, and '
          'operating hours accurate and up to date. Outdated information is a '
          'common cause of failed orders and settlement delays.',
    ),
    LegalHeading(1, '4. MENU STANDARDS'),
    LegalParagraph(
      'A clear, accurate menu drives orders and reduces disputes.',
    ),
    LegalHeading(2, '4.1 Item Accuracy'),
    LegalParagraph(
      'Each menu item should have an accurate name, a clear description, the '
          'correct price, and correct availability. Portion sizes and key '
          'ingredients should be described where relevant.',
    ),
    LegalHeading(2, '4.2 Pricing'),
    LegalParagraph(
      'Prices displayed on the Platform must match what you intend to charge. '
          'Do not list misleading prices or use the Platform to advertise items you '
          'cannot fulfil.',
    ),
    LegalHeading(2, '4.3 Categories and Structure'),
    LegalParagraph(
      'Organise items into logical categories (for example, starters, mains, '
          'beverages, desserts) so Customers can navigate easily. Keep bestsellers '
          'visible and remove discontinued items promptly.',
    ),
    LegalHeading(2, '4.4 Allergen and Dietary Information'),
    LegalParagraph(
      'Where reasonably practicable, indicate allergen and dietary information '
          '(for example, vegetarian, contains nuts). You remain solely responsible '
          'for the accuracy of allergen and ingredient information.',
    ),
    LegalHeading(1, '5. FOOD PHOTOGRAPHY GUIDELINES'),
    LegalParagraph(
      'Good images increase orders and set accurate expectations.',
    ),
    LegalHeading(2, '5.1 Quality Basics'),
    LegalBullets(<String>[
        'Use natural, even lighting where possible; avoid harsh shadows.',
        'Photograph the actual dish as served, not a stock or unrepresentative '
            'image.',
        'Keep the background clean and uncluttered.',
        'Use a consistent style across your menu for a professional look.',
    ]),
    LegalHeading(2, '5.2 Accuracy'),
    LegalParagraph(
      'Images must reflect the real dish, portion, and presentation. Misleading '
          'images are a common source of complaints and may be removed.',
    ),
    LegalHeading(2, '5.3 Rights'),
    LegalParagraph(
      'Only upload images you own or are licensed to use. By uploading, you '
          'confirm you have the necessary rights, consistent with the Intellectual '
          'Property Policy.',
    ),
    LegalHeading(1, '6. PREPARATION STANDARDS'),
    LegalHeading(2, '6.1 Timeliness'),
    LegalParagraph(
      'Once you accept an order, prepare it within the estimated preparation '
          'time. Consistent, realistic preparation times improve Customer '
          'experience and delivery coordination.',
    ),
    LegalHeading(2, '6.2 Consistency'),
    LegalParagraph(
      'Prepare each dish to a consistent recipe, portion, and presentation so '
          'that Customers receive what they expect every time.',
    ),
    LegalHeading(2, '6.3 Order Accuracy'),
    LegalParagraph(
      'Check each order against the ticket before handover: correct items, '
          'quantities, customisations, and any included utensils or condiments. '
          'Order accuracy is one of the strongest drivers of Customer satisfaction.',
    ),
    LegalHeading(1, '7. PACKAGING STANDARDS'),
    LegalParagraph(
      'Secure packaging protects food quality during transit and reduces '
          'spillage and damage complaints.',
    ),
    LegalHeading(2, '7.1 Leak and Spill Prevention'),
    LegalBullets(<String>[
        'Use containers appropriate to the dish; seal liquids and gravies '
            'securely.',
        'Separate wet and dry items where possible.',
        'Avoid overfilling containers.',
    ]),
    LegalHeading(2, '7.2 Temperature and Freshness'),
    LegalParagraph(
      'Package hot and cold items appropriately to maintain temperature and '
          'freshness. Keep items that should remain separate (for example, ice '
          'cream and hot dishes) in suitable packaging.',
    ),
    LegalHeading(2, '7.3 Tamper-Evidence and Labelling'),
    LegalParagraph(
      'Where possible, use tamper-evident sealing and label bags with the order '
          'reference. This supports food safety and helps Delivery Partners hand '
          'over the correct order.',
    ),
    LegalHeading(1, '8. KITCHEN HYGIENE'),
    LegalParagraph(
      'Hygiene is a legal obligation and a core expectation on the Platform.',
    ),
    LegalHeading(2, '8.1 General Practices'),
    LegalBullets(<String>[
        'Maintain clean preparation surfaces, equipment, and utensils.',
        'Ensure staff follow handwashing and personal hygiene practices.',
        'Store ingredients at correct temperatures and observe use-by dates.',
        'Prevent cross-contamination between raw and cooked foods and known '
            'allergens.',
    ]),
    LegalHeading(2, '8.2 Compliance'),
    LegalParagraph(
      'You must comply with applicable food safety laws, including the Food '
          'Safety and Standards Act, 2006, and maintain a valid FSSAI licence where '
          'required. Zopiq does not inspect or guarantee food quality; '
          'responsibility rests with the Restaurant Partner.',
    ),
    LegalHeading(1, '9. PICKUP WORKFLOW'),
    LegalParagraph(
      'A smooth pickup keeps deliveries on time and food fresh.',
    ),
    LegalHeading(2, '9.1 Preparing for Pickup'),
    LegalParagraph(
      'Have the order packed, sealed, and labelled by the time the Delivery '
          'Partner arrives. Keep prepared orders in a designated handover area.',
    ),
    LegalHeading(2, '9.2 Handover'),
    LegalParagraph(
      'Confirm the order reference with the Delivery Partner and hand over the '
          'correct, complete order. Do not hand over incomplete orders; if an item '
          'is delayed, communicate promptly.',
    ),
    LegalHeading(2, '9.3 Managing Delays'),
    LegalParagraph(
      'If preparation is running late, update the order status where possible '
          'so the Delivery Partner and Customer are informed. Repeated avoidable '
          'delays affect your performance metrics.',
    ),
    LegalHeading(1, '10. COMPLAINT HANDLING'),
    LegalParagraph(
      'Handling complaints well protects your ratings and Customer '
          'relationships.',
    ),
    LegalHeading(2, '10.1 Common Complaint Types'),
    LegalTable(
      headers: <String>['Complaint', 'Typical Cause', 'Preventive Action'],
      rows: <List<String>>[
        <String>['Missing item', 'Order not checked before handover.', 'Verify every order against the ticket at handover.'],
        <String>['Wrong item', 'Similar items confused; mislabelling.', 'Label clearly; double-check customisations.'],
        <String>['Spilled / leaked food', 'Inadequate sealing or packaging.', 'Seal liquids; avoid overfilling; use suitable containers.'],
        <String>['Quality / freshness', 'Delays, temperature loss, inconsistent prep.', 'Prepare to time; package for temperature; keep recipes consistent.'],
      ],
    ),
    LegalHeading(2, '10.2 Responding'),
    LegalParagraph(
      'Cooperate with Zopiq during complaint investigations, provide requested '
          'information promptly, and take corrective action to prevent recurrence.',
    ),
    LegalHeading(1, '11. REFUND HANDLING'),
    LegalParagraph(
      'Refunds are governed by the Refund & Cancellation Policy. Key points for '
          'Restaurant Partners:',
    ),
    LegalBullets(<String>[
        'Wrong item: a replacement or exchange is arranged where reasonably '
            'possible.',
        'Missing item: a refund equal to the verified missing item value may '
            'apply.',
        'Damaged or spilled food: a partial refund may apply after '
            'verification.',
        'Refunds attributable to the restaurant may be deducted from your '
            'settlements.',
    ]),
    LegalParagraph(
      'Accurate preparation and packaging are the most effective way to '
          'minimise refund-related deductions.',
    ),
    LegalHeading(1, '12. RESTAURANT DASHBOARD USAGE'),
    LegalParagraph(
      'The Restaurant Partner Application is your operational control centre.',
    ),
    LegalHeading(2, '12.1 Core Functions'),
    LegalBullets(<String>[
        'Receive, accept, and manage incoming orders.',
        'Update item availability and toggle items on or off.',
        'Manage operating hours and preparation times.',
        'View settlement reports and payout information.',
        'Access performance metrics and ratings.',
    ]),
    LegalHeading(2, '12.2 Good Habits'),
    LegalParagraph(
      'Keep availability accurate in real time, respond to orders promptly, and '
          'review your settlement and performance reports regularly to catch issues '
          'early.',
    ),
    LegalHeading(1, '13. QUALITY EXPECTATIONS'),
    LegalParagraph(
      'Zopiq expects Restaurant Partners to consistently meet standards across '
          'the following dimensions:',
    ),
    LegalTable(
      headers: <String>['Dimension', 'Expectation'],
      rows: <List<String>>[
        <String>['Order accuracy', 'Correct items, quantities, and customisations every time.'],
        <String>['Preparation time', 'Orders ready within the stated preparation time.'],
        <String>['Packaging', 'Secure, leak-resistant, temperature-appropriate packaging.'],
        <String>['Hygiene & safety', 'Full compliance with food safety laws and hygienic practice.'],
        <String>['Availability accuracy', 'Menu and availability kept current to avoid failed orders.'],
        <String>['Cancellations', 'Kept to a minimum and only for genuine operational reasons.'],
      ],
    ),
    LegalHeading(1, '14. PERFORMANCE IMPROVEMENT'),
    LegalParagraph(
      'Where performance falls below expectations, Zopiq may provide guidance '
          'and improvement steps before applying restrictions.',
    ),
    LegalHeading(2, '14.1 Using Your Metrics'),
    LegalParagraph(
      'Review your acceptance rate, preparation times, cancellation rate, and '
          'ratings regularly. Small, consistent improvements — accurate '
          'availability, faster prep, better packaging — compound into stronger '
          'performance and visibility.',
    ),
    LegalHeading(2, '14.2 Improvement Support'),
    LegalParagraph(
      'Zopiq may share operational insights such as order volumes, peak times, '
          'average preparation times, and delivery performance to help you improve. '
          'Persistent or serious issues may lead to reduced visibility, temporary '
          'suspension, or removal under the Merchant SLA and Restaurant Partner '
          'Agreement.',
    ),
    LegalHeading(1, '15. BEST PRACTICES'),
    LegalParagraph(
      'A concise checklist for consistently strong performance:',
    ),
    LegalBullets(<String>[
        'Keep the menu, prices, and availability accurate at all times.',
        'Use honest, high-quality images that reflect the real dish.',
        'Accept orders promptly and prepare within your stated times.',
        'Check every order for accuracy before handover.',
        'Seal and label packaging to prevent spills and mix-ups.',
        'Maintain strict hygiene and food safety compliance.',
        'Respond constructively to complaints and act on feedback.',
        'Review settlement and performance reports regularly.',
    ]),
    LegalHeading(1, '16. CONTACT INFORMATION'),
    LegalParagraph(
      'For questions, requests, or concerns relating to this document, please '
          'contact:',
    ),
    LegalParagraph(
      'Hybrid Monks LLP',
    ),
    LegalParagraph(
      'Brand: Zopiq',
    ),
    LegalParagraph(
      'Registered Office: C/O Meena Dev, Main Road, Sadri, Rajasthan – 306702, '
          'India',
    ),
    LegalParagraph(
      'Email: hello@hybridmonks.com',
    ),
    LegalParagraph(
      'Phone: +91 96608 77411',
    ),
    LegalParagraph(
      'GSTIN: 08AATFH7649R1Z2',
    ),
  ],
);
