// GENERATED BY tool/import_legal.mjs — DO NOT EDIT.
// Source: legal/source/Zopiq_Terms_and_Conditions.docx
//
// Edit the Word document, run `node tool/import_legal.mjs`, commit both.
import 'package:zopiq_legal/src/legal_document.dart';

const LegalDocument termsAndConditions = LegalDocument(
  slug: 'terms-and-conditions',
  title: 'Zopiq Terms & Conditions',
  subtitle: null,
  docId: null,
  version: '1.0',
  effectiveDate: '18 August 2026',
  group: 'core',
  audiences: <LegalAudience>{LegalAudience.customer, LegalAudience.restaurant, LegalAudience.rider},
  requiresConsent: true,
  blocks: <LegalBlock>[
    LegalHeading(1, '1. INTRODUCTION'),
    LegalParagraph(
      'Welcome to Zopiq, an online food ordering and delivery platform owned '
          'and operated by Hybrid Monks LLP, a Limited Liability Partnership '
          'incorporated under the laws of India, having its registered office at:',
    ),
    LegalParagraph(
      'Hybrid Monks LLP',
    ),
    LegalParagraph(
      'C/O Meena Dev, Main Road,',
    ),
    LegalParagraph(
      'Sadri, Rajasthan – 306702, India',
    ),
    LegalParagraph(
      'Email: hello@hybridmonks.com',
    ),
    LegalParagraph(
      'Phone: +91 96608 77411',
    ),
    LegalParagraph(
      'GSTIN: 08AATFH7649R1Z2',
    ),
    LegalParagraph(
      'These Terms and Conditions ("Terms") govern your access to and use of '
          'the Zopiq mobile applications, website, APIs, and related services '
          '(collectively, the "Platform").',
    ),
    LegalParagraph(
      'By creating an account, browsing, placing an order, registering as a '
          'Restaurant Partner, or registering as a Delivery Partner, you '
          'acknowledge that you have read, understood, and agreed to be legally '
          'bound by these Terms.',
    ),
    LegalParagraph(
      'If you do not agree to these Terms, you must immediately discontinue use '
          'of the Platform.',
    ),
    LegalHeading(1, '2. ABOUT ZOPIQ'),
    LegalParagraph(
      'Zopiq is a technology platform that connects:',
    ),
    LegalBullets(<String>[
        'Customers who wish to purchase food and beverages.',
        'Restaurant Partners who prepare and sell food.',
        'Delivery Partners who collect and deliver orders.',
    ]),
    LegalParagraph(
      'Zopiq acts solely as an intermediary facilitating these transactions and '
          'does not prepare, manufacture, package, or sell food.',
    ),
    LegalParagraph(
      'Unless explicitly stated otherwise, all food products are prepared, '
          'packaged, and supplied by independent Restaurant Partners.',
    ),
    LegalHeading(1, '3. DEFINITIONS'),
    LegalParagraph(
      'For these Terms:',
    ),
    LegalParagraph(
      'Account means the registered profile created by a Customer, Restaurant '
          'Partner, or Delivery Partner.',
    ),
    LegalParagraph(
      'Customer means any individual using the Platform to browse, order, or '
          'purchase food.',
    ),
    LegalParagraph(
      'Restaurant Partner means a restaurant, cloud kitchen, café, food vendor, '
          'or business registered on the Platform for selling food.',
    ),
    LegalParagraph(
      'Delivery Partner means an independent individual or entity responsible '
          'for collecting and delivering customer orders.',
    ),
    LegalParagraph(
      'Order means a confirmed request placed through the Platform for food or '
          'related items.',
    ),
    LegalParagraph(
      'Platform means the Zopiq mobile applications, website, software, APIs, '
          'and associated services.',
    ),
    LegalParagraph(
      'COD (Cash on Delivery) means an order where a Customer pays a mandatory '
          'advance online and the remaining amount upon successful delivery.',
    ),
    LegalParagraph(
      'Advance Payment means the mandatory 40% payment collected before '
          'confirmation of a COD order.',
    ),
    LegalParagraph(
      'Force Majeure Event means any event beyond the reasonable control of '
          'Hybrid Monks LLP, including natural disasters, strikes, riots, '
          'epidemics, governmental actions, internet failures, power outages, '
          'cyber-attacks, or similar events.',
    ),
    LegalHeading(1, '4. ACCEPTANCE OF TERMS'),
    LegalParagraph(
      'By using Zopiq, you represent and warrant that:',
    ),
    LegalBullets(<String>[
        'You have the legal capacity to enter into binding agreements.',
        'The information provided by you is true, complete, and accurate.',
        'You agree to comply with these Terms and all applicable laws.',
        'You agree to our Privacy Policy and other policies published by Zopiq.',
    ]),
    LegalParagraph(
      'Your continued use of the Platform constitutes ongoing acceptance of '
          'these Terms.',
    ),
    LegalHeading(1, '5. ELIGIBILITY'),
    LegalHeading(2, 'Customers'),
    LegalParagraph(
      'Individuals aged 18 years or older may create an account and place '
          'orders.',
    ),
    LegalParagraph(
      'Users below 18 years of age may use the Platform only with the consent '
          'and supervision of a parent or legal guardian.',
    ),
    LegalParagraph(
      'The parent or guardian assumes full responsibility for the minor\'s use '
          'of the Platform.',
    ),
    LegalHeading(2, 'Restaurant Partners'),
    LegalParagraph(
      'Restaurant Partners must:',
    ),
    LegalBullets(<String>[
        'Be legally authorised to operate a food business in India.',
        'Hold all necessary registrations, licences, permits, and approvals, '
            'including a valid FSSAI licence where applicable.',
        'Have the authority to enter into binding agreements on behalf of the '
            'business.',
    ]),
    LegalHeading(2, 'Delivery Partners'),
    LegalParagraph(
      'Delivery Partners must:',
    ),
    LegalBullets(<String>[
        'Be at least 18 years of age.',
        'Hold a valid government-issued identity proof.',
        'Possess a valid driving licence (where applicable).',
        'Operate a legally compliant vehicle if required.',
        'Comply with all applicable traffic and transport laws.',
    ]),
    LegalHeading(1, '6. ACCOUNT REGISTRATION'),
    LegalParagraph(
      'Users must provide accurate and complete information during '
          'registration.',
    ),
    LegalParagraph(
      'Users agree to:',
    ),
    LegalBullets(<String>[
        'Keep login credentials confidential.',
        'Immediately notify Zopiq of any unauthorised access.',
        'Maintain updated contact information.',
        'Use only one personal account unless otherwise authorised.',
    ]),
    LegalParagraph(
      'Zopiq reserves the right to suspend or terminate accounts containing '
          'false, misleading, or fraudulent information.',
    ),
    LegalHeading(1, '7. PLATFORM SERVICES'),
    LegalParagraph(
      'Zopiq provides a digital marketplace enabling Customers to:',
    ),
    LegalBullets(<String>[
        'Browse restaurants.',
        'View menus.',
        'Place food orders.',
        'Track deliveries.',
        'Make online payments.',
        'Submit ratings and reviews.',
    ]),
    LegalParagraph(
      'Restaurant Partners can:',
    ),
    LegalBullets(<String>[
        'List menus.',
        'Accept or reject orders.',
        'Update availability.',
        'Receive settlements.',
        'Manage business information.',
    ]),
    LegalParagraph(
      'Delivery Partners can:',
    ),
    LegalBullets(<String>[
        'Accept delivery assignments.',
        'Navigate to pickup and delivery locations.',
        'Receive earnings.',
        'Track completed deliveries.',
    ]),
    LegalParagraph(
      'Zopiq reserves the right to modify, suspend, or discontinue any feature '
          'or service at any time without prior notice.',
    ),
    LegalHeading(1, '8. CUSTOMER ACCOUNTS'),
    LegalParagraph(
      'Customers are responsible for ensuring that:',
    ),
    LegalBullets(<String>[
        'Delivery addresses are accurate.',
        'Phone numbers remain reachable.',
        'Payment information is valid.',
        'Orders are placed in good faith.',
    ]),
    LegalParagraph(
      'Customers must not:',
    ),
    LegalBullets(<String>[
        'Place fake orders.',
        'Abuse Restaurants or Delivery Partners.',
        'Attempt payment fraud.',
        'Use automated systems or bots.',
        'Exploit pricing errors.',
        'Misuse promotional offers or referral programs.',
    ]),
    LegalParagraph(
      'Repeated violations may result in suspension or permanent termination of '
          'the account.',
    ),
    LegalHeading(1, '9. RESTAURANT PARTNER ACCOUNTS'),
    LegalParagraph(
      'Restaurant Partners agree to:',
    ),
    LegalBullets(<String>[
        'Display accurate menus and prices.',
        'Maintain hygiene standards.',
        'Prepare food according to applicable food safety laws.',
        'Package food securely.',
        'Honour confirmed orders except where cancellation is necessary due to '
            'genuine operational reasons.',
        'Keep inventory information reasonably up to date.',
    ]),
    LegalParagraph(
      'Restaurant Partners remain solely responsible for the quality, '
          'ingredients, preparation, packaging, allergen information, and legality '
          'of the food supplied.',
    ),
    LegalHeading(1, '10. DELIVERY PARTNER ACCOUNTS'),
    LegalParagraph(
      'Delivery Partners agree to:',
    ),
    LegalBullets(<String>[
        'Behave professionally and respectfully.',
        'Follow delivery instructions.',
        'Deliver orders without unreasonable delay.',
        'Not tamper with, open, or consume customer orders.',
        'Comply with applicable traffic laws.',
        'Refrain from providing services while under the influence of alcohol '
            'or drugs.',
    ]),
    LegalParagraph(
      'Delivery Partners operate as independent contractors and are not '
          'employees, agents, or representatives of Hybrid Monks LLP.',
    ),
    LegalHeading(1, '11. ORDER PLACEMENT'),
    LegalParagraph(
      'An order is considered placed only after:',
    ),
    LegalBullets(<String>[
        'The Customer selects the desired items.',
        'The applicable charges are displayed.',
        'The required payment is successfully processed.',
        'The Restaurant Partner accepts the order.',
    ]),
    LegalParagraph(
      'Zopiq reserves the right to reject or cancel any order in cases '
          'including but not limited to suspected fraud, pricing errors, technical '
          'issues, unavailability of items, or violations of these Terms.',
    ),
    LegalHeading(1, '12. CASH ON DELIVERY (COD) POLICY'),
    LegalParagraph(
      'To reduce fraudulent and abandoned orders, Zopiq requires Customers '
          'choosing Cash on Delivery to pay an advance amount.',
    ),
    LegalHeading(2, '12.1 Advance Payment'),
    LegalParagraph(
      'For every COD order:',
    ),
    LegalBullets(<String>[
        'The Customer shall pay 40% of the total order value online as an '
            'advance.',
        'The remaining 60% shall be paid in cash or by another accepted method '
            'upon successful delivery, if permitted by the Platform.',
    ]),
    LegalHeading(2, '12.2 Non-Refundable Advance'),
    LegalParagraph(
      'If a Customer:',
    ),
    LegalBullets(<String>[
        'refuses to accept the order,',
        'is unavailable at the delivery address after reasonable delivery '
            'attempts,',
        'provides an incorrect delivery address,',
        'intentionally abandons the order, or',
        'otherwise causes the order to fail after preparation,',
    ]),
    LegalParagraph(
      'the 40% advance payment shall be forfeited and shall not be refunded.',
    ),
    LegalHeading(2, '12.3 Restaurant Cancellation'),
    LegalParagraph(
      'If a Restaurant Partner cancels an order before preparation due to '
          'reasons attributable to the restaurant (such as stock unavailability or '
          'inability to fulfil the order), the Customer shall receive a refund of '
          'the advance payment in accordance with the applicable refund process.',
    ),
    LegalHeading(2, '12.4 Platform Rights'),
    LegalParagraph(
      'Repeated refusal of COD orders or abuse of the COD facility may result '
          'in:',
    ),
    LegalBullets(<String>[
        'temporary suspension of COD privileges,',
        'mandatory prepaid-only orders, or',
        'suspension or termination of the Customer account.',
    ]),
    LegalHeading(1, '13. PAYMENT POLICY'),
    LegalParagraph(
      'Zopiq supports electronic payment methods including UPI, debit cards, '
          'credit cards, net banking, and other payment options made available on '
          'the Platform. Cash on Delivery is available only where offered by Zopiq.',
    ),
    LegalParagraph(
      'Payment processing may be handled by authorised third-party payment '
          'service providers. Zopiq does not store complete payment card '
          'information and is not responsible for failures, delays, or errors '
          'caused by external payment systems.',
    ),
    LegalParagraph(
      'For orders requiring advance payment, an order will not be confirmed '
          'until the required amount has been successfully received.',
    ),
    LegalParagraph(
      'Where a balance payment remains due at delivery, the Customer must pay '
          'the remaining amount before taking possession of the order, unless '
          'another payment arrangement is expressly permitted by the Platform.',
    ),
    LegalParagraph(
      'In the event of a payment processing issue affecting settlement, Zopiq '
          'may deduct a platform processing fee of ₹10, and the remaining eligible '
          'amount shall be settled to the Restaurant Partner in accordance with the '
          'Platform\'s settlement process, subject to applicable laws and '
          'reconciliation requirements.',
    ),
    LegalHeading(1, '14. ORDER ACCEPTANCE AND PREPARATION'),
    LegalParagraph(
      '14.1 An order shall be deemed accepted only after the Restaurant Partner '
          'confirms the order through the Platform.',
    ),
    LegalParagraph(
      '14.2 Until acceptance, a Restaurant Partner reserves the right to reject '
          'an order due to, including but not limited to:',
    ),
    LegalBullets(<String>[
        'Item unavailability.',
        'Restaurant closure.',
        'Technical issues.',
        'Excessive order volume.',
        'Safety concerns.',
        'Force Majeure Events.',
    ]),
    LegalParagraph(
      '14.3 Once accepted, the Restaurant Partner shall make reasonable efforts '
          'to prepare the order within the estimated preparation time displayed on '
          'the Platform.',
    ),
    LegalParagraph(
      '14.4 Estimated preparation and delivery times are indicative only and '
          'may vary due to traffic, weather conditions, restaurant workload, '
          'festivals, public holidays, or other unforeseen circumstances.',
    ),
    LegalHeading(1, '15. CUSTOMER CANCELLATION POLICY'),
    LegalHeading(2, '15.1 Before Restaurant Acceptance'),
    LegalParagraph(
      'Customers may cancel an order before the Restaurant Partner accepts it.',
    ),
    LegalParagraph(
      'Where payment has already been collected, the applicable amount shall be '
          'refunded in accordance with the Refund Policy.',
    ),
    LegalHeading(2, '15.2 After Restaurant Acceptance'),
    LegalParagraph(
      'Once a Restaurant Partner has accepted an order, cancellation by the '
          'Customer is not permitted.',
    ),
    LegalHeading(2, '15.3 During Food Preparation'),
    LegalParagraph(
      'Orders cannot be cancelled once food preparation has commenced.',
    ),
    LegalHeading(2, '15.4 After Dispatch'),
    LegalParagraph(
      'Orders cannot be cancelled once assigned to a Delivery Partner or '
          'dispatched from the Restaurant.',
    ),
    LegalHeading(2, '15.5 Abuse of Cancellation'),
    LegalParagraph(
      'Zopiq reserves the right to suspend, restrict, or permanently terminate '
          'accounts that repeatedly misuse the cancellation facility or place '
          'orders without the intention to complete the purchase.',
    ),
    LegalHeading(1, '16. RESTAURANT CANCELLATION POLICY'),
    LegalParagraph(
      'Restaurant Partners may cancel an order only for genuine operational '
          'reasons, including:',
    ),
    LegalBullets(<String>[
        'Food item unavailable.',
        'Kitchen malfunction.',
        'Restaurant closure.',
        'Safety or health emergency.',
        'Force Majeure Event.',
    ]),
    LegalParagraph(
      'Restaurants shall not intentionally cancel accepted orders to manipulate '
          'availability, pricing, ratings, or customer experience.',
    ),
    LegalParagraph(
      'Repeated cancellations may result in:',
    ),
    LegalBullets(<String>[
        'Warning notices.',
        'Reduced platform visibility.',
        'Temporary suspension.',
        'Permanent removal from Zopiq.',
    ]),
    LegalHeading(1, '17. DELIVERY FAILURE'),
    LegalParagraph(
      'Delivery may be considered unsuccessful where:',
    ),
    LegalBullets(<String>[
        'Customer refuses delivery.',
        'Customer is unreachable.',
        'Incorrect address is provided.',
        'Customer refuses to pay the remaining COD balance.',
        'Delivery location is unsafe.',
        'Fraud is suspected.',
    ]),
    LegalParagraph(
      'Where delivery fails due to Customer fault:',
    ),
    LegalBullets(<String>[
        'the 40% advance shall remain non-refundable;',
        'the Customer may be charged applicable delivery costs where permitted '
            'by law; and',
        'Zopiq may restrict future COD orders or suspend the Customer\'s '
            'account.',
    ]),
    LegalHeading(1, '18. REFUND POLICY'),
    LegalParagraph(
      'Refunds are processed solely in accordance with this section.',
    ),
    LegalHeading(2, '18.1 Wrong Item Delivered'),
    LegalParagraph(
      'Where an incorrect food item is delivered:',
    ),
    LegalBullets(<String>[
        'No monetary refund shall be issued.',
        'Zopiq shall arrange a replacement or exchange where reasonably '
            'possible.',
        'Replacement availability depends on the Restaurant Partner.',
    ]),
    LegalHeading(2, '18.2 Missing Items'),
    LegalParagraph(
      'If one or more items are missing from an order:',
    ),
    LegalParagraph(
      'The Customer shall receive a refund equivalent only to the value of the '
          'verified missing item(s).',
    ),
    LegalHeading(2, '18.3 Damaged Food'),
    LegalParagraph(
      'Where food is damaged during preparation, packaging, or delivery, Zopiq '
          'may provide a partial refund after verification.',
    ),
    LegalHeading(2, '18.4 Spilled Food'),
    LegalParagraph(
      'Where food becomes unusable due to spillage during delivery, Zopiq may '
          'provide a partial refund after investigation.',
    ),
    LegalHeading(2, '18.5 Food Quality'),
    LegalParagraph(
      'Taste preferences are subjective.',
    ),
    LegalParagraph(
      'Refunds shall not be granted merely because the Customer did not like '
          'the taste of food.',
    ),
    LegalParagraph(
      'Complaints regarding stale, unsafe, contaminated, or spoiled food shall '
          'be investigated individually.',
    ),
    LegalHeading(2, '18.6 Late Delivery'),
    LegalParagraph(
      'Delays caused by:',
    ),
    LegalBullets(<String>[
        'Traffic',
        'Weather',
        'Festivals',
        'Road closures',
        'Restaurant preparation',
        'Government restrictions',
        'Force Majeure',
    ]),
    LegalParagraph(
      'shall not automatically entitle the Customer to a refund.',
    ),
    LegalHeading(2, '18.7 Incorrect Address'),
    LegalParagraph(
      'No refund shall be provided where delivery fails because the Customer '
          'entered an incorrect or incomplete delivery address.',
    ),
    LegalHeading(2, '18.8 Failed COD Orders'),
    LegalParagraph(
      'Where the Customer refuses delivery or causes the order to fail, the 40% '
          'advance payment shall not be refunded.',
    ),
    LegalHeading(1, '19. DELIVERY POLICY'),
    LegalParagraph(
      'Delivery charges are determined dynamically.',
    ),
    LegalParagraph(
      'Charges may vary depending on:',
    ),
    LegalBullets(<String>[
        'Distance.',
        'Demand.',
        'Weather conditions.',
        'Time of day.',
        'Availability of Delivery Partners.',
        'Government restrictions.',
        'Special events.',
    ]),
    LegalParagraph(
      'Zopiq does not guarantee fixed delivery fees.',
    ),
    LegalHeading(2, '19.1 Rain Charges'),
    LegalParagraph(
      'Additional delivery fees may apply during adverse weather conditions.',
    ),
    LegalHeading(2, '19.2 Night Charges'),
    LegalParagraph(
      'Additional delivery charges may apply during late-night operating hours.',
    ),
    LegalHeading(2, '19.3 Dynamic Pricing'),
    LegalParagraph(
      'Delivery fees may increase during periods of exceptionally high demand.',
    ),
    LegalParagraph(
      'Customers shall always be informed of the applicable charges before '
          'confirming an order.',
    ),
    LegalHeading(1, '20. CUSTOMER RESPONSIBILITIES'),
    LegalParagraph(
      'Customers agree to:',
    ),
    LegalBullets(<String>[
        'Provide accurate delivery information.',
        'Remain reachable during delivery.',
        'Pay all applicable charges.',
        'Treat Restaurant Partners and Delivery Partners respectfully.',
        'Cooperate during dispute investigations.',
    ]),
    LegalParagraph(
      'Customers shall not:',
    ),
    LegalBullets(<String>[
        'Place fake orders.',
        'Abuse customer support.',
        'Use abusive, threatening, discriminatory, or offensive language.',
        'Attempt payment fraud.',
        'Submit false refund claims.',
        'Manipulate the rating system.',
        'Abuse promotional offers.',
        'Create multiple accounts to evade restrictions.',
    ]),
    LegalParagraph(
      'Violation of this section may result in immediate suspension or '
          'permanent termination of the Customer account.',
    ),
    LegalHeading(1, '21. RESTAURANT RESPONSIBILITIES'),
    LegalParagraph(
      'Restaurant Partners shall:',
    ),
    LegalBullets(<String>[
        'Maintain all required licences and approvals.',
        'Comply with applicable food safety regulations.',
        'Hold a valid FSSAI licence where required.',
        'Display accurate menu descriptions and prices.',
        'Prepare food using hygienic practices.',
        'Use fresh ingredients.',
        'Package food securely to reduce the risk of leakage or contamination.',
        'Honour accepted orders except where cancellation is permitted under '
            'these Terms.',
    ]),
    LegalParagraph(
      'Restaurant Partners remain solely responsible for:',
    ),
    LegalBullets(<String>[
        'Food quality.',
        'Ingredients.',
        'Allergens.',
        'Portion sizes.',
        'Packaging.',
        'Hygiene.',
        'Compliance with food safety laws.',
    ]),
    LegalParagraph(
      'Zopiq does not inspect or guarantee the quality of food prepared by '
          'Restaurant Partners.',
    ),
    LegalHeading(1, '22. DELIVERY PARTNER RESPONSIBILITIES'),
    LegalParagraph(
      'Delivery Partners shall:',
    ),
    LegalBullets(<String>[
        'Accept only orders they intend to complete.',
        'Reach pickup locations promptly.',
        'Deliver orders safely.',
        'Follow reasonable delivery instructions.',
        'Maintain professional conduct.',
        'Protect Customer privacy.',
        'Avoid tampering with food.',
    ]),
    LegalParagraph(
      'Delivery Partners shall not:',
    ),
    LegalBullets(<String>[
        'Open food packages.',
        'Consume Customer food.',
        'Request additional payments beyond Platform-authorised charges.',
        'Deliver while under the influence of alcohol or drugs.',
        'Harass Customers or Restaurant staff.',
    ]),
    LegalParagraph(
      'Repeated violations may result in permanent deactivation.',
    ),
    LegalHeading(1, '23. RATINGS AND REVIEWS'),
    LegalParagraph(
      'Customers may submit ratings and reviews after order completion.',
    ),
    LegalParagraph(
      'Reviews must:',
    ),
    LegalBullets(<String>[
        'Reflect genuine experiences.',
        'Avoid abusive language.',
        'Avoid discriminatory content.',
        'Avoid defamatory statements.',
        'Avoid false allegations.',
    ]),
    LegalParagraph(
      'Zopiq reserves the right to remove reviews that violate these Terms.',
    ),
    LegalParagraph(
      'By posting reviews, users grant Zopiq a non-exclusive, worldwide, '
          'royalty-free licence to display, reproduce, and use such content for '
          'Platform operations, quality improvement, and promotional purposes.',
    ),
    LegalHeading(1, '24. PROHIBITED CONDUCT'),
    LegalParagraph(
      'Users shall not:',
    ),
    LegalBullets(<String>[
        'Violate applicable laws.',
        'Use bots or automated ordering systems.',
        'Attempt to hack or interfere with the Platform.',
        'Upload malware or malicious code.',
        'Impersonate another individual.',
        'Submit forged documents.',
        'Abuse Restaurants.',
        'Abuse Delivery Partners.',
        'Abuse Customer Support staff.',
        'Engage in fraudulent transactions.',
        'Attempt chargeback fraud.',
        'Manipulate ratings or reviews.',
        'Resell Platform services without permission.',
        'Infringe intellectual property rights.',
        'Use the Platform to facilitate illegal activities.',
        'Order or distribute prohibited products, including alcohol where not '
            'permitted by the Platform or applicable law.',
    ]),
    LegalParagraph(
      'Zopiq reserves the right to investigate suspected violations and take '
          'appropriate action, including suspension, termination, reporting to law '
          'enforcement, or legal proceedings where necessary.',
    ),
    LegalHeading(1, '25. INTELLECTUAL PROPERTY RIGHTS'),
    LegalHeading(2, '25.1 Ownership'),
    LegalParagraph(
      'Unless otherwise stated, all rights, title, and interest in and to the '
          'Platform, including but not limited to:',
    ),
    LegalBullets(<String>[
        'Zopiq name',
        'Zopiq logo',
        'Mobile applications',
        'Website',
        'Software',
        'Source code',
        'APIs',
        'UI/UX designs',
        'Icons',
        'Graphics',
        'Animations',
        'Databases',
        'Business processes',
        'Documentation',
        'Audio',
        'Video',
        'Marketing material',
        'Text',
        'Artificial intelligence models',
        'Algorithms',
    ]),
    LegalParagraph(
      'are owned by or licensed to Hybrid Monks LLP and are protected under '
          'applicable copyright, trademark, patent, trade secret, and other '
          'intellectual property laws.',
    ),
    LegalParagraph(
      'Nothing in these Terms transfers ownership of any intellectual property '
          'to any user.',
    ),
    LegalHeading(2, '25.2 Limited License'),
    LegalParagraph(
      'Subject to compliance with these Terms, Zopiq grants users a limited, '
          'non-exclusive, non-transferable, revocable license to access and use the '
          'Platform solely for its intended purpose.',
    ),
    LegalParagraph(
      'This license does not permit users to:',
    ),
    LegalBullets(<String>[
        'Copy the Platform.',
        'Modify the Platform.',
        'Reverse engineer any software.',
        'Sell Platform content.',
        'Redistribute Platform software.',
        'Create competing products using Zopiq technology.',
        'Scrape data from the Platform.',
    ]),
    LegalHeading(2, '25.3 Trademarks'),
    LegalParagraph(
      '"Zopiq", its logos, branding elements, slogans, and associated marks are '
          'trademarks or registered trademarks of Hybrid Monks LLP.',
    ),
    LegalParagraph(
      'Users shall not use these marks without prior written permission.',
    ),
    LegalHeading(1, '26. USER-GENERATED CONTENT'),
    LegalParagraph(
      'Users may upload:',
    ),
    LegalBullets(<String>[
        'Reviews',
        'Ratings',
        'Profile photographs',
        'Restaurant images',
        'Menu images',
        'Comments',
        'Other content permitted by the Platform',
    ]),
    LegalParagraph(
      'Users retain ownership of their content but grant Zopiq a worldwide, '
          'non-exclusive, royalty-free, sublicensable license to:',
    ),
    LegalBullets(<String>[
        'Host',
        'Store',
        'Display',
        'Reproduce',
        'Modify (for formatting purposes)',
        'Publish',
        'Distribute',
    ]),
    LegalParagraph(
      'such content in connection with operating, improving, promoting, and '
          'securing the Platform.',
    ),
    LegalParagraph(
      'Users warrant that any uploaded content:',
    ),
    LegalBullets(<String>[
        'Belongs to them or they have permission to use it.',
        'Does not infringe third-party rights.',
        'Is lawful.',
        'Is not misleading.',
        'Does not contain malware or harmful code.',
    ]),
    LegalHeading(1, '27. PLATFORM RIGHTS'),
    LegalParagraph(
      'Zopiq reserves the right to:',
    ),
    LegalBullets(<String>[
        'Reject any order.',
        'Cancel any order.',
        'Refuse service.',
        'Suspend any account.',
        'Remove any listing.',
        'Modify Platform features.',
        'Update pricing mechanisms.',
        'Change commission structures with notice where applicable.',
        'Remove content.',
        'Require identity verification.',
        'Investigate suspicious activity.',
        'Introduce new policies.',
    ]),
    LegalParagraph(
      'These rights may be exercised where reasonably necessary to protect '
          'users, comply with law, maintain platform integrity, or prevent fraud.',
    ),
    LegalHeading(1, '28. FRAUD PREVENTION'),
    LegalParagraph(
      'To protect Customers, Restaurants, Delivery Partners, and the Platform, '
          'Zopiq may implement fraud detection measures, including:',
    ),
    LegalBullets(<String>[
        'Device verification.',
        'IP address analysis.',
        'Payment risk assessment.',
        'Multiple account detection.',
        'Order pattern analysis.',
        'Identity verification.',
        'Location verification.',
        'Behavioural analytics.',
    ]),
    LegalParagraph(
      'Where fraudulent activity is reasonably suspected, Zopiq may:',
    ),
    LegalBullets(<String>[
        'Hold payments temporarily while investigating.',
        'Cancel orders.',
        'Restrict payment methods.',
        'Disable Cash on Delivery.',
        'Request additional verification.',
        'Suspend or terminate accounts.',
        'Report unlawful conduct to relevant authorities.',
    ]),
    LegalParagraph(
      'Providing false information, forged documents, or engaging in payment '
          'fraud may lead to permanent account termination and legal action.',
    ),
    LegalHeading(1, '29. ACCOUNT SUSPENSION AND TERMINATION'),
    LegalHeading(2, '29.1 Suspension'),
    LegalParagraph(
      'Zopiq may temporarily suspend an account where there is reasonable '
          'belief that a user has:',
    ),
    LegalBullets(<String>[
        'Violated these Terms.',
        'Committed fraud.',
        'Submitted false information.',
        'Misused promotional offers.',
        'Abused support staff.',
        'Threatened or harassed another user.',
        'Repeatedly refused COD deliveries.',
        'Engaged in suspicious payment activity.',
        'Attempted unauthorized access to the Platform.',
    ]),
    LegalParagraph(
      'Suspension may remain in effect while an investigation is conducted.',
    ),
    LegalHeading(2, '29.2 Permanent Termination'),
    LegalParagraph(
      'Zopiq may permanently terminate accounts for serious or repeated '
          'violations, including:',
    ),
    LegalBullets(<String>[
        'Criminal activity.',
        'Identity fraud.',
        'Chargeback fraud.',
        'Falsified restaurant licenses.',
        'Delivery theft.',
        'Food tampering.',
        'Repeated fake orders.',
        'Repeated abusive conduct.',
        'Intellectual property infringement.',
        'Use of automated bots.',
        'Distribution of prohibited items.',
    ]),
    LegalParagraph(
      'Termination may occur without prior notice where immediate action is '
          'reasonably necessary to protect users or comply with legal obligations.',
    ),
    LegalHeading(2, '29.3 Effect of Termination'),
    LegalParagraph(
      'Upon termination:',
    ),
    LegalBullets(<String>[
        'Access to the Platform may be revoked immediately.',
        'Pending settlements may be withheld until verification is completed, '
            'subject to applicable law.',
        'Legal obligations that survive termination shall remain enforceable.',
    ]),
    LegalHeading(1, '30. LIMITATION OF LIABILITY'),
    LegalParagraph(
      'To the fullest extent permitted by applicable law:',
    ),
    LegalParagraph(
      'Hybrid Monks LLP and Zopiq shall not be liable for:',
    ),
    LegalBullets(<String>[
        'Indirect damages.',
        'Incidental damages.',
        'Consequential damages.',
        'Special damages.',
        'Loss of profits.',
        'Loss of goodwill.',
        'Business interruption.',
        'Loss of data.',
        'Emotional distress.',
        'Third-party actions.',
    ]),
    LegalParagraph(
      'Zopiq provides a technology platform connecting independent Customers, '
          'Restaurant Partners, and Delivery Partners. Food preparation, quality, '
          'ingredients, and compliance with food safety laws remain the '
          'responsibility of the Restaurant Partner. Delivery execution remains the '
          'responsibility of the Delivery Partner.',
    ),
    LegalParagraph(
      'Where liability cannot legally be excluded, Zopiq\'s aggregate liability '
          'shall not exceed the amount of Platform service fees actually received '
          'by Zopiq in connection with the specific order giving rise to the claim, '
          'unless a higher liability is required by applicable law.',
    ),
    LegalHeading(1, '31. DISCLAIMER OF WARRANTIES'),
    LegalParagraph(
      'The Platform is provided on an "as is" and "as available" basis.',
    ),
    LegalParagraph(
      'To the extent permitted by law, Zopiq disclaims all warranties, whether '
          'express or implied, including warranties of:',
    ),
    LegalBullets(<String>[
        'Merchantability.',
        'Fitness for a particular purpose.',
        'Non-infringement.',
        'Availability.',
        'Accuracy.',
        'Reliability.',
        'Security.',
    ]),
    LegalParagraph(
      'Zopiq does not guarantee:',
    ),
    LegalBullets(<String>[
        'Continuous Platform availability.',
        'Error-free operation.',
        'Uninterrupted service.',
        'Restaurant availability.',
        'Delivery within estimated times.',
        'Availability of specific menu items.',
    ]),
    LegalHeading(1, '32. FOOD SAFETY DISCLAIMER'),
    LegalParagraph(
      'Restaurant Partners are solely responsible for:',
    ),
    LegalBullets(<String>[
        'Food preparation.',
        'Hygiene.',
        'Ingredients.',
        'Allergen disclosures.',
        'Expiry of ingredients.',
        'Packaging.',
        'Compliance with food safety laws.',
    ]),
    LegalParagraph(
      'Customers with allergies or dietary restrictions are responsible for '
          'reviewing available information and contacting the Restaurant Partner '
          'where necessary before placing an order.',
    ),
    LegalParagraph(
      'Zopiq is not responsible for allergic reactions or dietary issues '
          'arising from information supplied by Restaurant Partners.',
    ),
    LegalHeading(1, '33. DELIVERY DISCLAIMER'),
    LegalParagraph(
      'Estimated delivery times are estimates only.',
    ),
    LegalParagraph(
      'Delays may occur due to:',
    ),
    LegalBullets(<String>[
        'Weather.',
        'Traffic.',
        'Road closures.',
        'Public events.',
        'Government restrictions.',
        'Restaurant delays.',
        'Vehicle breakdowns.',
        'Force Majeure Events.',
    ]),
    LegalParagraph(
      'Such delays do not automatically entitle Customers to refunds or '
          'compensation.',
    ),
    LegalHeading(1, '34. INDEMNIFICATION'),
    LegalParagraph(
      'Users agree to indemnify, defend, and hold harmless Hybrid Monks LLP, '
          'Zopiq, its partners, officers, directors, employees, affiliates, '
          'contractors, and agents from and against any claims, liabilities, '
          'losses, damages, costs, expenses, fines, penalties, or reasonable legal '
          'fees arising out of or related to:',
    ),
    LegalBullets(<String>[
        'Breach of these Terms.',
        'Violation of applicable law.',
        'Fraudulent conduct.',
        'Misuse of the Platform.',
        'Infringement of third-party rights.',
        'Content uploaded by the user.',
        'Negligence or intentional misconduct.',
    ]),
    LegalParagraph(
      'This obligation survives termination of the user\'s account.',
    ),
    LegalHeading(1, '35. FORCE MAJEURE'),
    LegalParagraph(
      'Zopiq shall not be liable for any delay or failure to perform its '
          'obligations where such delay or failure results from events beyond its '
          'reasonable control, including:',
    ),
    LegalBullets(<String>[
        'Natural disasters.',
        'Floods.',
        'Earthquakes.',
        'Fire.',
        'Pandemic or epidemic.',
        'War.',
        'Civil unrest.',
        'Terrorist acts.',
        'Government actions.',
        'Internet outages.',
        'Power failures.',
        'Cyber-attacks.',
        'Labour strikes.',
        'Transportation disruptions.',
    ]),
    LegalParagraph(
      'During a Force Majeure Event, affected obligations shall be suspended '
          'for the duration of the event, and Zopiq will make reasonable efforts to '
          'resume normal operations as soon as practicable.',
    ),
    LegalHeading(1, '36. COMPLIANCE WITH LAWS'),
    LegalParagraph(
      'All users agree to comply with applicable laws and regulations, '
          'including but not limited to:',
    ),
    LegalBullets(<String>[
        'Information Technology Act, 2000 (India), as amended.',
        'Digital Personal Data Protection Act, 2023.',
        'Consumer Protection Act, 2019.',
        'Food Safety and Standards Act, 2006 (where applicable).',
        'Goods and Services Tax laws.',
        'Motor Vehicles Act (for Delivery Partners).',
        'Any other applicable central, state, or local laws.',
    ]),
    LegalParagraph(
      'Users are solely responsible for ensuring that their activities on the '
          'Platform comply with applicable legal',
    ),
    LegalHeading(1, '37. GOVERNING LAW'),
    LegalParagraph(
      'These Terms and all matters arising from or relating to the Platform '
          'shall be governed by and construed in accordance with the laws of the '
          'Republic of India.',
    ),
    LegalParagraph(
      'Nothing in these Terms limits any non-waivable rights available to '
          'consumers under applicable law.',
    ),
    LegalHeading(1, '38. JURISDICTION'),
    LegalParagraph(
      'Unless otherwise required by applicable law, the courts having '
          'jurisdiction over Bali, Rajasthan, India, shall have exclusive '
          'jurisdiction over disputes arising out of or relating to these Terms or '
          'the use of the Platform.',
    ),
    LegalParagraph(
      'Where a consumer protection law grants a Customer the right to bring '
          'proceedings before another competent forum, nothing in this clause is '
          'intended to override that statutory right.',
    ),
    LegalHeading(1, '39. DISPUTE RESOLUTION'),
    LegalHeading(2, '39.1 Customer Support First'),
    LegalParagraph(
      'Before initiating legal proceedings, users agree to make reasonable '
          'efforts to resolve disputes through Zopiq Customer Support.',
    ),
    LegalParagraph(
      'Users may contact:',
    ),
    LegalParagraph(
      'Email: hello@hybridmonks.com',
    ),
    LegalParagraph(
      'Phone: +91 96608 77411',
    ),
    LegalHeading(2, '39.2 Investigation'),
    LegalParagraph(
      'Zopiq may investigate complaints relating to:',
    ),
    LegalBullets(<String>[
        'Payments',
        'Refunds',
        'Missing items',
        'Damaged food',
        'Restaurant disputes',
        'Delivery disputes',
        'Fraud',
        'Abuse',
        'Policy violations',
    ]),
    LegalParagraph(
      'Users agree to cooperate by providing any reasonably requested '
          'information or evidence.',
    ),
    LegalHeading(2, '39.3 Mediation (Optional)'),
    LegalParagraph(
      'Where appropriate, the parties may mutually agree to attempt mediation '
          'before commencing formal legal proceedings.',
    ),
    LegalHeading(1, '40. ELECTRONIC COMMUNICATIONS'),
    LegalParagraph(
      'By using the Platform, users consent to receive electronic '
          'communications from Zopiq, including:',
    ),
    LegalBullets(<String>[
        'Order confirmations',
        'Delivery updates',
        'Payment receipts',
        'OTPs',
        'Security alerts',
        'Policy updates',
        'Service announcements',
        'Promotional communications (where consent has been provided and as '
            'permitted by applicable law)',
    ]),
    LegalParagraph(
      'Electronic communications satisfy any legal requirement that such '
          'communications be in writing.',
    ),
    LegalHeading(1, '41. NOTICES'),
    LegalParagraph(
      'Official notices from Zopiq may be sent by:',
    ),
    LegalBullets(<String>[
        'Email',
        'SMS',
        'Push notification',
        'In-app notification',
        'Website publication',
    ]),
    LegalParagraph(
      'Users are responsible for keeping their contact details current.',
    ),
    LegalParagraph(
      'A notice is deemed received when it is sent to the contact information '
          'provided by the user or published through the Platform, unless '
          'applicable law provides otherwise.',
    ),
    LegalHeading(1, '42. MODIFICATION OF TERMS'),
    LegalParagraph(
      'Zopiq may update these Terms from time to time to reflect changes in:',
    ),
    LegalBullets(<String>[
        'Laws or regulations',
        'Platform features',
        'Business operations',
        'Security requirements',
        'Payment methods',
        'Services offered',
    ]),
    LegalParagraph(
      'Material changes will be communicated through the Platform or by other '
          'reasonable means.',
    ),
    LegalParagraph(
      'Continued use of the Platform after the effective date of revised Terms '
          'constitutes acceptance of the updated Terms.',
    ),
    LegalHeading(1, '43. ACCOUNT DELETION'),
    LegalParagraph(
      'Users may request deletion of their accounts through the Platform or by '
          'contacting Customer Support.',
    ),
    LegalParagraph(
      'Account deletion is subject to:',
    ),
    LegalBullets(<String>[
        'Verification of account ownership.',
        'Settlement of outstanding dues (for Restaurant Partners and Delivery '
            'Partners).',
        'Retention of records where required by applicable law or for fraud '
            'prevention, taxation, accounting, dispute resolution, or regulatory '
            'compliance.',
    ]),
    LegalParagraph(
      'Deletion of an account does not automatically erase information that '
          'Zopiq is legally required or otherwise permitted to retain.',
    ),
    LegalParagraph(
      'Further details are provided in the Account Deletion & Data Retention '
          'Policy.',
    ),
    LegalHeading(1, '44. PRIVACY'),
    LegalParagraph(
      'The collection, use, disclosure, storage, and protection of personal '
          'data are governed by the Zopiq Privacy Policy, which forms an integral '
          'part of these Terms.',
    ),
    LegalParagraph(
      'By using the Platform, users acknowledge that they have read and '
          'understood the Privacy Policy.',
    ),
    LegalHeading(1, '45. THIRD-PARTY SERVICES'),
    LegalParagraph(
      'The Platform may integrate with third-party services, including but not '
          'limited to:',
    ),
    LegalBullets(<String>[
        'Payment gateways',
        'Maps and navigation providers',
        'SMS and email providers',
        'Cloud hosting providers',
        'Analytics providers',
        'Notification services',
    ]),
    LegalParagraph(
      'Zopiq is not responsible for the availability, content, or independent '
          'policies of third-party services. Users remain subject to the terms and '
          'privacy policies of those third parties where applicable.',
    ),
    LegalHeading(1, '46. ASSIGNMENT'),
    LegalParagraph(
      'Users may not assign or transfer their rights or obligations under these '
          'Terms without the prior written consent of Zopiq.',
    ),
    LegalParagraph(
      'Zopiq may assign or transfer its rights and obligations under these '
          'Terms in connection with a merger, acquisition, restructuring, sale of '
          'assets, or other corporate transaction, subject to applicable law.',
    ),
    LegalHeading(1, '47. SEVERABILITY'),
    LegalParagraph(
      'If any provision of these Terms is held to be invalid, illegal, or '
          'unenforceable by a court of competent jurisdiction, that provision shall '
          'be enforced to the maximum extent permitted by law, and the remaining '
          'provisions shall continue in full force and effect.',
    ),
    LegalHeading(1, '48. WAIVER'),
    LegalParagraph(
      'Failure by Zopiq to enforce any provision of these Terms shall not '
          'constitute a waiver of that provision or of any other provision.',
    ),
    LegalParagraph(
      'Any waiver shall be effective only if made in writing by an authorised '
          'representative of Zopiq.',
    ),
    LegalHeading(1, '49. ENTIRE AGREEMENT'),
    LegalParagraph(
      'These Terms, together with the Privacy Policy, Account Deletion & Data '
          'Retention Policy, Restaurant Partner Agreement, Delivery Partner '
          'Agreement, and any other policies expressly incorporated by reference, '
          'constitute the entire agreement between the user and Hybrid Monks LLP '
          'regarding the use of the Platform.',
    ),
    LegalParagraph(
      'They supersede all prior understandings, communications, or agreements '
          'relating to the same subject matter.',
    ),
    LegalHeading(1, '50. SURVIVAL'),
    LegalParagraph(
      'The following provisions shall survive the termination or deletion of an '
          'account to the extent necessary to fulfil their purpose:',
    ),
    LegalBullets(<String>[
        'Payment obligations',
        'Refund obligations',
        'Intellectual Property',
        'Confidentiality',
        'Indemnification',
        'Limitation of Liability',
        'Dispute Resolution',
        'Governing Law',
        'Jurisdiction',
        'Data Retention',
        'Fraud Investigations',
        'Tax and Accounting Requirements',
    ]),
    LegalHeading(1, '51. CONTACT INFORMATION'),
    LegalParagraph(
      'Brand Name: Zopiq',
    ),
    LegalParagraph(
      'Owned and Operated by: Hybrid Monks LLP',
    ),
    LegalParagraph(
      'Registered Office:',
    ),
    LegalParagraph(
      'C/O Meena Dev',
    ),
    LegalParagraph(
      'Main Road',
    ),
    LegalParagraph(
      'Sadri, Rajasthan – 306702',
    ),
    LegalParagraph(
      'India',
    ),
    LegalParagraph(
      'Email: hello@hybridmonks.com',
    ),
    LegalParagraph(
      'Phone: +91 96608 77411',
    ),
    LegalParagraph(
      'GSTIN: 08AATFH7649R1Z2',
    ),
    LegalParagraph(
      'For legal notices, users should contact the email address above unless '
          'Zopiq designates another address in writing.',
    ),
    LegalHeading(1, 'APPENDIX A – COD POLICY SUMMARY'),
    LegalBullets(<String>[
        'Cash on Delivery orders require a 40% advance payment.',
        'The remaining 60% is payable upon delivery (or by another method '
            'accepted by the Platform).',
        'If the Customer refuses delivery, is unavailable after reasonable '
            'attempts, provides an incorrect address, or otherwise causes the order '
            'to fail after preparation, the 40% advance is non-refundable.',
        'Repeated abuse of the COD facility may result in restriction or '
            'removal of COD privileges and/or suspension of the Customer account.',
    ]),
    LegalHeading(1, 'APPENDIX B – RESTAURANT COMMISSION'),
    LegalParagraph(
      'Unless otherwise agreed in writing:',
    ),
    LegalBullets(<String>[
        'Zopiq charges a platform commission of ₹10 per item sold through the '
            'Platform.',
        'Commission is deducted before settlement.',
        'Zopiq may revise commission structures prospectively with reasonable '
            'notice to Restaurant Partners.',
    ]),
    LegalHeading(1, 'APPENDIX C – PAYMENT SETTLEMENTS'),
    LegalHeading(2, 'Restaurant Partners'),
    LegalBullets(<String>[
        'Settlements are processed daily, subject to successful reconciliation, '
            'applicable deductions, and legal requirements.',
        'Settlement reports will be made available through the Restaurant '
            'Partner application or dashboard.',
    ]),
    LegalHeading(2, 'Delivery Partners'),
    LegalBullets(<String>[
        'Delivery Partner earnings are processed daily, subject to verification '
            'of completed deliveries and applicable deductions or adjustments.',
        'Zopiq reserves the right to withhold or adjust payouts where fraud, '
            'duplicate deliveries, or policy violations are reasonably suspected, '
            'pending investigation.',
    ]),
    LegalHeading(1, 'APPENDIX D – PROHIBITED ITEMS'),
    LegalParagraph(
      'The following categories are prohibited on the Platform unless expressly '
          'permitted by applicable law and by Zopiq:',
    ),
    LegalBullets(<String>[
        'Alcoholic beverages',
        'Tobacco and nicotine products',
        'Illegal drugs or controlled substances',
        'Weapons',
        'Explosives',
        'Hazardous chemicals',
        'Counterfeit goods',
        'Stolen property',
        'Any other items prohibited by law or by Zopiq\'s policies',
    ]),
    LegalParagraph(
      'Restaurants must not list or sell prohibited items through the Platform.',
    ),
    LegalHeading(1, 'APPENDIX E – POLICY HIERARCHY'),
    LegalParagraph(
      'In the event of any inconsistency:',
    ),
    LegalBullets(<String>[
        'Restaurant Partner Agreement (for Restaurant Partners)',
        'Delivery Partner Agreement (for Delivery Partners)',
        'Privacy Policy',
        'Account Deletion & Data Retention Policy',
        'These Terms & Conditions',
    ]),
    LegalParagraph(
      'shall apply in that order, to the extent of the inconsistency and as '
          'permitted by applicable law.',
    ),
  ],
);
