// GENERATED BY tool/import_legal.mjs — DO NOT EDIT.
// Source: legal/source/15_Website_Terms_of_Use.docx
//
// Edit the Word document, run `node tool/import_legal.mjs`, commit both.
import 'package:zopiq_legal/src/legal_document.dart';

const LegalDocument websiteTermsOfUse = LegalDocument(
  slug: 'website-terms-of-use',
  title: 'Website Terms of Use',
  subtitle: 'Use of the Zopiq Website and Web Services',
  docId: 'ZOPIQ-LEGAL-15',
  version: '1.0',
  effectiveDate: '18 August 2026',
  group: 'support',
  audiences: <LegalAudience>{LegalAudience.customer},
  requiresConsent: false,
  blocks: <LegalBlock>[
    LegalHeading(1, 'Document Control & Version History'),
    LegalParagraph(
      'This document is maintained under version control. Any material '
          'amendment will be recorded in the table below and reflected in the '
          'version number and effective date on the cover page.',
    ),
    LegalTable(
      headers: <String>['Version', 'Date', 'Summary of Changes', 'Approved By'],
      rows: <List<String>>[
        <String>['1.0', '18 August 2026', 'Initial publication-ready version.', 'Hybrid Monks LLP'],
      ],
    ),
    LegalHeading(1, '1. INTRODUCTION'),
    LegalParagraph(
      'These Website Terms of Use ("Terms") govern your access to and use of '
          'the Zopiq website and supported web services (the "Website"), operated '
          'by Hybrid Monks LLP ("Zopiq", "Company", "we", "our", or "us"). By '
          'accessing or using the Website, you agree to these Terms. If you do not '
          'agree, you should not use the Website.',
    ),
    LegalParagraph(
      'These Terms supplement, and are read together with, the Zopiq Terms & '
          'Conditions, Privacy Policy, Cookie Policy, and other applicable '
          'policies. Where the Zopiq Terms & Conditions and these Terms address the '
          'same subject, the Terms & Conditions prevail for Platform transactions.',
    ),
    LegalHeading(1, '2. DEFINITIONS'),
    LegalParagraph(
      'Website means the Zopiq website and supported web services.',
    ),
    LegalParagraph(
      'Content means text, graphics, images, software, and other material made '
          'available on the Website.',
    ),
    LegalParagraph(
      'User means any person who accesses or uses the Website.',
    ),
    LegalParagraph(
      'Account means a registered profile used to access certain features.',
    ),
    LegalHeading(1, '3. ELIGIBILITY AND ACCEPTANCE'),
    LegalParagraph(
      'By using the Website, you represent that you have the legal capacity to '
          'enter into these Terms and that you will use the Website in accordance '
          'with these Terms and applicable law. Continued use of the Website '
          'constitutes ongoing acceptance of these Terms as updated from time to '
          'time.',
    ),
    LegalHeading(1, '4. WEBSITE USAGE'),
    LegalParagraph(
      'You may use the Website only for lawful purposes and in accordance with '
          'these Terms.',
    ),
    LegalHeading(2, '4.1 Permitted Use'),
    LegalParagraph(
      'You may browse the Website, access information about Zopiq services, and '
          'use features made available to you for their intended purpose.',
    ),
    LegalHeading(2, '4.2 Prohibited Use'),
    LegalParagraph(
      'You shall not:',
    ),
    LegalBullets(<String>[
        'Use the Website in violation of applicable law or these Terms.',
        'Attempt to hack, disrupt, or interfere with the Website or its '
            'security.',
        'Upload or transmit malware or malicious code.',
        'Scrape, harvest, or extract data except as expressly permitted.',
        'Use bots or automated systems to access the Website without '
            'permission.',
        'Impersonate any person or misrepresent your affiliation.',
        'Infringe the intellectual property or other rights of any person.',
    ]),
    LegalHeading(1, '5. ACCOUNTS'),
    LegalParagraph(
      'Certain features may require an Account. You are responsible for '
          'providing accurate information, keeping your credentials confidential, '
          'and for activity under your Account. You must notify Zopiq promptly of '
          'any unauthorised access. Zopiq may suspend or terminate Accounts that '
          'contain false information or are used in breach of these Terms.',
    ),
    LegalHeading(1, '6. CONTENT'),
    LegalHeading(2, '6.1 Our Content'),
    LegalParagraph(
      'Content on the Website is provided for general information and for the '
          'operation of Zopiq services. It may be updated or removed at any time. '
          'Content is provided on an "as is" basis and may not always be complete '
          'or current.',
    ),
    LegalHeading(2, '6.2 Your Content'),
    LegalParagraph(
      'Where you submit content through the Website, you are responsible for it '
          'and warrant that it is lawful and does not infringe third-party rights. '
          'You grant Zopiq a licence to use such content consistent with the Terms '
          '& Conditions and Intellectual Property Policy.',
    ),
    LegalHeading(1, '7. INTELLECTUAL PROPERTY'),
    LegalParagraph(
      'The Website and its Content, including the Zopiq name, logos, software, '
          'and design, are owned by or licensed to Hybrid Monks LLP and protected '
          'by intellectual property laws. These Terms grant you a limited, '
          'non-exclusive, non-transferable, revocable licence to access and use the '
          'Website for its intended purpose, and do not transfer any intellectual '
          'property to you. Use of Zopiq marks requires prior written permission.',
    ),
    LegalHeading(1, '8. LINKS TO THIRD-PARTY SITES'),
    LegalParagraph(
      'The Website may contain links to third-party websites or services. Zopiq '
          'is not responsible for the availability, content, or practices of '
          'third-party sites, and links do not imply endorsement. Your use of '
          'third-party sites is subject to their own terms and privacy policies.',
    ),
    LegalHeading(1, '9. COOKIES'),
    LegalParagraph(
      'The Website uses cookies and similar technologies as described in the '
          'Cookie Policy. By using the Website, you agree to the use of cookies in '
          'accordance with that policy, subject to any consent required by '
          'applicable law.',
    ),
    LegalHeading(1, '10. DISCLAIMERS'),
    LegalParagraph(
      'The Website is provided on an "as is" and "as available" basis. To the '
          'extent permitted by law, Zopiq disclaims all warranties, express or '
          'implied, including merchantability, fitness for a particular purpose, '
          'non-infringement, availability, accuracy, reliability, and security. '
          'Zopiq does not guarantee continuous, error-free, or uninterrupted '
          'operation of the Website.',
    ),
    LegalHeading(1, '11. LIMITATION OF LIABILITY'),
    LegalParagraph(
      'To the fullest extent permitted by applicable law, Hybrid Monks LLP and '
          'Zopiq shall not be liable for any indirect, incidental, consequential, '
          'or special damages, loss of profits, loss of data, or business '
          'interruption arising out of or relating to your use of the Website. '
          'Where liability cannot legally be excluded, it is limited to the maximum '
          'extent permitted by law. Nothing in these Terms limits liability that '
          'cannot be limited under applicable law.',
    ),
    LegalHeading(1, '12. INDEMNIFICATION'),
    LegalParagraph(
      'You agree to indemnify and hold harmless Hybrid Monks LLP, Zopiq, and '
          'its partners, officers, directors, employees, affiliates, and agents '
          'from claims, liabilities, losses, damages, costs, and reasonable legal '
          'fees arising out of your breach of these Terms, your misuse of the '
          'Website, or your violation of applicable law or third-party rights.',
    ),
    LegalHeading(1, '13. DISPUTES, GOVERNING LAW, AND JURISDICTION'),
    LegalParagraph(
      'These Terms are governed by the laws of the Republic of India. Before '
          'initiating legal proceedings, Users are encouraged to resolve disputes '
          'through Zopiq support and, where appropriate, mediation, consistent with '
          'the Terms & Conditions and Grievance Redressal Policy. Subject to '
          'applicable law, the courts having jurisdiction over the location '
          'specified in the Zopiq Terms & Conditions shall have jurisdiction over '
          'disputes relating to the Website, without overriding any non-waivable '
          'consumer rights.',
    ),
    LegalHeading(1, '14. CHANGES TO THESE TERMS'),
    LegalParagraph(
      'Zopiq may update these Terms from time to time to reflect changes in '
          'law, Website features, or operations. Material changes will be '
          'communicated through the Website or by other reasonable means. Continued '
          'use of the Website after the effective date constitutes acceptance of '
          'the updated Terms.',
    ),
    LegalHeading(1, '15. CONTACT INFORMATION'),
    LegalParagraph(
      'For questions, requests, or concerns relating to this document, please '
          'contact:',
    ),
    LegalParagraph(
      'Hybrid Monks LLP',
    ),
    LegalParagraph(
      'Brand: Zopiq',
    ),
    LegalParagraph(
      'Registered Office: C/O Meena Dev, Main Road, Sadri, Rajasthan – 306702, '
          'India',
    ),
    LegalParagraph(
      'Email: hello@hybridmonks.com',
    ),
    LegalParagraph(
      'Phone: +91 96608 77411',
    ),
    LegalParagraph(
      'GSTIN: 08AATFH7649R1Z2',
    ),
  ],
);
