-- 0131 — consent is a record, not a checkbox.
--
-- The sign-in screens now refuse to sign anybody in until they tick a box
-- saying they have read the Terms & Conditions and the Privacy Policy. A tick
-- that lives only in the widget's `setState` is not consent — it is a widget.
-- Under the DPDP Act the question that gets asked afterwards is *who* agreed,
-- to *which version*, and *when*, and none of those survive a rebuild.
--
-- So the tick gates the button on the device, and this records what it meant on
-- the server, once there is a user id to record it against. That ordering is
-- forced rather than chosen: consent is given on the sign-in screen, which is by
-- definition the one screen where nobody is signed in yet.
--
-- ---------------------------------------------------------------------------
-- Why the version is a string from the documents and not a number here.
-- ---------------------------------------------------------------------------
-- `legalConsentVersion` is generated by `tool/import_legal.mjs` from the version
-- fields of the two consent documents themselves. Bump a document in Word,
-- re-run the importer, and the constant changes; `has_accepted_policies` then
-- answers false for everybody and the whole userbase is asked again. A version
-- kept anywhere else is a version that gets forgotten on the release where it
-- mattered.
--
-- ---------------------------------------------------------------------------
-- Append-only, and unreachable except through the two functions.
-- ---------------------------------------------------------------------------
-- An acceptance is evidence. Evidence a user can rewrite is not evidence, and
-- 0089 and 0092 are the standing reminders that a new table arrives writable to
-- `anon` and a new function arrives executable by PUBLIC. So: every grant is
-- revoked from the table, RLS is on with no policy at all (which denies
-- everything, including the TRUNCATE that RLS would not have covered anyway),
-- and the only two doors are the SECURITY DEFINER functions below.

-- ===========================================================================
-- A. The record.
-- ===========================================================================
create table if not exists public.policy_acceptances (
  id          uuid primary key default gen_random_uuid(),
  user_id     uuid not null references auth.users (id) on delete cascade,

  -- The generated consent version — '1.0' today.
  version     text not null check (length(version) between 1 and 200),

  -- Which app the tick happened in. The same person may be a customer and a
  -- rider, and they agreed twice, in two places, on two days.
  surface     text not null check (surface in ('customer', 'vendor', 'rider')),

  -- The slugs that were named beside the tick box. Stored rather than inferred,
  -- because what somebody agreed to is what the screen said at the time, not
  -- what the current build happens to list.
  documents   text[] not null,

  accepted_at timestamptz not null default now()
);

-- One row per person, per version, per app. A second sign-in on a second phone
-- is the same consent, not a new one, and 40 rows per user would bury the one
-- that answers the question.
create unique index if not exists policy_acceptances_user_version_surface_key
  on public.policy_acceptances (user_id, version, surface);

comment on table public.policy_acceptances is
  'Who accepted which version of the terms and privacy policy, from which app, '
  'and when. Append-only; reachable only via record_policy_acceptance and '
  'has_accepted_policies.';

-- ===========================================================================
-- B. Nobody touches it directly.
-- ===========================================================================
alter table public.policy_acceptances enable row level security;

-- No policy is declared on purpose. RLS with zero policies denies every row to
-- every non-superuser role, which is exactly the intent: the functions below
-- are SECURITY DEFINER and bypass it, and nothing else has any business here.

revoke all on public.policy_acceptances from public;
revoke all on public.policy_acceptances from anon;
revoke all on public.policy_acceptances from authenticated;

-- ===========================================================================
-- C. Writing one.
-- ===========================================================================
-- `auth.uid()` and not an argument: a user id passed in from a client is a user
-- id a client can change, and an acceptance signed in somebody else's name is
-- worse than no acceptance at all.
create or replace function public.record_policy_acceptance(
  p_version   text,
  p_surface   text,
  p_documents text[]
)
returns void
language plpgsql
security definer
set search_path = public, pg_catalog
as $$
declare
  v_user uuid := auth.uid();
begin
  if v_user is null then
    raise exception 'not signed in'
      using errcode = '42501';
  end if;

  insert into public.policy_acceptances (user_id, version, surface, documents)
  values (v_user, p_version, p_surface, p_documents)
  -- Idempotent. The app calls this after every sign-in, not only the first, so
  -- that a session predating the gate is picked up the next time it signs in.
  -- The first acceptance is the one that counts, so a repeat changes nothing —
  -- including `accepted_at`, which must keep saying when they actually agreed.
  on conflict (user_id, version, surface) do nothing;
end;
$$;

comment on function public.record_policy_acceptance(text, text, text[]) is
  'Records that the calling user accepted a version of the consent documents. '
  'Idempotent per (user, version, surface).';

-- ===========================================================================
-- D. Asking whether they already did.
-- ===========================================================================
-- Not scoped by surface, deliberately. Somebody who accepted version 1.0 in the
-- customer app has read the same two documents that the rider app would show
-- them; asking again because they opened a different one of our apps is a
-- second tick that means nothing.
create or replace function public.has_accepted_policies(p_version text)
returns boolean
language sql
security definer
set search_path = public, pg_catalog
stable
as $$
  select exists (
    select 1
      from public.policy_acceptances
     where user_id = auth.uid()
       and version = p_version
  );
$$;

comment on function public.has_accepted_policies(text) is
  'Whether the calling user has accepted the given consent version, in any app.';

-- ===========================================================================
-- E. Who may call them.
-- ===========================================================================
-- Two routes in, and both are closed before either is opened (0089). A
-- SECURITY DEFINER function left executable by PUBLIC is a signed-out caller
-- writing rows as nobody, or reading whether nobody has consented — harmless
-- here only by accident, and the accident is the part that does not repeat.
revoke all on function public.record_policy_acceptance(text, text, text[]) from public;
revoke all on function public.record_policy_acceptance(text, text, text[]) from anon;
revoke all on function public.has_accepted_policies(text) from public;
revoke all on function public.has_accepted_policies(text) from anon;

grant execute on function public.record_policy_acceptance(text, text, text[]) to authenticated;
grant execute on function public.has_accepted_policies(text) to authenticated;
