-- Migration 140: every kitchen sells a cold drink.
--
-- Eight bottled drinks — Coca Cola, Thums Up, Sprite, Limca, Fanta, Mirinda,
-- 7Up, Maaza — in two sizes each, on the menu of every restaurant on the
-- platform. Nobody stocked a branded soft drink before this: the beverage
-- sections held lassi, shakes and fresh lime and nothing that comes sealed.
--
-- **These are menu items, not options.** The obvious-looking alternative was a
-- `menu_option_groups` add-on group hung off every dish (0048), and it is the
-- wrong shape three times over: `menu_options` has no image column, so a drink
-- could never carry a photograph; an option folds into its dish's line, so two
-- curries would force two Cokes and the kitchen would read
-- "Paneer Butter Masala (Coca Cola)" as one line; and `dish_options_sheet`
-- opens for *any* dish with a group, so attaching one to all 998 dishes would
-- put a modal in front of every ADD button on the platform. A drink is a thing
-- you buy, with its own count and its own picture. The "add a drink" prompt at
-- the moment of adding to the cart is a customer-app concern, and it reads these
-- rows.
--
-- **Prices are MRP + ₹10**, the platform markup every dish carries — ₹20 → ₹30
-- for 250 ml and ₹40 → ₹50 for the large. Decided explicitly rather than
-- inherited: a sealed bottle prints its own MRP, so this is the one place on the
-- menu where the markup is visible to the customer as a difference from the
-- label. Confirmed 2026-08-29.
--
-- **GST stays at 500 bps**, matching all 998 existing rows and the rest of the
-- restaurant supply, rather than the packaged-aerated-drink slab. Also an
-- explicit call, not an oversight.
--
-- **Maaza's large is 600 ml, not 750 ml.** Coca-Cola India does not make a
-- 750 ml Maaza; 600 ml is the pack that exists, at the same ₹40 MRP. The seven
-- aerated drinks all take 750 ml.
--
-- Idempotent: ids are derived from the restaurant and the drink, and a re-run
-- refreshes the name, price, description and artwork. It deliberately does NOT
-- reset `is_available` — a vendor who has turned a drink off has said something,
-- and re-running a seed is not a reason to overrule them.

-- ---------------------------------------------------------------------------
-- The catalogue: eight drinks, two sizes, one drawing each.
-- ---------------------------------------------------------------------------
-- `image_url` carries no `/v<version>/` segment on purpose. The artwork is
-- generated by `tool/seed_beverages.mjs`, which uploads with a deterministic
-- public_id and `invalidate=true` — so the day real packshets replace these
-- drawings, that script is re-run and these rows do not move.
with drink (slug, label, liquid_rank) as (
  values
    ('coca-cola', 'Coca Cola', 0),
    ('thums-up',  'Thums Up',  1),
    ('sprite',    'Sprite',    2),
    ('limca',     'Limca',     3),
    ('fanta',     'Fanta',     4),
    ('mirinda',   'Mirinda',   5),
    ('7up',       '7Up',       6),
    ('maaza',     'Maaza',     7)
),
-- Size 0 is the single-serve that pairs with one meal; size 1 is the bottle a
-- table shares. They are adjacent in `item_rank` so a brand's two sizes sit
-- next to each other rather than the menu listing all the smalls then all the
-- larges.
sized as (
  select
    d.slug,
    d.label,
    d.liquid_rank,
    s.size_rank,
    case
      when s.size_rank = 0 then '250 ml'
      when d.slug = 'maaza' then '600 ml'  -- no 750 ml Maaza is made
      else '750 ml'
    end                                        as size_label,
    case when s.size_rank = 0 then 30 else 50 end as price  -- MRP + ₹10
  from drink d
  cross join (values (0), (1)) as s (size_rank)
),
-- Where the section goes, and where in it these sixteen start.
--
-- Two kitchens already have a category called exactly "Beverages" — Mamaji
-- Snacks sells a Bisleri out of one and the demo kitchen a Cold Coffee — so
-- this joins their section instead of opening a second one with the same name
-- and a different rank. The customer app groups by category *name*, so a
-- duplicate would not show as two headings; it would show as one heading whose
-- items are ordered by a rank the vendor never chose. Everyone else gets a new
-- section at the end of their menu.
--
-- Both subqueries read the pre-INSERT snapshot, so all sixteen rows of a
-- restaurant agree on the same answer.
placed as (
  select
    r.id as restaurant_id,
    coalesce(
      (
        select min(m.category_rank)
          from public.menu_items m
         where m.restaurant_id = r.id and m.category = 'Beverages'
      ),
      (
        select coalesce(max(m.category_rank), -1) + 1
          from public.menu_items m
         where m.restaurant_id = r.id
      )
    ) as category_rank,
    coalesce(
      (
        select max(m.item_rank) + 1
          from public.menu_items m
         where m.restaurant_id = r.id and m.category = 'Beverages'
      ),
      0
    ) as item_offset
  from public.restaurants r
)
insert into public.menu_items (
  id, restaurant_id, name, description, price, is_veg, is_bestseller,
  image_url, category, category_rank, item_rank, is_available,
  category_available, gst_rate_bps
)
select
  'bev-' || p.restaurant_id || '-' || z.slug || '-' || z.size_rank,
  p.restaurant_id,
  z.label || ' (' || z.size_label || ')',
  'Chilled ' || z.size_label || ' bottle.',
  z.price,
  true,   -- a soft drink is vegetarian, and the green dot is load-bearing here
  false,
  'https://res.cloudinary.com/w69i7qes/image/upload/zopiqnow/beverages/' || z.slug || '.jpg',
  'Beverages',
  p.category_rank,
  p.item_offset + z.liquid_rank * 2 + z.size_rank,
  true,
  true,
  500
from placed p
cross join sized z
on conflict (id) do update set
  name        = excluded.name,
  description = excluded.description,
  price       = excluded.price,
  image_url   = excluded.image_url;
